### ISSUE TITLE
$queue[] is broken?

### ISSUE THREAD

**Issue by Alconera130** [aoijs/aoi.js#104]
now playing: flamingo remix
current queue:
1.) bad apple
2.) bad apple remix
^ this is my current queue. And i noticed that there is an error, i evaled it and...
![Screenshot (43)](https://user-images.githubusercontent.com/83458587/117940559-086fb100-b2be-11eb-8b9a-5d793f31a089.png)

**Comment by DiscordBond** [comment]
Your queue only has two songs so there is no second page… not a bug. Check documentation of $queue function please

**Comment by Alconera130** [comment]
> Your queue only has two songs so there is no second page… not a bug. Check documentation of $queue function please

oki
