### ISSUE TITLE
$getCooldownTime error

### ISSUE THREAD

**Issue by bubblejoey** [aoijs/aoi.js#105]
## Type
- [ ] Functions: \$getCooldownTime
- [ ] Callbacks: \<Callback Name>
- [ ] Handlers: \$loadCommands
- [ ] Others: \______

Code used:
```
$globalCooldown[1d;{title:Daily Rewards}{thumbnail:$authorAvatar}{description:You have claimed your daily rewards already!}{field:Claim again after:$getCooldownTime[globalUser;daily;no]}{color:f44336}]
Error get: ❌ Invalid cooldown type on $getCooldownTime[globalUser;daily;no] at line 7
```

More:
- Aoi.js version: 1.0.6
- Node.js version: v12.22.1
- Operating system: Debian

Screenshots (If any): Image or Link
![Screenshot_2021_0513_151105](https://user-images.githubusercontent.com/74786022/118091808-d9f8ef80-b3fd-11eb-9219-e2e8ac14bee1.png)
![Screenshot_2021_0513_151137](https://user-images.githubusercontent.com/74786022/118091820-debda380-b3fd-11eb-8241-692027b50c4b.png)

**Comment by USERSATOSHI** [comment]
@bubblejoey You are missing one field in getcooldowntime

**Comment by DiscordBond** [comment]
You need to put the duration In the first field of $getCooldownTime

**Comment by bubblejoey** [comment]
ah ye the id my bad

**Comment by bubblejoey** [comment]
thanks btw

**Comment by bubblejoey** [comment]
![Screenshot_2021_0513_152348](https://user-images.githubusercontent.com/74786022/118092911-49bbaa00-b3ff-11eb-8115-3ec021a4886e.png)
I still get an error

**Comment by USERSATOSHI** [comment]
no u are missing the time field 🤦

**Comment by USERSATOSHI** [comment]
@bubblejoey

**Comment by bubblejoey** [comment]
Fixed already, DerBond help me on the server. Thanks for the help!
