### ISSUE TITLE
Optional field in $awaitMessages, $reactionCollector and $awaitReactions.

### ISSUE THREAD

**Issue by Eduard1221** [aoijs/aoi.js#110]
## Type
- [x] Functions: $awaitMessages, $awaitReactions and $reactionCollector

## Description
Add a field called "channelID" in these commands so we can make the bot to await replies or reactions in an another channel

**Comment by DiscordBond** [comment]
> ## Type
> * [x]  Functions: $awaitMessages, $awaitReactions and $reactionCollector
> 
> ## Description
> Add a field called "channelID" in these commands so we can make the bot to await replies or reactions in an another channel

Alright 😉

**Comment by Leref** [comment]
#55
