### ISSUE TITLE
$justMembersCount

### ISSUE THREAD

**Issue by Gamerlagan-lag** [aoijs/aoi.js#113]
## Type
- [ ] Functions: $justMembersCount

## Description
Gets the members of the server not including bots.

**Comment by falsisdev** [comment]
> 
> ## Type
> - [ ] Functions: $justMembersCount
> 
> ## Description
> Gets the members of the server not including bots.

$math[$membersCount-$botCount]
Or
$sub[$membersCount;$botCount]

**Comment by Gamerlagan-lag** [comment]
Ok thanks sorry for your time

**Comment by falsisdev** [comment]
> Ok thanks sorry for your time

Np

**Comment by DiscordBond** [comment]
$membersCount has a field to say yes/no if bots should be counted to
