### ISSUE TITLE
$getConsoleError function

### ISSUE THREAD

**Issue by falsisdev** [aoijs/aoi.js#114]
# $getConsoleError

## Usage;
$getConsoleError

## Example
```js
$channelSendMessage[$channelID;$getConsoleError[$djsEval[falsis.hi;yes]];no]
```
Output: 
- falsis is not defined in `$djsEval[falsis.hi;yes]` at line 1

**Comment by USERSATOSHI** [comment]
djseval already does that

there is error: property which get interpreter errors

and 

the bot.onFunctionError () 

covers the getConsoleError 
@falsisdev

**Comment by USERSATOSHI** [comment]
djseval already does that

there is error: property which get interpreter errors

and 

the bot.onFunctionError () 

covers the getConsoleError 
@falsisdev

**Comment by falsisdev** [comment]
> djseval already does that
> 
> there is error: property which get interpreter errors
> 
> and 
> 
> the bot.onFunctionError () 
> 
> covers the getConsoleError 
> @falsisdev 

Hmmm, How can I get a command with the method you said to get the console error? Can you give me an example? :)

**Comment by DiscordBond** [comment]
Hey, just follow the guide of $error in our documentation. You can use the "error" property in your command to execute that code if console error/ interpreter error comes up. Using $error returns the console error the interpreter threw… you can use it inside $channelSendMessage as example

**Comment by falsisdev** [comment]
> Hey, just follow the guide of $error in our documentation. You can use the "error" property in your command to execute that code if console error/ interpreter error comes up. Using $error returns the console error the interpreter threw… you can use it inside $channelSendMessage as example

This works! Thanks!!

**Comment by USERSATOSHI** [comment]
> > Hey, just follow the guide of $error in our documentation. You can use the "error" property in your command to execute that code if console error/ interpreter error comes up. Using $error returns the console error the interpreter threw… you can use it inside $channelSendMessage as example
> 
> This works! Thanks!!

if you checked #sneakpeak  u can see a clip on the callback bot.onFunctionError()

**Comment by falsisdev** [comment]
> > > Hey, just follow the guide of $error in our documentation. You can use the "error" property in your command to execute that code if console error/ interpreter error comes up. Using $error returns the console error the interpreter threw… you can use it inside $channelSendMessage as example
> > 
> > This works! Thanks!!
> 
> if you checked #sneakpeak  u can see a clip on the callback bot.onFunctionError()
> 

Oky ♥️
