### ISSUE TITLE
Spotify bug

### ISSUE THREAD

**Issue by Priyanshu360-cpu** [aoijs/aoi.js#116]
Aoi version 1.0.6
$songInfo[duration_left] doesn't works if we play a song through Spotify that means through $playSpotify please fix the bug

**Comment by Mr-Catty** [comment]
Not sure whether it has a bug or not. __If anyone has the same issue ping in the Support channel and share the **screenshot**__. I will try to resolve

**Comment by Leref** [comment]
Nothing was discussed nor fully described.
If this continues create a new Pull Request.
