### ISSUE TITLE
$getLeaderboardValue

### ISSUE THREAD

**Issue by Cursed95** [aoijs/aoi.js#120]
## Type
- [ ] Functions: \<$getLeaderboardValue>

## Description
gets varible values by leaderboard position
Usage:
$getLeaderboardValue[variable name;variable type (user/globalUser/server);asc/desc;position;{servername} - {value} - {server id}]

**Comment by DiscordBond** [comment]
$getLeaderboardInfo exists

**Comment by Cursed95** [comment]
it is not same thing

**Comment by USERSATOSHI** [comment]
> 
> 
> ## Type
> - [ ] Functions: \<$getLeaderboardValue>
> 
> 
> ## Description
> gets varible values by leaderboard position
> Usage:
> $getLeaderboardValue[variable name;variable type (user/globalUser/server);asc/desc;position;{servername} - {value} - {server id}]

is that server leaderboard ?

**Comment by Cursed95** [comment]
example:
i have "money" varible its value "10" for user1 
and its value "5" for user2 
when i use this command
$getLeaderboardValue[money;user;asc;1;{servername} - {value} - {server id}]
i will get this message :
username - 10 - userID
// example: it will takes richest persons information

**Comment by USERSATOSHI** [comment]
> example:
> i have "money" varible its value "10" for user1 
> and its value "5" for user2 
> when i use this command
> $getLeaderboardValue[money;user;asc;1;{servername} - {value} - {server id}]
> i will get this message :
> username - 10 - userID
> // example: it will takes richest persons information

u can do that bye $userLeaderboard[money;asc;{username}-{value}-{id};1;1]
this will return the top user 

and for other u can use textsplit
```js
$splitText[position here]
$textSplit[$userLeaderboard[money;asc;{username}-{value}-{id};20;1];\n]
```
