### ISSUE TITLE
New Callback Function

### ISSUE THREAD

**Issue by RedentSama** [aoijs/aoi.js#122]
## Type
- [x] Functions: $messageDeleter[name/id/tag/mention] for bot.onMessageDelete()
- [ ] Callbacks: \
- [ ] Handlers: \
- [ ] Others: \

## Description
will indicate the person who deleted the message

**Comment by falsisdev** [comment]
> ## Type
> - [x] Functions: $messageDeleter[name/id/tag/mention] for bot.onMessageDelete()
> - [ ] Callbacks: \
> - [ ] Handlers: \
> - [ ] Others: \
> 
> ## Description
> will indicate the person who deleted the message

$username is already exists

**Comment by RedentChan** [comment]
> > ## Type
> > - [x] Functions: $messageDeleter[name/id/tag/mention] for bot.onMessageDelete()
> > - [ ] Callbacks: \
> > - [ ] Handlers: \
> > - [ ] Others: \
> > 
> > ## Description
> > will indicate the person who deleted the message
> 
> $username is already exists 

i say a function that shows which official deleted the message

**Comment by falsisdev** [comment]
> > > ## Type
> > > - [x] Functions: $messageDeleter[name/id/tag/mention] for bot.onMessageDelete()
> > > - [ ] Callbacks: \
> > > - [ ] Handlers: \
> > > - [ ] Others: \
> > > 
> > > ## Description
> > > will indicate the person who deleted the message
> > 
> > $username is already exists 
> 
> i say a function that shows which official deleted the message

This is not possible

**Comment by DiscordBond** [comment]
That message delete event doesn’t provide data about the user that deleted the message. You need to check that via audit logs
