### ISSUE TITLE
$channelType types

### ISSUE THREAD

**Issue by falsisdev** [aoijs/aoi.js#123]
## Type
- Functions: $channelType
### $channelType new type
[Types:
text => normal text channel
voice => voice channel
category => category
news => announcement channel
dm => dm's](https://aoi.leref.ga/functions/usdchanneltype)

Example:
```$onlyIf[$channelType==dm;:x: This command only For DM's!]```
![Ekran görüntüsü 2021-05-18 105338](https://user-images.githubusercontent.com/63756985/118613334-52c5c600-b7c7-11eb-9238-121f77a2cb76.jpg)

**Comment by USERSATOSHI** [comment]
@falsisdev uh ejats6tge issue?

**Comment by falsisdev** [comment]
> @falsisdev uh what's the issue?

$channelType => dm

**Comment by USERSATOSHI** [comment]
> > @falsisdev uh what's the issue?
> 
> $channelType => dm

ping der Bond about this
 for docs issues, ping der Bond in #general 
no need to make an issue here

**Comment by falsisdev** [comment]
> > > @falsisdev uh what's the issue?
> > 
> > 
> > $channelType => dm
> 
> ping der Bond about this
> for docs issues, ping der Bond in #general
> no need to make an issue here

Hmm, I didn't say that to change the docs. There is no such function. Not working. I was just giving suggestions for inclusion.

**Comment by USERSATOSHI** [comment]
> > > > @falsisdev uh what's the issue?
> > > 
> > > 
> > > $channelType => dm
> > 
> > ping der Bond about this
> > for docs issues, ping der Bond in #general
> > no need to make an issue here
> 
> Hmm, I didn't say that to change the docs. There is no such function. Not working. I was just giving suggestions for inclusion.

![Screenshot_2021-05-18-13-44-59-18_572064f74bd5f9fa804b05334aa4f912.png](https://user-images.githubusercontent.com/73595362/118616447-5402ed00-b7df-11eb-8777-00aa6bd083ad.png)

dm type exists

**Comment by falsisdev** [comment]
> > > > > @falsisdev uh what's the issue?
> > > > 
> > > > 
> > > > $channelType => dm
> > > 
> > > 
> > > ping der Bond about this
> > > for docs issues, ping der Bond in #general
> > > no need to make an issue here
> > 
> > 
> > Hmm, I didn't say that to change the docs. There is no such function. Not working. I was just giving suggestions for inclusion.
> 
> ![Screenshot_2021-05-18-13-44-59-18_572064f74bd5f9fa804b05334aa4f912.png](https://user-images.githubusercontent.com/73595362/118616447-5402ed00-b7df-11eb-8777-00aa6bd083ad.png)
> 
> dm type exists and so Does the function

HmM, I tried dm log but it didn't work. I will try again
