### ISSUE TITLE
new function

### ISSUE THREAD

**Issue by RedentSama** [aoijs/aoi.js#124]
## Type
- [x] Functions: \$forEachRole
- [ ] Callbacks: \
- [ ] Handlers: \
- [ ] Others: \

## Description
This function creates a loop over all roles the bot has access to

**Comment by falsisdev** [comment]
> ## Type
> - [x] Functions: \$forEachRole
> - [ ] Callbacks: \
> - [ ] Handlers: \
> - [ ] Others: \
> 
> ## Description
> This function creates a loop over all roles the bot has access to

I agree. Maybe $forEachGuildRoles :)

**Comment by DiscordBond** [comment]
> ## Type
> * [x]  Functions: $forEachRole
> * [ ]  Callbacks: \
> * [ ]  Handlers: \
> * [ ]  Others: \
> 
> ## Description
> This function creates a loop over all roles the bot has access to

roles are cached in guilds, not global.
