### ISSUE TITLE
$httpRequest more Methods[POST,PATCH,DELETE,PUT]

### ISSUE THREAD

**Issue by Cursed95** [aoijs/aoi.js#128]
## Type
- [ ] Functions: \<$httpRequest>

## Description
Can you add more methods to $httpRequest like post,patch,delete,put

**Comment by falsisdev** [comment]
> 
> 
> ## Type
> - [ ] Functions: \<$httpRequest>
> 
> 
> ## Description
> Can you add more methods to $httpRequest like post,patch,delete,put

$jsonRequest and $httpRequest is already exists

**Comment by Cursed95** [comment]
it is not they only supports get

**Comment by falsisdev** [comment]
I thought GET and POST were enough for an api. This is the first time I've heard about other methods.

**Comment by Cursed95** [comment]
> I thought GET and POST were enough for an api. This is the first time I've heard about other methods.

it is not and post doesnt work with $httpRequest

**Comment by falsisdev** [comment]
> > I thought GET and POST were enough for an api. This is the first time I've heard about other methods.
> 
> it is not and post doesnt work with $httpRequest

Post is already exists 🤦

**Comment by Cursed95** [comment]
> > > I thought GET and POST were enough for an api. This is the first time I've heard about other methods.
> > 
> > 
> > it is not and post doesnt work with $httpRequest
> 
> Post is already exists 🤦

it is not working lol

**Comment by falsisdev** [comment]
> > > > I thought GET and POST were enough for an api. This is the first time I've heard about other methods.
> > > 
> > > 
> > > it is not and post doesnt work with $httpRequest
> > 
> > Post is already exists 🤦
> 
> it is not working lol

LoL apparently you tried it on a bad api that is not working. Previously tested and used. I havent tried it, but it may work with the methods you advised. This already exists and works,
please do not give unnecessary suggestions.

**Comment by Cursed95** [comment]
> > > > > I thought GET and POST were enough for an api. This is the first time I've heard about other methods.
> > > > 
> > > > 
> > > > it is not and post doesnt work with $httpRequest
> > > 
> > > 
> > > Post is already exists 🤦
> > 
> > 
> > it is not working lol
> 
> LoL apparently you tried it on a bad api that is not working. Previously tested and used. I havent tried it, but it may work with the methods you advised. This already exists and works,
> please do not give unnecessary suggestions.

it is not unnecessary suggestion and i tried discord webhook api how it could be bad api :D i tested it again only GET working

**Comment by falsisdev** [comment]
> > > > > > I thought GET and POST were enough for an api. This is the first time I've heard about other methods.
> > > > > 
> > > > > 
> > > > > it is not and post doesnt work with $httpRequest
> > > > 
> > > > 
> > > > Post is already exists 🤦
> > > 
> > > 
> > > it is not working lol
> > 
> > LoL apparently you tried it on a bad api that is not working. Previously tested and used. I havent tried it, but it may work with the methods you advised. This already exists and works,
> > please do not give unnecessary suggestions.
> 
> it is not unnecessary suggestion and i tried discord webhook api how it could be bad api :D i tested it again only GET working

Please think about it. Why would it be $httpRequest if only GET worked? Already have  $jsonRequest ??

**Comment by Cursed95** [comment]
> > > > > > > I thought GET and POST were enough for an api. This is the first time I've heard about other methods.
> > > > > > 
> > > > > > 
> > > > > > it is not and post doesnt work with $httpRequest
> > > > > 
> > > > > 
> > > > > Post is already exists 🤦
> > > > 
> > > > 
> > > > it is not working lol
> > > 
> > > 
> > > LoL apparently you tried it on a bad api that is not working. Previously tested and used. I havent tried it, but it may work with the methods you advised. This already exists and works,
> > > please do not give unnecessary suggestions.
> > 
> > 
> > it is not unnecessary suggestion and i tried discord webhook api how it could be bad api :D i tested it again only GET working
> 
> Please think about it. Why would it be $httpRequest if only GET worked? Already have $jsonRequest ??

Because we need more methods and i think they will add it

**Comment by Mr-Catty** [comment]
This conversation is going long and lengthy like a chat. There are enough methods available in our package. `**End of discussion**` will be good.

**Comment by Cursed95** [comment]
> This conversation is going long and lengthy like a chat. There are enough methods available in our package. `**End of discussion**` will be good.

only GET ?

**Comment by falsisdev** [comment]
I agree @Mr-Catty Thank you. <3

**Comment by KASKUSTTV** [comment]
Any examples on how to use POST with body?

**Comment by XzFirzal** [comment]
$httpRequest support all http methods, and the api must support it too

**Comment by XzFirzal** [comment]
[Please see this conversation for POST request issue](https://github.com/aoijs/aoi.js/issues/24)
