### ISSUE TITLE
$isEmoji bug

### ISSUE THREAD

**Issue by Hataken999** [aoijs/aoi.js#129]
## Type
- [ ] Functions: \$isEmoji

Code used:
```
$isEmoji[$message[1]]
```
It return error on console

More:
- Aoi.js version: 1.0.6

Screenshots (If any): https://cdn.discordapp.com/attachments/742273318195036220/844310436651991060/Screenshot_20210519-0311422.png

**Comment by USERSATOSHI** [comment]
> 
> 
> ## Type
> - [ ] Functions: \$isEmoji
> 
> Code used:
> ```
> $isEmoji[$message[1]]
> ```
> It return error on console
> 
> More:
> - Aoi.js version: 1.0.6
> 
> Screenshots (If any): https://cdn.discordapp.com/attachments/742273318195036220/844310436651991060/Screenshot_20210519-0311422.png

yes it's fixed for next update

**Comment by falsisdev** [comment]
Hey @USERSATOSHI, There are too many bugs like this, please fix it in the next update. 💁

**Comment by Hataken999** [comment]
> > 
> > 
> > ## Type
> > - [ ] Functions: \$isEmoji
> > 
> > Code used:
> > ```
> > $isEmoji[$message[1]]
> > ```
> > It return error on console
> > 
> > More:
> > - Aoi.js version: 1.0.6
> > 
> > Screenshots (If any): https://cdn.discordapp.com/attachments/742273318195036220/844310436651991060/Screenshot_20210519-0311422.png
> 
> yes it's fixed for next update

Okay thank you

**Comment by USERSATOSHI** [comment]
> Hey @USERSATOSHI, There are too many bugs like this, please fix it in the next update. 💁

@falsisdev already done

this was fixed by kubaturi
and some other fixes are also done

**Comment by falsisdev** [comment]
>> @falsisdev already done
> 
>> this was fixed by kubaturi
>> and some other fixes are also done 

Oky thx >:)

**Comment by USERSATOSHI** [comment]
> >> @falsisdev already done
> > 
> >> this was fixed by kubaturi
> >> and some other fixes are also done 
> 
> Oky thx >:)

can You close this issue

**Comment by falsisdev** [comment]
> > >> @falsisdev already done
> > > 
> > >> this was fixed by kubaturi
> > >> and some other fixes are also done 
> > 
> > Oky thx >:)
> 
> can You close this issue 

I am not the owner of the Issue: /

**Comment by USERSATOSHI** [comment]
yeah I saw later.
my mistake

**Comment by Hataken999** [comment]
@USERSATOSHI this function still bug i think.. bcos after update it run but the func not working as the purpose..

Example:
```
$isEmoji[<:justread:778366051917234206>]
```

_**Always return false**_
![Screenshot_20210529-050521~2.png](https://user-images.githubusercontent.com/75216370/120046443-5b769180-c03c-11eb-879e-2756dbad66f7.png)
