### ISSUE TITLE
New function: $suppressConsoleErrors

### ISSUE THREAD

**Issue by Huguitis** [aoijs/aoi.js#131]
## Type
- [x] Functions: \$suppressConsoleErrors

## Description
This function would do is eliminate any type of error message that starts displaying in the console. Like $suppressErrors but instead of in discord, from the project.

**Comment by falsisdev** [comment]
I guess you can solve it like this;
```js
$let[falsis;$error] //I don't think it will throw the error if you don't put $get[falsis].
```
I haven't tried this but I guess it will work.

**Comment by Huguitis** [comment]
Oh I'll try thanks

**Comment by USERSATOSHI** [comment]
closed due to inactivity
