### ISSUE TITLE
Status bug

### ISSUE THREAD

**Issue by TrxppyVX** [aoijs/aoi.js#132]
Started my server and my bot went online as planned but then it went offline after 2 minutes or 3 minutes. It took me days to figure out what was wrong but then i did. It was the status (the server kept on running even though the bot was offline). I took out the status feature and when i did, the bot didn't go offline. I put it back and it went offline again. I did the same thing over and over again a couple times to make sure that it wasn't something else.

**Comment by USERSATOSHI** [comment]
> Started my server and my bot went online as planned but then it went offline after 2 minutes or 3 minutes. It took me days to figure out what was wrong but then i did. It was the status (the server kept on running even though the bot was offline). I took out the status feature and when i did, the bot didn't go offline. I put it back and it went offline again. I did the same thing over and over again a couple times to make sure that it wasn't something else. 
> 

probably ur project memory got out of heap memory

**Comment by Mr-Catty** [comment]
> Started my server and my bot went online as planned but then it went offline after 2 minutes or 3 minutes. It took me days to figure out what was wrong but then i did. It was the status (the server kept on running even though the bot was offline). I took out the status feature and when i did, the bot didn't go offline. I put it back and it went offline again. I did the same thing over and over again a couple times to make sure that it wasn't something else.

Hello @TrxppyVX . It is normal and happening for many users [Inclusing me]. It's a kinda bug in discord.js. And I think you got an error like `Javascript heap out of memory`. [Click here](https://github.com/discordjs/discord.js/issues/4904) to view one of the problems in Github. Try to change your node version to **12.19.0**.  This may work!

**Comment by Mr-Catty** [comment]
Hello @TrxppyVX  . It is normal and happening for many users [Inclusing me]. It's a kinda bug in discord.js. And I think you got an error like `Javascript heap out of memory`. [Click here](https://github.com/discordjs/discord.js/issues/4904) to view one of the problems in Github. Try to change your node version to **12.19.0**.  This may work!

**Comment by TrxppyVX** [comment]
> > Started my server and my bot went online as planned but then it went offline after 2 minutes or 3 minutes. It took me days to figure out what was wrong but then i did. It was the status (the server kept on running even though the bot was offline). I took out the status feature and when i did, the bot didn't go offline. I put it back and it went offline again. I did the same thing over and over again a couple times to make sure that it wasn't something else.
> 
> probably ur project memory got out of heap memory

nope

**Comment by TrxppyVX** [comment]
> Hello @TrxppyVX . It is normal and happening for many users [Including me]. It's a kinda bug in discord.js. And I think you got an error like `Javascript heap out of memory`. [Click here](https://github.com/discordjs/discord.js/issues/4904) to view one of the problems in Github. Try to change your node version to **12.19.0**. This may work!

where would i change that?

**Comment by Mr-Catty** [comment]
Which host you are using right now? What are the specs(RAM and Storage) given by the host provider? Ping me in #support-1 for more
