### ISSUE TITLE
$ignoreChannels

### ISSUE THREAD

**Issue by Gamerlagan-lag** [aoijs/aoi.js#135]
## Type
- [ ] Functions: $ignoreChannels[channelD]

## Description
ignores the channel inside of the [].

**Comment by USERSATOSHI** [comment]
> 
> 
> ## Type
> - [ ] Functions: $ignoreChannels[channelD]
> 
> ## Description
> ignores the channel inside of the [].
@Gamerlagan-lag 
```
$onlyIf[$checkContains[&$channelID&;&channelID1&;&channelID2&;...]==false;This channel has been blacklisted]
```
You can use this
