### ISSUE TITLE
$removeAllEmbeds

### ISSUE THREAD

**Issue by falsisdev** [aoijs/aoi.js#136]
- [x] Functions: $removeAllEmbeds[channelID;messageID]

## Description
[If this is possible (I don't know) $removeAllEmbeds. May come.](https://stackoverflow.com/questions/63012322/how-to-remove-the-embed-from-specific-messages-and-from-messages-coming-from-spe)
## Usage
```js
$removeAllEmbeds[channelID;messageID]
```
## Error Messages
```js
❌ Invalid Channel ID in $removeAllEmbeds[aa;844727981662535681] at line 1
❌ Invalid Message ID in $removeAllEmbeds[844727981662535681;aa] at line 1
❌ Invalid Usage In $removeAllEmbeds[ at line 1
```

I guess its not possible but maybeee >:)
[Click Pls](https://stackoverflow.com/questions/63012322/how-to-remove-the-embed-from-specific-messages-and-from-messages-coming-from-spe) >:))

![ScreenShot](https://user-images.githubusercontent.com/63756985/119165408-1fed2d80-ba66-11eb-9af0-ff0673a679ad.png)

**Comment by USERSATOSHI** [comment]
hmm I guess it's possible
well sure I will take a look on this

**Comment by falsisdev** [comment]
> hmm I guess it's possible
> well sure I will take a look on this

Thanks 🐢

**Comment by WinBOT31sj** [comment]
nice good ingilizcem bu kadar yetti sad :(

**Comment by falsisdev** [comment]
> nice good ingilizcem bu kadar yetti sad :(

Speak english 😔✌️



Anlıyorum sus.

**Comment by WinBOT31sj** [comment]
> > nice good ingilizcem bu kadar yetti sad :(
> 
> Speak english 
> 
> Anlıyorum sus.

 TM AB

**Comment by WinBOT31sj** [comment]
pls add **leref**

**Comment by USERSATOSHI** [comment]
leref is retired

she doesn't contribute anymore

**Comment by falsisdev** [comment]
> leref is retired
> 
> she doesn't contribute anymore

She?? Is Leref girl omg 🤭

**Comment by WinBOT31sj** [comment]
> leref is retired
> 
> she doesn't contribute anymore

Why :&

**Comment by Mr-Catty** [comment]
Don't chat here. Use discord for more

**Comment by WinBOT31sj** [comment]
> Don't chat here. Use discord for more

ah okey

**Comment by falsisdev** [comment]
mm will this function be introduced? should i close the issue?

**Comment by falsisdev** [comment]
I hope it will be added 😄
