### ISSUE TITLE
$cut[command;num]

### ISSUE THREAD

**Issue by falsisdev** [aoijs/aoi.js#137]
- [x] Functions: $cut[command;num]
## Description
For commands that are too long, when I type $cut[command;2], it will show the 2nd of the row. For example;
$cut[$serverEmojis;1]
$cut[$serverEmojis;2]

**it will divide the command into 2 groups.**

## EXAMPLE ;
Input:
```js
$description[$cut[$serverEmojis;2]
$cut[$serverEmojs;1]]
```

Output:
![Example](https://media.discordapp.net/attachments/837999297341292634/845335605621293116/unknown.png?width=344&height=99)

## Usage
```js
$cut[command;number]
```

### End
I hope I could explain | **In short, it will divide the command into 2 groups.**

**Comment by falsisdev** [comment]
# Pictured is a bot verified discord.js bot

**Comment by USERSATOSHI** [comment]
> # Pictured is a bot verified discord.js bot

so basically sends 2 different embeds ?

**Comment by falsisdev** [comment]
> > # Pictured is a bot verified discord.js bot
> 
> so basically sends 2 different embeds ?
> @falsisdev 

Yes, because it cant send too many emojis. Sending 2 messages.

**Comment by USERSATOSHI** [comment]
well I can try making split messages in sendMessage 
but  split embed will be a custom 
u can use a bit djseval but u can make that pretty much easily

**Comment by falsisdev** [comment]
Got it, even if there are split messages :) I searched for a djs code but couldn't find any code that can work with $djsEval. Still thank you very much.

**Comment by falsisdev** [comment]
May I ask if the function will come before closing the issue?

**Comment by falsisdev** [comment]
> well I can try making split messages in sendMessage
> but split embed won't be made.
> 
> u can use a bit djseval but u can make that pretty much easily

👍
