### ISSUE TITLE
$search[command_name;seperator(Optional)] and $searchCount

### ISSUE THREAD

**Issue by falsisdev** [aoijs/aoi.js#139]
## Type
- [x] Functions: $search[command_name;seperator(optional)], $searchCount

# $search

## Description
Searches for the letter or word typed instead of command_name in the names of commands. And it returns what it finds.
## Example
```js
$description[I could not find a command called he. You may be interested in the following;
help, hello]
```
## DJS Code
```js
client.bot_commands.filter(x => x.name.includes("command_name")).map(x => x.name).join(", ")
```

# $searchCount

## Description
Shows the number of commands searched.

## DJS Code
```hs
client.bot_commands.filter(x => x.name.includes("command_name")).map(x => x.name).length
```
## WITH $djsEval

![wow](https://cdn.discordapp.com/attachments/593911411533414432/845570905656131604/20210522_105626.jpg)

Thx

**Comment by DiscordBond** [comment]
Okay, lemme test

**Comment by falsisdev** [comment]
> Okay, lemme test

Thx ♥️

**Comment by falsisdev** [comment]
Channel searches similar to this can also come.
```js
message.guild.channels.cache.filter(x => x.name.includes("channel_name")).map(x => x).join(", ")
```
I use them in my bot with $djsEval, but if it comes as aoijs function everyone can use it more easily.
@DiscordBond ✌️

**Comment by falsisdev** [comment]
oh, der bond :/
