### ISSUE TITLE
$searchChannel and $searchChannelsCount

### ISSUE THREAD

**Issue by falsisdev** [aoijs/aoi.js#141]
## $searchChannel[channel_name;seperator(optional)]

```js
message.guild.channels.cache.filter(x => x.name.includes("channel_name")).map(x => x).join(", ")
```
## $searchChannelsCount
```js
message.guild.channels.cache.filter(x => x.name.includes("channel_name")).map(x => x).lenght
```

**As I said on Issue 139. Use as a channel.**

**Comment by falsisdev** [comment]
[Referenced](https://github.com/aoijs/aoi.js/issues/139#issuecomment-846372366)

**Comment by DiscordBond** [comment]
> ## $searchChannel[channel_name;seperator(optional)]
> ```js
> message.guild.channels.cache.filter(x => x.name.includes("channel_name")).map(x => x).join(", ")
> ```
> 
> ## $searchChannelCount
> ```js
> message.guild.channels.cache.filter(x => x.name.includes("channel_name")).map(x => x).lenght
> ```
> 
> **As I said on Issue 139. Use as a channel.**

no need to open a new issue

**Comment by falsisdev** [comment]
> > ## $searchChannel[channel_name;seperator(optional)]
> > ```js
> > message.guild.channels.cache.filter(x => x.name.includes("channel_name")).map(x => x).join(", ")
> > ```
> > 
> > ## $searchChannelCount
> > ```js
> > message.guild.channels.cache.filter(x => x.name.includes("channel_name")).map(x => x).lenght
> > ```
> > 
> > **As I said on Issue 139. Use as a channel.**
> 
> no need to open a new issue

Oh k do I close?
