### ISSUE TITLE
Add $jsonRequest[URL;property;get/set]

### ISSUE THREAD

**Issue by CUBE2593k** [aoijs/aoi.js#146]
This will do so that example if there is a hosting it can be
!addresources <User> <Resources> it is an example so I would appreciate if you could add that

**Comment by falsisdev** [comment]
> This will do so that example if there is a hosting it can be
> !addresources <User> <Resources> it is an example so I would appreciate if you could add that 

$jsonRequest already exists

I understand what you mean. Use [$httpRequest](https://aoi.leref.ga/function/usdhttprequest).

**Comment by USERSATOSHI** [comment]
closed due to inactivity
