### ISSUE TITLE
$isValidImageLink field bug

### ISSUE THREAD

**Issue by Hataken999** [aoijs/aoi.js#148]
## Type
- [ ] Functions: \$isValidImageLink

# Description
When i testing that func with only image link it works fine, but when i put $message func inside $isValidImageLink it doesn't work like in the docs, it always return false (i make this report just in case no one know or report about this).

First test:
```
$title[**IMAGE VALID**]
$image[https://wallpaperaccess.com/full/2351985.jpg]
$onlyIf[$isValidImageLink[https://wallpaperaccess.com/full/2351985.jpg]==true;{title:ERROR}{description:\:x\: Image link not valid & remember link should end with (.png/.jpg) format.}{color:RED}{delete:10s}]
```
First result:
![Screenshot_20210523-075526~2.png](https://user-images.githubusercontent.com/75216370/119244711-65f8dd00-bb9d-11eb-9afa-74e8093183ff.png)

Second test:
```
$title[**IMAGE VALID**]
$image[$message[1]]
$onlyIf[$isValidImageLink[$message[1]]==true;{title:ERROR}{description:\:x\: Image link not valid & remember link should end with (.png/.jpg) format.}{color:RED}{delete:10s}]
```
Second result:
![Screenshot_20210523-075550~2.png](https://user-images.githubusercontent.com/75216370/119244776-18c93b00-bb9e-11eb-9032-504346be6028.png)

More:
- Aoi.js version: 1.0.6

**Comment by falsisdev** [comment]
I think this works. If you actually entered a valid image link in the image 2, the image would appear.

**Comment by Hataken999** [comment]
> I think this works. If you actually entered a valid image link in the image 2, the image would appear.

The link valid, it just loading the img (lag a bit)

**Comment by falsisdev** [comment]
> > I think this works. If you actually entered a valid image link in the image 2, the image would appear.
> 
> The link valid, it just loading the img (lag a bit)

Hmm, there might be a problem with that picture.
![IMG_20210523_042227.jpg](https://user-images.githubusercontent.com/63756985/119245005-7fd6f780-bb7e-11eb-8ec5-3a156029a3aa.jpg)

**Comment by Hataken999** [comment]
> > > I think this works. If you actually entered a valid image link in the image 2, the image would appear.
> > 
> > The link valid, it just loading the img (lag a bit)
> 
> Hmm, there might be a problem with that picture.
> ![IMG_20210523_042227.jpg](https://user-images.githubusercontent.com/63756985/119245005-7fd6f780-bb7e-11eb-8ec5-3a156029a3aa.jpg)

U understand what i report above?? I say it works fine if just an image link, what i report is it wont work when u put $message function in $isValidImageLink like in the [docs](https://aoi.leref.ga/functions/usdisvalidimagelink)

For example:
```
$isValidImageLink[$message]
```

It will return false bcos $message func not executed on $isValidImageLink field

**Comment by falsisdev** [comment]
Yes I know. $message does not work, but $noMentionMessage does.

**Comment by Hataken999** [comment]
> Yes I know. $message does not work, but $noMentionMessage does.

Really? So i hope next updt $message can be put on $isValidImageLink, cus $noMentionMessage to long

**Comment by falsisdev** [comment]
> > Yes I know. $message does not work, but $noMentionMessage does.
> 
> Really? So i hope next updt $message can be put on $isValidImageLink, cus $noMentionMessage to long.
> 
> Btw thx info

Yes I agree. Mods look after ... 

Np

**Comment by Leref** [comment]
$isValidLink and $isValidImageLink are two different functions.
$isValidImageLink is recognized by the format of the Image link (png, webp, etc)
