### ISSUE TITLE
pruneMusic bug

### ISSUE THREAD

**Issue by LueyCoder** [aoijs/aoi.js#151]
## Type
- [X] Functions: \$pruneMusic (Whenever I use it returns the error of the print)
- [ ] Callbacks: \<Callback Name>
- [ ] Handlers: \<Handler Type>
- [ ] Others: \______

Code used:
```
$playSong[$message]
$pruneMusic
```

More:
- Aoi.js version: 1.0.6
- Node.js version: v12.16.1

Screenshots (If any): https://cdn.discordapp.com/attachments/835715920504029217/846047799589208075/Screenshot_20210523-1231102.jpg

**Comment by USERSATOSHI** [comment]
> 
> 
> ## Type
> - [X] Functions: \$pruneMusic (Whenever I use it returns the error of the print)
> - [ ] Callbacks: \<Callback Name>
> - [ ] Handlers: \<Handler Type>
> - [ ] Others: \______
> 
> Code used:
> ```
> $playSong[$message]
> $pruneMusic
> ```
> 
> More:
> - Aoi.js version: 1.0.6
> - Node.js version: v12.16.1
> 
> Screenshots (If any): https://cdn.discordapp.com/attachments/835715920504029217/846047799589208075/Screenshot_20210523-1231102.jpg

@LueyCoder 
make it
$pruneMusic
$playSong[$message]

**Comment by LueyCoder** [comment]
ok, wait

**Comment by Leref** [comment]
No response.
