### ISSUE TITLE
$setGuildIcon bug

### ISSUE THREAD

**Issue by falsisdev** [aoijs/aoi.js#152]
## Type
- [x] Functions: $setGuildIcon

Code used:
```
$setGuildIcon[$userAvatar[$clientId]]
```

More:
- Aoi.js version: 1.0.6
- Node.js version: Latest Version

![Kremlin](https://user-images.githubusercontent.com/63756985/119270235-5cef2680-bc04-11eb-9ab8-0ad5a01fb046.jpg)

**Comment by DiscordBond** [comment]
This issue is caused by discord.js, not by us. currently guild icon can't be edited. @falsisdev

**Comment by falsisdev** [comment]
> This issue is caused by discord.js, not by us. currently guild icon can't be edited. @falsisdev 

Hmm I understand. I hope the discord.js fix it as soon as possible. Thanks. I close Issue
