### ISSUE TITLE
$clearReaction it's not working well

### ISSUE THREAD

**Issue by CUBE2593k** [aoijs/aoi.js#153]
In the reactionAddCommand the $clearReaction is not working for me I do not know what is due

**Comment by BeastBoyADI** [comment]
Its actually working for me perfectly

**Comment by BeastBoyADI** [comment]
Yeah don't know why the bot is even counting itself so i used $onlyIf[$authorID!=$clientID;] which stopped the bot clearing its own reaction.

**Comment by Leref** [comment]
It's pretty self-explanatory as the author ID must be the same as the Client, which is not.

**Comment by CUBE2593k** [comment]
Well, Ami does not serve me the $clearReaction in a reactionAddCommand
