### ISSUE TITLE
$ticketCount

### ISSUE THREAD

**Issue by falsisdev** [aoijs/aoi.js#155]
# $ticketCount Function
## Description
It shows the total number of opened tickets on the server. We can use this in channel names. We can make the channel name ticket-3 for the 3rd ticket, the channel name for the next ticket, ticket-4
```js
$ticketCount //returns 117/32/31/4/1/6/8(...)
```
Using $random is not good at all :/
## Example
```js
$newTicket[ticket-$ticketCount;blabla;blabla;no;blabla]
```

**Comment by falsisdev** [comment]
**Like this...**
![Ekran görüntüsü 2021-05-25 093735](https://user-images.githubusercontent.com/63756985/119450622-b69a4280-bd23-11eb-8718-637d9024dd80.jpg)

**Comment by BeastBoyADI** [comment]
Hmm actually i use variables for this
