### ISSUE TITLE
Fix $deleteSlashCommand returning "cannot get guild slash commands"

### ISSUE THREAD

**Issue by ExtremeStylez** [aoijs/aoi.js#157]
## Type
- [ ] Functions: \$deleteSlashCommand

Code used:
```
$deleteSlashCommand[846066028949798954;$guildID]
```

More:
- Aoi.js version: 1.0.6
- Node.js version: Latest
- Operating system: Repl.it Mobile

Screenshots (If any): 
![Screenshot_20210526-013322](https://user-images.githubusercontent.com/46006826/119582467-d897d180-bdc4-11eb-8ab4-5909f4d56f33.jpg)

**Comment by USERSATOSHI** [comment]
> 
> 
> ## Type
> - [ ] Functions: \$deleteSlashCommand
> 
> Code used:
> ```
> $deleteSlashCommand[846066028949798954;$guildID]
> ```
> 
> More:
> - Aoi.js version: 1.0.6
> - Node.js version: Latest
> - Operating system: Repl.it Mobile
> 
> Screenshots (If any): 
> ![Screenshot_20210526-013322](https://user-images.githubusercontent.com/46006826/119582467-d897d180-bdc4-11eb-8ab4-5909f4d56f33.jpg)

@ExtremeStylez wrong usage
correct usage is this

![Screenshot_2021-05-26-10-33-34-96.png](https://user-images.githubusercontent.com/73595362/119605178-f178a500-be0d-11eb-8a4a-8a214858bc02.png)
