### ISSUE TITLE
CMD HANDLER WITH HOSTING NOT WORKING.

### ISSUE THREAD

**Issue by aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa77** [aoijs/aoi.js#158]
so basically when I made a discord bot using aoi.js WITH the command handler in the docs. I tried hosting on repl.it 24/7 HACKER plan, it turns on for some time then it turns off after 1 minute.. this happened even when I tried with repl.it + uptime robot same result, even when I tried using a Paid VPS same result.. now I'm pretty sure this is the cause of the command handler as I host my other bot in the repl.it 24/7 hacker plan the same code WITHOUT command handler. IT. WORKED. please fix 🙏
More:
- Aoi.js version: ^1.0.6
- Node.js version: v12
- Operating system: Linux

**Comment by falsisdev** [comment]
i don't think this has anything to do with aoijs?
