### ISSUE TITLE
Bug in reactionAddCommand. Don't know but the problem is the reactionAddCommand command has stopped working after this new update and due to this the bot is automatically restarting again and again. Like it happened 20 times till now. Please fix the bug in reactionAddCommand as i checked there is no host issue and everything was working perfectly before update!! Please i request to check and fix it.

### ISSUE THREAD

**Issue by BeastBoyADI** [aoijs/aoi.js#162]
## Type
- [ ] Functions: \<Function Name>
- [x] Callbacks: \reactionAddCommand
- [ ] Handlers: \<Handler Type>
- [ ] Others: \______

Code used:
```
Your Code Here
```

More:
- Aoi.js version:3.0.0
- Node.js version:14.17.0
- Operating system:linux

Screenshots (If any): Image or Link

**Comment by BeastBoyADI** [comment]
Also i just tried removing bot.onReactionAdd() , bot.onReactionRemove() and reactionAddCommand and the bot has now stop re-starting. So the main error is in these. Please fix it as i was using it for tickets and now it can't work.😭😢

**Comment by USERSATOSHI** [comment]
@BeastBoyADI for now remove ur reactionAddCommand code

we wilk check what exactly got bugged
