### ISSUE TITLE
Pls add buttons https://support.discord.com/hc/en-us/articles/1500012250861-Bots-Buttons

### ISSUE THREAD

**Issue by DavidXP1225** [aoijs/aoi.js#165]
## Type
- [x] Functions: \<Function Name>
- [ ] Callbacks: \<Callback Name>
- [ ] Handlers: \<Handler Type>
- [ ] Others: \______

## Description
Explain how it works

**Comment by KASKUSTTV** [comment]
Yeah pls add it it will be very usefull :3

**Comment by unknown-software** [comment]
There coming just wait

**Comment by abdullah09637** [comment]
Yes just wait
