### ISSUE TITLE
add $deleteChannelsByName[name1;name2;etc...] pls

### ISSUE THREAD

**Issue by Huguitis** [aoijs/aoi.js#166]
## Type
- [x] Functions: \$deleteChannelsByName
- [ ] Callbacks: 
- [ ] Handlers: 
- [ ] Others: 

## Description
$deleteChannelsByName[name1;name2;name3] - Like bdfd, it will remove ALL channels with the same name, this can be used to unraid a server in which many channels have been created as: #server-raided-lol for example.

I know there is $deleteChannels, but it would only delete one channel called #server-raided-lol and not all, right?

**Comment by RedentSama** [comment]
$deleteChannels[$channelID[channel name];$channelID[channel name]]

**Comment by falsisdev** [comment]
It's ridiculous to turn something that is already possible into a separate function, as in BDFD
$deleteChannels[$channelID[channel name];$channelID[channel name]] already exists
