### ISSUE TITLE
$vcSize bug

### ISSUE THREAD

**Issue by bitshelf5562645** [aoijs/aoi.js#167]
## Type
- [ ] Functions: \<$vcSize>
- [ ] Callbacks: \<None>
- [ ] Handlers: \<FS>
- [ ] Others: \______

Code used:
```
$vcSize[users]
```

More:
- Aoi.js version: 3.0.0
- Node.js version: 
- Operating system: MacOS (Big Sur) (if it's about where it's hosted, it's hosted on Dynox Host).

Screenshots (If any): Image or Link https://cdn.discordapp.com/attachments/848531878406651944/848909679866413066/Screenshot_2021-05-31_at_3.03.56_PM.png

**Comment by BetaDv** [comment]
screenshot not working

**Comment by falsisdev** [comment]
> 
> 
> ## Type
> - [ ] Functions: \<$vcSize>
> - [ ] Callbacks: \<None>
> - [ ] Handlers: \<FS>
> - [ ] Others: \______
> 
> Code used:
> ```
> $vcSize[users]
> ```
> 
> More:
> - Aoi.js version: 3.0.0
> - Node.js version: 
> - Operating system: MacOS (Big Sur) (if it's about where it's hosted, it's hosted on Dynox Host).
> 
> Screenshots (If any): Image or Link https://cdn.discordapp.com/attachments/848531878406651944/848909679866413066/Screenshot_2021-05-31_at_3.03.56_PM.png

![Screenshot_2021-05-31_at_1.29.49_PM.png](https://user-images.githubusercontent.com/63756985/120222607-df04ce00-c248-11eb-8a39-269357305537.png)
I think he's talking about this

**Comment by falsisdev** [comment]
![Screenshot_2021-05-31_at_1.29.49_PM.png](https://user-images.githubusercontent.com/63756985/120222686-0491d780-c249-11eb-999d-6c376784adb8.png)
ups

**Comment by falsisdev** [comment]
> ![Screenshot_2021-05-31_at_1.29.49_PM.png](https://user-images.githubusercontent.com/63756985/120222686-0491d780-c249-11eb-999d-6c376784adb8.png)
> ups
i think he talking about this

**Comment by BetaDv** [comment]
Can you send me the error?

**Comment by falsisdev** [comment]
> Can you send me the error?

As I see it does not give any answer

**Comment by BetaDv** [comment]
> > Can you send me the error?
> 
> As I see it does not give any answer

It does not help me identify the issue. It can be backend related (npm) or something with your bot

**Comment by bitshelf5562645** [comment]
> > > Can you send me the error?
> > 
> > 
> > As I see it does not give any answer
> 
> It does not help me identify the issue if I have no error. It can be backend related (npm) or something with your bot

There is no error, the problem is that when I try to use $vcSize[users] or $vcSize[users;$guildID] it doesn't send anything, it is not a problem with my bot itself because I requested some friends or people I work with to try it and it also didn't work for them. Essentially the problem is that the users option in $vcSize doesn't work if you try to limit it to the current server, because if you use all it will work but then it's global and not local. It only works local if no one's in a voice channel.

**Comment by USERSATOSHI** [comment]
@bitshelf5562645 @falsisdev vcSize is bugged for guild one 

i will check on this will pr the fix

**Comment by USERSATOSHI** [comment]
bug is fixed now it should work .

You can copy paste the code or wait for next Update 

![Bug Fix](https://user-images.githubusercontent.com/73595362/120227237-6ca2e680-c266-11eb-8b7f-ad6ea9a8dd4c.png)

**Comment by falsisdev** [comment]
k thx @USERSATOSHI :)
