### ISSUE TITLE
$charCount doubles the character count.

### ISSUE THREAD

**Issue by Alconera130** [aoijs/aoi.js#171]
![Screenshot_2021-06-01-11-37-38-36_572064f74bd5f9fa804b05334aa4f912](https://user-images.githubusercontent.com/83458587/120263278-f5a13880-c2cd-11eb-94a5-fb957e12ce7d.jpg)

**Comment by Alconera130** [comment]
Although this can be controlled by using `$math`, I really want this bug to be fixed

**Comment by USERSATOSHI** [comment]
> Although this can be controlled by using `$math`, I really want this bug to be fixed
> 

@Alconera130 not bugged in eval $message will count the whole message u put to eval that's why
use $charCount[hi] then try it will return 2

**Comment by Alconera130** [comment]
> > Although this can be controlled by using `$math`, I really want this bug to be fixed
> 
> @Alconera130 not bugged in eval $message will count the whole message u put to eval that's why
> use $charCount[hi] then try it will return 2

yes it returns 2. I have this in my `ascii` command that has an onlyIf saying that the max characters are 20 ($onlyIf[$charCount[$message]<20;]), the text is `< Aoi.Js >` which has only 10 characters, somehow the error activated. Would'nt be `$message` returns the message after command?

**Comment by USERSATOSHI** [comment]
> > > Although this can be controlled by using `$math`, I really want this bug to be fixed
> > 
> > @Alconera130 not bugged in eval $message will count the whole message u put to eval that's why
> > use $charCount[hi] then try it will return 2
> 
> yes it returns 2. I have this in my `ascii` command that has an onlyIf saying that the max characters are 20 ($onlyIf[$charCount[$message]<20;]), the text is `< Aoi.Js >` which has only 10 characters, somehow the error activated. Would'nt be `$message` returns the message after command?

well you see that < and > are converted into #RIGHT_CLICK# and #LEFT_CLICK# 

so now it will exceed 20 chars

**Comment by Alconera130** [comment]
> > > > Although this can be controlled by using `$math`, I really want this bug to be fixed
> > > 
> > > 
> > > @Alconera130 not bugged in eval $message will count the whole message u put to eval that's why
> > > use $charCount[hi] then try it will return 2
> > 
> > 
> > yes it returns 2. I have this in my `ascii` command that has an onlyIf saying that the max characters are 20 ($onlyIf[$charCount[$message]<20;]), the text is `< Aoi.Js >` which has only 10 characters, somehow the error activated. Would'nt be `$message` returns the message after command?
> 
> well you see that < and > are converted into #RIGHT_CLICK# and #LEFT_CLICK#
> 
> so now it will exceed 20 chars

ohh okay... Thanks for the info!
