### ISSUE TITLE
$addToBotFile

### ISSUE THREAD

**Issue by dhruvakalur** [aoijs/aoi.js#172]
## Type
- [ ] Functions: \<$addToBotFile>
- [ ] Callbacks: \<Callback Name>
- [ ] Handlers: \<Handler Type>
- [ ] Others: \__$addToBotFile[file ditectory;what to add]____

## Description
It works like adding a line of code to the given file directory

**Comment by USERSATOSHI** [comment]
> 
> 
> ## Type
> - [ ] Functions: \<$addToBotFile>
> - [ ] Callbacks: \<Callback Name>
> - [ ] Handlers: \<Handler Type>
> - [ ] Others: \__$addToBotFile[file ditectory;what to add]____
> 
> ## Description
> It works like adding a line of code to the given file directory

$writeFile

**Comment by USERSATOSHI** [comment]
@dhruvakalur ^
