### ISSUE TITLE
Commands start

### ISSUE THREAD

**Issue by abdullah09637** [aoijs/aoi.js#175]
Its a issue 
 if we make a buy command and made buy bag but in aoijs we cannot do like we have to put symbols -,_,,! We cannot space and use it i will show the example of now ex buy-bag we want like buy bag

**Comment by USERSATOSHI** [comment]
> Its a issue 
>  if we make a buy command and made buy bag but in aoijs we cannot do like we have to put symbols -,_,,! We cannot space and use it i will show the example of now ex buy-bag we want like buy bal 
> 
@abdullah09637 
you can put name as 
name:"buy"

and in code : part add

$onlyIf[$message[1]==bal;]

**Comment by abdullah09637** [comment]
Ok thanks

**Comment by abdullah09637** [comment]
But the team has to add it in most of the languages its there

**Comment by USERSATOSHI** [comment]
> But the team has to add it, in most of the languages its there 

well in aoijs ,the first word in the user message is counted as the command name 

other packages don't have a way to get cmd name so the user who is using the package define it the way they want it
