### ISSUE TITLE
"$varExist" Feature Request

### ISSUE THREAD

**Issue by ExtremeStylez** [aoijs/aoi.js#176]
## Type
- [  ] Functions: \$varExists[var name]
## Description
It checks if the bot has a prefix with a name that was inputed in the field!

Without Var:
Example:
$varExists[kxjejx]
Result: false
because kxjejx is not a var that the bot has!

With Var:
Example:
$varExists[prefix]
result: true
because var prefix does exists

**Comment by USERSATOSHI** [comment]
> 
> 
> ## Type
> - [  ] Functions: \$varExists[var name]
> ## Description
> It checks if the bot has a prefix with a name that was inputed in the field!
> 
> Without Var:
> Example:
> $varExists[kxjejx]
> Result: false
> because kxjejx is not a var that the bot has!
> 
> With Var:
> Example:
> $varExists[prefix]
> result: true
> because var prefix does exists

umm I don't think it required to be made as Function cause it's basically
```
$djseval[client.variables[d.args.join(" ")] ? true : false;yes]
```
@ExtremeStylez
