### ISSUE TITLE
$creationDate not working in DM

### ISSUE THREAD

**Issue by KASKUSTTV** [aoijs/aoi.js#177]
## Type
- [x] Functions: \<$creationDate[]>

Code used:
```
$formatDate[$creationDate[$get[author];ms];LLL]
$let[author;$authorID]
```

More:
- Aoi.js version: Latest
- Node.js version: Latest
- Operating system: replit.com

`$creationDate` is not working on dm, it is returning invalid role even i put $authorID in let

**Comment by USERSATOSHI** [comment]
@KASKUSTTV can you provide a screenshot?

**Comment by KASKUSTTV** [comment]
> @KASKUSTTV can you provide a screenshot?

```
TypeError: Cannot read property 'roles' of null
    at module.exports (/home/runner/KleeMail-1/node_modules/aoi.js/package/functions/funcs/creationDate.js:22:21)
    at interpreter (/home/runner/KleeMail-1/node_modules/aoi.js/package/interpreter.js:223:31)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by USERSATOSHI** [comment]
> > @KASKUSTTV can you provide a screenshot?
> 
> ```
> TypeError: Cannot read property 'roles' of null
>     at module.exports (/home/runner/KleeMail-1/node_modules/aoi.js/package/functions/funcs/creationDate.js:22:21)
>     at interpreter (/home/runner/KleeMail-1/node_modules/aoi.js/package/interpreter.js:223:31)
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)
> ```

ohk I will check the code then

**Comment by USERSATOSHI** [comment]
This is now Fixed
