### ISSUE TITLE
$if statement not working properly

### ISSUE THREAD

**Issue by KASKUSTTV** [aoijs/aoi.js#179]
## Type
- [x] Functions: \<$if, $elseIf, $else, $endelseIf, $endIf>

Code used:
```
https://srcb.in/wdRctyJ5IF
```

More:
- Aoi.js version: Latest
- Node.js version: Latest
- Operating system: replit.com

**Comment by unknown-software** [comment]
works fine on my end can you explain the error your getting

**Comment by USERSATOSHI** [comment]
Closed due to inactivity
