### ISSUE TITLE
Lavalink Music Changes

### ISSUE THREAD

**Issue by tolisdev** [aoijs/aoi.js#19]
## Type
- [ ] Functions: About all music functions

## Description
Hey there! It would be easier to implement lavalink in the regular music commands ($play). Let me explain how it works. If there is a lavalink stream using bot.createLavalink(), the bot would automatically use lavalink instead of ffmpeg.

**Comment by Kubaturi** [comment]
No, some people would like to use both ffmpeg and lavalink

**Comment by Kino7916** [comment]
Lavalink will not send a stream to request, how it works is different from ytdl-core.
