### ISSUE TITLE
$deleteDBUser function

### ISSUE THREAD

**Issue by bitshelf5562645** [aoijs/aoi.js#190]
## Type
- [X] Functions: $deleteDBUser
- [ ] Callbacks: \
- [ ] Handlers: \
- [ ] Others: \______

## Description
It completely removes a user from the dbdjs.db as in all variable values.
Options: User ID, example: $deleteDBUser[$authorid] or $deleteDBUser[$finduser[leref]].
This could be very helpful for reset commands (those that are used for users to request deletion of their info for policy and stuff), the reason this'd be helpful is that when someone has a big economy bot they can spare time of making a reset command with each variable name and instead just use this function.

**Comment by DinoTheDevOfficial** [comment]
you can already delete it by hand tho this will be more practical do it by going to new-database > main > main_scheme_1.sql

**Comment by BeastBoyADI** [comment]
No not for cloud db so maybe it will be a good idea 

> you can already delete it by hand tho this will be more practical do it by going to new-database > main > main_scheme_1.sql

If u use mongodb like me then u need this function for ease as it's stored on cloud

**Comment by USERSATOSHI** [comment]
> No not for cloud db so maybe it will be a good idea 
> 
> > you can already delete it by hand tho this will be more practical do it by going to new-database > main > main_scheme_1.sql
> 
> If u use mongodb like me then u need this function for ease as it's stored on cloud

@BeastBoyADI instead of $deleteDbUser 
i think $deleteDbData is better
and u can select which type of data to delete

**Comment by BeastBoyADI** [comment]
> > No not for cloud db so maybe it will be a good idea
> > > you can already delete it by hand tho this will be more practical do it by going to new-database > main > main_scheme_1.sql
> > 
> > 
> > If u use mongodb like me then u need this function for ease as it's stored on cloud
> 
> @BeastBoyADI instead of $deleteDbUser
> i think $deleteDbData is better
> and u can select which type of data to delete

Yeah like $deleteDbData[user/globaluser/channel/message]
