### ISSUE TITLE
ReferenceError: info is not defined

### ISSUE THREAD

**Issue by MaxIsDumbLoL** [aoijs/aoi.js#191]
![chrome_xKDNT3kljB](https://user-images.githubusercontent.com/73972313/121559351-8372d700-c9e4-11eb-8b70-a925ba6104cb.png)

**Comment by Leref** [comment]
That's within the actual fetching song Info.
Spotify and get video details isn't something we handle.

**Comment by Rubenennj** [comment]
#236
