### ISSUE TITLE
heeeeeeeeeeelppppppp

### ISSUE THREAD

**Issue by Scriptyyy13** [aoijs/aoi.js#192]
Info:
- Aoi.js version: 3.0.0
- Node.js version: 12
- Operating system: linux

Screenshots (If any): https://cdn.discordapp.com/attachments/773357157394939924/852677993414918205/Screenshot_20210611-0103172.png

pls help me, if i start my bot, server stopped with error on screenshot

**Comment by USERSATOSHI** [comment]
> Info:
> - Aoi.js version: 3.0.0
> - Node.js version: 12
> - Operating system: linux
> 
> Screenshots (If any): https://cdn.discordapp.com/attachments/773357157394939924/852677993414918205/Screenshot_20210611-0103172.png
> 
> 
> pls help me, if i start my bot, server stopped with error on screenshot

put ```js
process.setMaxListeners(50)
```
at top of ur mainfile
and
```js
bot.client.setMaxListeners(50)
```
below const bot = new aoi.Bot({...})
@Scriptyyy13

**Comment by Scriptyyy13** [comment]
thanks

**Comment by Scriptyyy13** [comment]
> > Info:
> > - Aoi.js version: 3.0.0
> > - Node.js version: 12
> > - Operating system: linux
> > 
> > Screenshots (If any): https://cdn.discordapp.com/attachments/773357157394939924/852677993414918205/Screenshot_20210611-0103172.png
> > 
> > 
> > pls help me, if i start my bot, server stopped with error on screenshot
> 
> put
>  ```js
> process.setMaxListeners(50)
> ```
> at top of ur mainfile
> and
> ```js
> bot.client.setMaxListeners(50)
> ```
> ```js
> below const bot = new aoi.Bot({...})
> ```
> @Scriptyyy13 

thank you!
