### ISSUE TITLE
Command Variables

### ISSUE THREAD

**Issue by KASKUSTTV** [aoijs/aoi.js#194]
## Type
- [x] Functions: \<$setCommandVar[name;value;guildID (optional)], $getCommandVar[name;guildID (optional)]>

## Description
Set a variable to a specific command, this will be very useful for command management like disable enable system and many more :3 | i hope it will be added next update

**Comment by USERSATOSHI** [comment]
> 
> 
> ## Type
> - [x] Functions: \<$setCommandVar[name;value;guildID (optional)], $getCommandVar[name;guildID (optional)]>
> 
> ## Description
> Set a variable to a specific command, this will be very useful for command management like disable enable system and many more :3 | i hope it will be added next update 

u can do that using serverVar
