### ISSUE TITLE
ability to add more properties in 1 json request

### ISSUE THREAD

**Issue by ArcDiscord** [aoijs/aoi.js#200]
some api's are randomized with multiple properties so it would be nice if we could add more properties seperated by a comma

**Comment by USERSATOSHI** [comment]
> some api's are randomized with multiple properties so it would be nice if we could add more properties seperated by a comma

ok if we add that feature who do u want the response from jsonRequest

**Comment by ArcDiscord** [comment]
maybe like $json.1st-property $json.2nd-property ?

**Comment by Rubenennj** [comment]
Maybe cache http url (and their respective responses) when used once and then reuse said value for the rest.

**Comment by USERSATOSHI** [comment]
> some api's are randomized with multiple properties so it would be nice if we could add more properties seperated by a comma

ok new solution to this

if u don't provide any property then it will send all data

which u can put into CreateObject and use getObjectProperty to get multiple values
