### ISSUE TITLE
Added Support Command In DM Bot

### ISSUE THREAD

**Issue by BranGamer145** [aoijs/aoi.js#207]
## Type
- [ ] Functions: \<Function Name>
- [ ] Callbacks: \<Callback Name>
- [ ] Handlers: \<Handler Type>
- [x] Others: pls Support Command/anything On DM Bot :(

## Description
Please Add So We Can Use Command/or anything in DM Bot Pls, *OnlyGuilds: false* But It Doesn't Work

**Comment by ElTuna** [comment]
already possible, use support channels in Discord

**Comment by ElTuna** [comment]
btw its
guildOnly: false

**Comment by BranGamer145** [comment]
> already possible, use support channels in Discord

Oh. 🤐

**Comment by USERSATOSHI** [comment]
issue solved
