### ISSUE TITLE
$globalBan

### ISSUE THREAD

**Issue by falsisdev** [aoijs/aoi.js#208]
## Type
- [x] Functions: $globalBan

## Description
Bans the user whose ID is entered from the servers whose ID is entered. If the bot is not member on the entered servers, it will give an error.

`$globalBan[userID;userID2;...;guildID;guildID2;...;Reason]`

## Usage
```js
$globalBan[$mentioned[1];$guildID;$guildID[Test];Test Reason]
```

## Error
```js
:x: Invalid guildID 770676924451651594 in (...)
```

**Comment by USERSATOSHI** [comment]
hmmm so like it's bans a user from multiple servers ?

**Comment by falsisdev** [comment]
> hmmm so like it's bans a user from multiple servers ?

Yes. And maybe => $globalKick

**Comment by BeastBoyADI** [comment]
It's a cool idea i liked it and some bots that r in d.js have the feature. I noticed while i was seeing audit logs
