### ISSUE TITLE
Template for creating fucntion

### ISSUE THREAD

**Issue by Rakejs** [aoijs/aoi.js#21]
## Type
- [ ] Functions: \<Function Name>
- [ ] Callbacks: \<Callback Name>
- [ ] Handlers: \<Handler Type>
- [ X] Others: \______Template

## Description
Explain how it works
Add a template.js to dev branch
like:

```
module.exports = async (d) => {
  const code = d.command.code;
  const inside = d.unpack();
  const err = d.inside(inside);
  if (err) return d.error(err);
  const [value1,value2,value3] = inside.splits; //or inside for only 1 param

  return {
    code: code.replaceLast(`$template${inside}`, "to replace"),
  };
};

```
so every function has the same structure.

**Comment by USERSATOSHI** [comment]
> ## Type
> * [ ]  Functions: <Function Name>
> * [ ]  Callbacks: <Callback Name>
> * [ ]  Handlers: <Handler Type>
> * [ X] Others: ______Template
> 
> ## Description
> Explain how it works
> Add a template.js to dev branch
> like:
> 
> ```
> module.exports = async (d) => {
>   const code = d.command.code;
>   const inside = d.unpack();
>   const err = d.inside(inside);
>   if (err) return d.error(err);
>   const [value1,value2,value3] = inside.splits; //or inside for only 1 param
> 
>   return {
>     code: code.replaceLast(`$template${inside}`, "to replace"),
>   };
> };
> ```
> 
> so every function has the same structure.

not every function have same formats
and each function can be different 
like unpack() can be done manually 
or u don't sometimes need args 
which might can become an issue later 
@Rakejs

**Comment by Rakejs** [comment]
yeah but is was made for complicated functions nvm

**Comment by soudblox** [comment]
not every functions use d.unpack()

**Comment by Rakejs** [comment]
nvm
