### ISSUE TITLE
ONLYIF 

### ISSUE THREAD

**Issue by KamexGaming** [aoijs/aoi.js#211]
$OnlyIf[$getUserVar[moderation]==yes || $getUserVar[support]==no;Error]

If var will be on yes or another var will be so then the command works. He wants to make it possible, because one by one it is wrong

**Comment by ElTuna** [comment]
use $checkCondition

**Comment by ElTuna** [comment]
$onlyIf[$checkCondition[condition1]$checkCondition[condition2]!=falsefalse;error message]

**Comment by KamexGaming** [comment]
> $onlyIf[$checkCondition[condition1]$checkCondition[condition2]!=falsefalse;error message]

Can you do when it has permissions in this?

**Comment by ElTuna** [comment]
yeah, you can choose the conditions

**Comment by Rubenennj** [comment]
this change is probably impossible to achieve in aoijs conditions
