### ISSUE TITLE
Add the funtion $buttonSendMessage

### ISSUE THREAD

**Issue by CUBE2593k** [aoijs/aoi.js#213]
$buttonSendMessage[Mensaje Con Embed Errors o content;Components;return ID (yes/no);Channel ID (optional]

**Comment by Alconera130** [comment]
$apiMessage already exist

**Comment by CUBE2593k** [comment]
The problem is that you cannot send messages to a specific channel

**Comment by USERSATOSHI** [comment]
> $buttonSendMessage[Mensaje Con Embed Errors o content;Components;return ID (yes/no);Channel ID (optional]
> 

channelSendMessage and apiMessage both will support this in next update

**Comment by Leref** [comment]
It has been added.
