### ISSUE TITLE
$resumeSong not working

### ISSUE THREAD

**Issue by BeastBoyADI** [aoijs/aoi.js#214]
## Type
- [√] Functions: \$resumeSong
- [ ] Callbacks: \<Callback Name>
- [ ] Handlers: \<Handler Type>
- [ ] Others: \______

Code used:
```
$resumeSong
Song resumed
```

More:
- Aoi.js version: 4.0.1
- Node.js version: 14.17.0
- Operating system: linux

Screenshots (If any): Image or Link

**Comment by BeastBoyADI** [comment]
No error message but it doesn't resumes song

**Comment by BeastBoyADI** [comment]
> ## Type
> * [√] Functions: $resumeSong
> * [ ]  Callbacks: <Callback Name>
> * [ ]  Handlers: <Handler Type>
> * [ ]  Others: ______
> 
> Code used:
> 
> ```
> $resumeSong
> Song resumed
> ```
> 
> More:
> 
> * Aoi.js version: 4.0.1
> * Node.js version: 14.17.0
> * Operating system: linux
> 
> Screenshots (If any): Image or Link

Even many are facing same problems

**Comment by Leref** [comment]
Strange, I'm not getting this error.
Is there any codes, or something I can go with?

**Comment by BeastBoyADI** [comment]
I just used that code which i specified before don't know what error occurred. Even console is not logging any errors

**Comment by Leref** [comment]
It's working fine for me using the latest version,
Make sure the Client is online and is executing $playSong before.

**Comment by Leref** [comment]
Nothing has been else reported or told.
