### ISSUE TITLE
$userLeaderboard bug

### ISSUE THREAD

**Issue by LueyCoder** [aoijs/aoi.js#218]
## Type
- [x] Functions: $userLeaderboard
- [ ] Callbacks: \<Callback Name>
- [ ] Handlers: \<Handler Type>
- [ ] Others: \______

Code used:
```
$userLeaderboard[varex;asc;{top} - {username} - {value};15]
```

More: parameter list is buggy, instead of showing "20" for example, it keeps showing 10
- Aoi.js version:
- Node.js version:
- Operating system:

Screenshots (If any): Image or Link

**Comment by BeastBoyADI** [comment]
No it's not. The only reason it doesn't shows for all is the user value is not allotted to that many users till then. Bot needs to allot it to get that
