### ISSUE TITLE
$isWebhook[]

### ISSUE THREAD

**Issue by falsisdev** [aoijs/aoi.js#220]
## Type
- [x] Functions: $isWebhook[ID]

## Description
Checks if the user whose ID is entered is a webhook.

## Example

`Boolean`
```js
$isWebhook[848733320358395905] //true - MEE6 Webhook 🐱
$isWebhook[539843855567028227] //false - Me 🐱
```

`I couldn't find any discord.js code about it but maybe it's possible with discord-api.`

**Comment by BeastBoyADI** [comment]
Just use $webhookExists

**Comment by falsisdev** [comment]
> Just use $webhookExists

I just want to see if the user is a webhook. It has nothing to do with $webhookExists :D?
