### ISSUE TITLE
$osType

### ISSUE THREAD

**Issue by tiyonn** [aoijs/aoi.js#221]
## Type
-  🔨 Functions: $osType

## Description
Returns the bot client OS.

## Usage And Return

Usage is simple. Just write `$osType`. And it will returns the current client os.

## A Return Example

`Input: $eval[$osType]`
`Output: windows`

**Edit: As I remember Discord.js have a code like this.**

**Comment by falsisdev** [comment]
[Here](https://github.com/aoijs/aoi.js/pull/164) I posted a Pr like this...

**Comment by falsisdev** [comment]
> [Here](https://github.com/aoijs/aoi.js/pull/164) I posted a Pr like this...

You can use 
```js
$djsEval[require("os").platform();yes]
```

**Comment by tiyonn** [comment]
Thanks!
