### ISSUE TITLE
$textSplit() bug

### ISSUE THREAD

**Issue by falsisdev** [aoijs/aoi.js#222]
## Type
- [x] Functions: $textSplit()

## Code used:
```js
$joinSplitText[ ]
$textSplit[1, 2, 3, 4;, ]
```

## Info
- Aoi.js version: git+https://github.com/aoijs/aoi.js#dev / 4.0.3
- Node.js version: v12
- Operating system: linux

## ScreenShot
<img src="https://cdn.discordapp.com/attachments/775822548519616562/862991748195418112/unknown.png">

## Description
**Separator** in $textSplit() is not working...

**Comment by USERSATOSHI** [comment]
remove the space between `,` then try @falsisdev

**Comment by falsisdev** [comment]
Same

**Comment by USERSATOSHI** [comment]
> Same

@falsisdev try with a different seperator

**Comment by falsisdev** [comment]
![IMG_20210709_204051.jpg](https://user-images.githubusercontent.com/63756985/125116841-f95a8300-e0f5-11eb-8310-8eed61850f98.jpg)
But why is `, ` not working?

**Comment by USERSATOSHI** [comment]
ok ik 
it will work in code but not in eval because
, is escaped to #COMMA#

**Comment by falsisdev** [comment]
hmmm i understand thx
