### ISSUE TITLE
"$deletecommand" Breaks alot of times

### ISSUE THREAD

**Issue by eRaZeCooler** [aoijs/aoi.js#224]
## Type
- [ ] Functions: \$deletecommand

Code used:
```
but i have Anti-Curse and Anti-Link system and sometimes when i turn on the anti system it dosnt delete the Curse/link words it just sends the "You cannot curse here" message it dont delete it pls tell meh what im doing wrong```

More:
- Aoi.js version: Highest
- Node.js version: idk
- Operating system: An hosting server!

**Comment by abdullah09637** [comment]
Check bot has permissions to delete the message

**Comment by falsisdev** [comment]
If the bot didn't have permission, it would throw a `Missing Permissions` error.

**Comment by BeastBoyADI** [comment]
> If the bot didn't have permission, it would throw a `Missing Permissions` error.

Well yeah it should send but it doesn't in my case. Well don't know why but it doesn't send error message if it doesn't have perms

**Comment by Rubenennj** [comment]
Where does it break? This function is intended to not work in some callbacks because the message object in the interpreter is not *always* a real message object

**Comment by eRaZeCooler** [comment]
> If the bot didn't have permission, it would throw a `Missing Permissions` error.

Nope not that!

**Comment by eRaZeCooler** [comment]
> If the bot didn't have permission, it would throw a `Missing Permissions` error.

Not that!

**Comment by eRaZeCooler** [comment]
> Where does it break? This function is intended to not work in some callbacks because the message object in the interpreter is not _always_ a real message object

Ok so i have it in my anti-curse and anti-link things and when i enable them both it just says the error message it dosnt delete them?... it says "Please do not curse" or "Please do not send Links" it dont delete but SOMETIMES it deletes them idk whats wrong ;-;

**Comment by eRaZeCooler** [comment]
@Leref Can you please help? thanks!

**Comment by eRaZeCooler** [comment]
> Where does it break? This function is intended to not work in some callbacks because the message object in the interpreter is not _always_ a real message object

ok so i have it in my !antilink and !anticurse so when i enable them SOMETIMES it dont delete the curse/link but SOMETIMES it deletes them idk what the problem is so... if its a error please help fix it thanks :)

**Comment by BeastBoyADI** [comment]
> > Where does it break? This function is intended to not work in some callbacks because the message object in the interpreter is not _always_ a real message object
> 
> ok so i have it in my !antilink and !anticurse so when i enable them SOMETIMES it dont delete the curse/link but SOMETIMES it deletes them idk what the problem is so... if its a error please help fix it thanks :)

Maybe it's a ratelimit by discord

**Comment by eRaZeCooler** [comment]
> > > Where does it break? This function is intended to not work in some callbacks because the message object in the interpreter is not _always_ a real message object
> > 
> > 
> > ok so i have it in my !antilink and !anticurse so when i enable them SOMETIMES it dont delete the curse/link but SOMETIMES it deletes them idk what the problem is so... if its a error please help fix it thanks :)
> 
> Maybe it's a ratelimit by discord

i dont think its that but if it is how can i fix it? please help iv been waiting for almost a week or something

**Comment by Leref** [comment]
First of you stated it returns an error.
This can be by your code because $deletecommand deletes the Client message.
The only reason I can see is the Client is deleting messages at a rate which is being "RateLimited."

**Comment by eRaZeCooler** [comment]
> First of you stated it returns an error.
> This can be by your code because $deletecommand deletes the Client message.
> The only reason I can see is the Client is deleting messages at a rate which is being "RateLimited."

Hello by me saying "it breaks" mean like sometimes it do NOT delete the "links/BadWords" and idk how to fix that please help :)

**Comment by Leref** [comment]
As stated, this is your code,
It either deleting within 1 millisecond or takes time as multiple keywords it has to delete.
It not bugged at all.
