### ISSUE TITLE
$httpRequest: Method POST doesn't work

### ISSUE THREAD

**Issue by zlures** [aoijs/aoi.js#24]
## Type
- [ ] Functions: $httpRequest
- [ ] Callbacks: Triggering command with message
- [ ] Handlers: None
- [ ] Others: METHOD: Post || Bot and Website in 1 project: Express and Aoi.JS || Hosting: Glitch

Code used:
```
$httpRequest[https://pamdandabeta.glitch.me/api/t/info;post;{"prefix":"$message"};;$error;]
Done! 
```

More:
- Aoi.js version: 1.0.0
- Node.js version: 12.x.x
- Operating system: Linux

**Comment by XzFirzal** [comment]
![Screenshot](https://cdn.discordapp.com/attachments/827730677759082526/837888471229005834/aaasgagsasgdsdgsdgdgssdgdgssdagdsgasd.png)
What do you mean by `doesn't work`

**Comment by zlures** [comment]
It's doesn't update.

**Comment by Cursed95** [comment]
it is still doesn't work

**Comment by XzFirzal** [comment]
![Works](https://cdn.discordapp.com/attachments/773364744240496640/844424764981641216/aaaafasggasagsaasggsdadgdgas.png)
I tested with discord api, and it works fine

**Comment by XzFirzal** [comment]
But, there is problem where it failed to caught the error so it return `undefined`, [Here is the fix](https://github.com/aoijs/aoi.js/commit/6228b14d8fe5ea7d15df80cdbf93c22aa6e0969d).
And also, u need to put the `content-type` header for methods other than GET
