### ISSUE TITLE
$jsonRequest is not working properly in boolean response

### ISSUE THREAD

**Issue by KASKUSTTV** [aoijs/aoi.js#240]
## Type
- [x] Functions: \<$jsonRequest>

This is the full json response
https://kitsu.io/api/edge/anime?filter[text]=Nisekoi

Code used:
```
$jsonRequest[https://kitsu.io/api/edge/anime?filter[text]=Nisekoi;data#RIGHT#0#LEFT#.attributes.nsfw]
```

More:
- Aoi.js version: Latest
- Node.js version: 12

**Comment by USERSATOSHI** [comment]
@KASKUSTTV ss?

**Comment by KASKUSTTV** [comment]
> @KASKUSTTV ss?

https://i.kaskus.cf/k6Yo6sZ

This issue is almost a month :/
