### ISSUE TITLE
$if function never worked as it should, and that's a problem

### ISSUE THREAD

**Issue by ap0sentada** [aoijs/aoi.js#241]
## Type
- [x] Functions: $if
- [ ] Callbacks: \<Callback Name>
- [ ] Handlers: \<Handler Type>
- [ ] Others: \______

Code used:
```
fix the $if functions. 
actually if executes before all code, and that breaks the main function of if! check variables!

example:

{
$get[o] 
$if[$get[i]==1]

$let[o;yes]
$else
$let[o;no]
$endif

$let[i;1] 
}

in this case it should return "yes", but it returns "no", as the variable "i" has not yet been stored!
```

More:
- Aoi.js version: 4.x+
- Node.js version: v14
- Operating system: any

Screenshots (If any): https://cdn.discordapp.com/attachments/849899836530884610/865574166475964467/unknown.png

**Comment by USERSATOSHI** [comment]
$if executes seperately from the rest of the code
that's how it was made

**Comment by ap0sentada** [comment]
> $if executes seperately from the rest of the code
> that's how it was made

can't make it work with the code? even reversing the reading position (from top to bottom)

**Comment by USERSATOSHI** [comment]
> > $if executes seperately from the rest of the code
> > that's how it was made
> 
> can't make it work with the code? even reversing the reading position (from top to bottom)

well to make it work rn is to make it bottom to top format

**Comment by ap0sentada** [comment]
> > > $if executes seperately from the rest of the code
> > > that's how it was made
> > 
> > 
> > can't make it work with the code? even reversing the reading position (from top to bottom)
> 
> well to make it work rn is to make it bottom to top format

make instead of recognizing $if as start, recognize $endif?

**Comment by USERSATOSHI** [comment]
hmm I was thinking of that too

ig I will try that

**Comment by Leref** [comment]
If statement function will be improved in v5.
