### ISSUE TITLE
Disable mentions don't work with $channelSendMessage

### ISSUE THREAD

**Issue by BeastBoyADI** [aoijs/aoi.js#245]
## Type
- [x] Functions: \$channelSendMessage
- [ ] Callbacks: \<Callback Name>
- [ ] Handlers: \<Handler Type>
- [ ] Others: \______

Code used:
```
$channelSendMessage[$channelID;$message]
$disableRoleMentions
$disableEveryoneMentions
```

More:
- Aoi.js version: 4.2.1
- Node.js version: 14.x
- Operating system: linux

Screenshots (If any): Image or Link

**Comment by falsisdev** [comment]
Write the message instead of using $channelID.
```js
$message
$disableRoleMentions
$disableEveryoneMentions
```

**Comment by BeastBoyADI** [comment]
No i mean i use like ```
$channelSendMessage[$message[1];$messageSlice[1]]
```
And it didn't disable mentions even if i used the $disableRoleMentions
$disableEveryoneMentions

**Comment by DevSpen** [comment]
Can reproduce.

![ex](https://user-images.githubusercontent.com/69215413/126881521-0e821678-1c84-4237-b5f0-c5c696ba391f.png)

**Comment by USERSATOSHI** [comment]
it wasn't supposed to work with channelSendMessage

**Comment by USERSATOSHI** [comment]
inactive

**Comment by BeastBoyADI** [comment]
> it wasn't supposed to work with channelSendMessage

The thing is it also don't work with $sendMessage isn't there a way to let it work with atleast $sendMessage

**Comment by BeastBoyADI** [comment]
As i use $sendMessage in my one of the commands for getting it's id and I don't want it to ping a role

**Comment by USERSATOSHI** [comment]
> > it wasn't supposed to work with channelSendMessage
> 
> The thing is it also don't work with $sendMessage isn't there a way to let it work with atleast $sendMessage

it's not suppose to work with that either

**Comment by USERSATOSHI** [comment]
disable mentions Functions is for disabling the mentions in the main message which is formed by $title and stuff
$sendmessage sends the message before these

**Comment by BeastBoyADI** [comment]
> disable mentions Functions is for disabling the mentions in the main message which is formed by $title and stuff
> $sendmessage sends the message before these

So can u say a way to get the id of the message the bot sent as i need it for some cmds

**Comment by BeastBoyADI** [comment]
Like $sendMessage was doing the work by giving id

**Comment by USERSATOSHI** [comment]
uh u can't get the id of main message

but sendmessage is updated in V5 so u probably can then disable things then
