### ISSUE TITLE
inline buttons

### ISSUE THREAD

**Issue by ap0sentada** [aoijs/aoi.js#246]
## Type
- [x] Others: inline buttons (there are packages that can help with this)

## Description
works like normal buttons but inline, being possible to make rows of buttons
like this:
![img](https://cdn.discordapp.com/attachments/849899836530884610/866289841246044180/unknown.png)

**Comment by USERSATOSHI** [comment]
@ap0sentada inline buttons are already possible
u can use more than 1 button in {actionRow

**Comment by ap0sentada** [comment]
> @ap0sentada inline buttons are already possible
> u can use more than 1 button in {actionRow

but have a limit, 5 buttons in {actionRow

**Comment by USERSATOSHI** [comment]
```js
{actionRow:button1,2,1,but1:button2,2,1,but2}
```

**Comment by USERSATOSHI** [comment]
> > @ap0sentada inline buttons are already possible
> > u can use more than 1 button in {actionRow
> 
> but have a limit, 5 buttons in {actionRow

u can use more than 1 actionRow
limit is 5

**Comment by ap0sentada** [comment]
> > > @ap0sentada inline buttons are already possible
> > > u can use more than 1 button in {actionRow
> > 
> > 
> > but have a limit, 5 buttons in {actionRow
> 
> u can use more than 1 actionRow
> limit is 5

oh, true. thanks
