### ISSUE TITLE
Add delete author message option in  $suppressError

### ISSUE THREAD

**Issue by KASKUSTTV** [aoijs/aoi.js#247]
## Type
- [x] Functions: \<$suppressError>

## Description
It will delete the author message if $suppressError is triggered, in short it's just like the $deleteCommand added as an option in the $suppressError

**Comment by BeastBoyADI** [comment]
Already exists. Use {deletedCommand} or {deletedCommand:time}

**Comment by KASKUSTTV** [comment]
> Already exists. Use {deletedCommand} or {deletedCommand:time}

Ohh,ok sry
