### ISSUE TITLE
Leaderboard values not showing up

### ISSUE THREAD

**Issue by Wiskerl** [aoijs/aoi.js#251]
Hi there, I've noticed that with the last version of aoi.js the leaderboard info is not showing up properly. Some scores just dissapear from the list. I'm getting several complaints about it tho. Probably it's a bug?

## Type
- [ ] Functions: $userLeaderboard

Code used:
$description[$userLeaderboard[points;asc;**{top}.** {username} - {value} $customEmoji[inflatable;711390630542180412]]]

More:
- Aoi.js version: 4.2.1
- Operating system: Windows 10

**Comment by USERSATOSHI** [comment]
> Hi there, I've noticed that with the last version of aoi.js the leaderboard info is not showing up properly. Some scores just dissapear from the list. I'm getting several complaints about it tho. Probably it's a bug?
> 
> ## Type
> * [ ]  Functions: $userLeaderboard
> 
> Code used:
> $description[$userLeaderboard[points;asc;**{top}.** {username} - {value} $customEmoji[inflatable;711390630542180412]]]
> 
> More:
> 
> * Aoi.js version: 4.2.1
> * Operating system: Windows 10

try updating the var of a user then check
