### ISSUE TITLE
i tried to make a anti-swear thing but it deletes other messages too , i couldnt find anything wrong in the code so it must be a bug.

### ISSUE THREAD

**Issue by aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa77** [aoijs/aoi.js#252]
Code used:
```
https://srcshare.io/?id=60f9549dd568291b0f398bb5
```
More:
- Aoi.js version: ^4.2.1
- Node.js version: v12.22.1
- Operating system: linux

https://i-th.ink/asterio🪐-is-hot/yhblfqbt

**Comment by USERSATOSHI** [comment]
> Code used:
> 
> ```
> https://srcshare.io/?id=60f9549dd568291b0f398bb5
> ```
> 
> More:
> 
> * Aoi.js version: ^4.2.1
> * Node.js version: v12.22.1
> * Operating system: linux
> 
> [https://i-th.ink/asterio🪐-is-hot/yhblfqbt](https://i-th.ink/asterio%F0%9F%AA%90-is-hot/yhblfqbt)

it's a code issue

$if executes before everything else so put ur checkcontains and onlyif inside them
