### ISSUE TITLE
$onlyForIDs is broken

### ISSUE THREAD

**Issue by ap0sentada** [aoijs/aoi.js#255]
## Type
- [x] Functions: <$onlyForIDs[id;error]>

Code used:
```
$onlyForIDs[691726916217995286;]
```

More:
- Aoi.js version:
- Node.js version:
- Operating system:

Screenshots:
![](https://cdn.discordapp.com/attachments/813121117476225056/869000303326945280/unknown.png)

**Comment by Leref** [comment]
Strange, where did you use the function in?

**Comment by ap0sentada** [comment]
> Strange, where did you use the function in?

a common command.
```js
bot.command({
name:"test",
code:`
sure
$onlyForIDs[691726916217995286;]`
})
```

**Comment by Leref** [comment]
Perhaps the ID was not cache, if you could do
`$cacheMembers` it will cache the Author ID.
Then re-test the usage.

**Comment by USERSATOSHI** [comment]
> ## Type
> * [x]  Functions: <$onlyForIDs[id;error]>
> 
> Code used:
> 
> ```
> $onlyForIDs[691726916217995286;]
> ```
> 
> More:
> 
> * Aoi.js version:
> * Node.js version:
> * Operating system:
> 
> Screenshots:
> ![](https://camo.githubusercontent.com/b5b09cd6903d4e793aa14bf18381b16345ff7cd119f9b1ff43dbaae088c55b04/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3831333132313131373437363232353035362f3836393030303330333332363934353238302f756e6b6e6f776e2e706e67)

@ap0sentada  onlyForIds won't work in bot.readyCommand because bot doesn't habe access to users when it connects to Discord

it gets user data a bit after
