### ISSUE TITLE
""open source""

### ISSUE THREAD

**Issue by Darker-Ink** [aoijs/aoi.js#266]
Whats the point of open source if you are obfuscating [files](https://github.com/aoijs/aoi.js/blob/master/package/handlers/boosterAPI.js) You are breaking ToS having that in there. You are using USER tokens to get the booster API info

const _0x35beae = await axios['get'](_0x4846d9(0x1b0) + boostFile, {
                            'headers': {
                                'Authorization': 'Bearer ' + usertoken,
                                'Content-Type': 'application/json'
                            }
                        });

this is using a user token. It kinda seems dumb lmao

**Comment by Rubenennj** [comment]
Where's in the fuck does it say discord user token
a user token is not always meant to be a discord user token
so i could pretty much say the dumb one here is you assuming what it isn't

**Comment by USERSATOSHI** [comment]
> Whats the point of open source if you are obfuscating [files](https://github.com/aoijs/aoi.js/blob/master/package/handlers/boosterAPI.js) You are breaking ToS having that in there. You are using USER tokens to get the booster API info
> 
> 
> const _0x35beae = await axios['get'](_0x4846d9(0x1b0) + boostFile, {
>                             'headers': {
>                                 'Authorization': 'Bearer ' + usertoken,
>                                 'Content-Type': 'application/json'
>                             }
>                         });
> 
> this is using a user token. It kinda seems dumb lmao

@Darker-Ink 
about this topic,

this file was made to give boosters beta access to the functions when 

aoi.js was known as `dbd.js` and wasn't `open source`
after aoijs because open source and dev branch was introduced 

that file had no purpose at all

it's just that no one cared (or actually forget) to remove  it from the package.

this file right now is basically not needed anymore so in V5 it's will be removed

**Comment by USERSATOSHI** [comment]
[files](https://github.com/aoijs/aoi.js/blob/master/package/handlers/boosterAPI.js) You are breaking ToS having that in there. You are using USER tokens to get the booster API info
> 
> 
> const _0x35beae = await axios['get'](_0x4846d9(0x1b0) + boostFile, {
>                             'headers': {
>                                 'Authorization': 'Bearer ' + usertoken,
>                                 'Content-Type': 'application/json'
>                             }
>                         });
> 
> this is using a user token. It kinda seems dumb lmao

uh user Token is for our api 

not discord User token :/
there is a `boosterToken` property in Bot Class of Aoijs
![boosterToken.png](https://user-images.githubusercontent.com/73595362/129664987-8cdc9663-bac0-4a98-9e6c-02708499bd89.png)

**Comment by Darker-Ink** [comment]
> > Whats the point of open source if you are obfuscating [files](https://github.com/aoijs/aoi.js/blob/master/package/handlers/boosterAPI.js) You are breaking ToS having that in there. You are using USER tokens to get the booster API info
> > const _0x35beae = await axios['get'](_0x4846d9(0x1b0) + boostFile, {
> > 'headers': {
> > 'Authorization': 'Bearer ' + usertoken,
> > 'Content-Type': 'application/json'
> > }
> > });
> > this is using a user token. It kinda seems dumb lmao
> 
> @Darker-Ink
> about this topic,
> 
> this file was made to give boosters beta access to the functions when
> 
> aoi.js was known as `dbd.js` and wasn't `open source`
> after aoijs because open source and dev branch was introduced
> 
> that file had no purpose at all
> 
> it's just that no one cared (or forgot) to remove it from the package.
> 
> this file right now is basically not needed anymore so in V5 it's will be removed

You shouldn't obfuscate code though, It makes it 100000000000000% more sus when you are hiding code. And can I say the person that got really mad over this is making my die XDD

**Comment by Darker-Ink** [comment]
> Where's in the fuck does it say discord user token
> a user token is not always meant to be a discord user token
> so i could pretty much say the dumb one here is you assuming what it isn't

dumbass I was deobfuscating it and I named the var that it 100% looks like you guys are accessing the discord API with a user token

**Comment by USERSATOSHI** [comment]
> > > Whats the point of open source if you are obfuscating [files](https://github.com/aoijs/aoi.js/blob/master/package/handlers/boosterAPI.js) You are breaking ToS having that in there. You are using USER tokens to get the booster API info
> > > const _0x35beae = await axios['get'](_0x4846d9(0x1b0) + boostFile, {
> > > 'headers': {
> > > 'Authorization': 'Bearer ' + usertoken,
> > > 'Content-Type': 'application/json'
> > > }
> > > });
> > > this is using a user token. It kinda seems dumb lmao
> > 
> > @Darker-Ink
> > about this topic,
> > 
> > this file was made to give boosters beta access to the functions when
> > 
> > aoi.js was known as `dbd.js` and wasn't `open source`
> > after aoijs because open source and dev branch was introduced
> > 
> > that file had no purpose at all
> > 
> > it's just that no one cared (or forgot) to remove it from the package.
> > 
> > this file right now is basically not needed anymore so in V5 it's will be removed
> 
> You shouldn't obfuscate code though, It makes it 100000000000000% more sus when you are hiding code. And can I say the person that got really mad over this is making my die XDD

uh well no one wants there booster api code 
to be leaked / plagiarized 

and again I am saying that this was made when **aoi.js wasn't an open source**
the moment it went open source

the file became useless

**Comment by USERSATOSHI** [comment]
> > Where's in the fuck does it say discord user token
> > a user token is not always meant to be a discord user token
> > so i could pretty much say the dumb one here is you assuming what it isn't
> 
> dumbass I was deobfuscating it and I named the var that it 100% looks like you guys are accessing the discord API with a user token

uhhhhhhh u should have checked
all the files , which are linked
to boosterApi

or where boosterApi
was used

if u had checked bot.js
u could have tell that its token for our api

*so next time I would like you to suggest that
please do a throughout checking of a topic*

about variable name

uh it's doesn't really mean that if it's user token then it's for Discord

i mean like I can fr define 

client in bot.js as

`dapiGreaterThanDjs`

**Comment by BeastBoyADI** [comment]
> Whats the point of open source if you are obfuscating [files](https://github.com/aoijs/aoi.js/blob/master/package/handlers/boosterAPI.js) You are breaking ToS having that in there. You are using USER tokens to get the booster API info
> 
> const _0x35beae = await axios['get'](_0x4846d9(0x1b0) + boostFile, {
> 'headers': {
> 'Authorization': 'Bearer ' + usertoken,
> 'Content-Type': 'application/json'
> }
> });
> 
> this is using a user token. It kinda seems dumb lmao

A mad user who just come and claim like this without checking everything of the code. Don't claim like this if u have not gone through each and every code
