### ISSUE TITLE
Unable to start bot

### ISSUE THREAD

**Issue by TeamColaDev** [aoijs/aoi.js#269]
## Type
- [ ] Functions: \<Function Name>
- [ ] Callbacks: \<Callback Name>
- [ ] Handlers: \<Handler Type>
- [ ] Others: \______

Code used:
```
Your Code Here
```

More:
- Aoi.js version:
- Node.js version:
- Operating system:

Screenshots (If any): Image or Link

**Comment by Leref** [comment]
Duplicate of #270
