### ISSUE TITLE
$channel doesn't work

### ISSUE THREAD

**Issue by Miduwu** [aoijs/aoi.js#27]
## Type
- [x] Bug Fix
- [ ] Functions: \<Function Name>
- [ ] Callbacks: \<Callback Name>
- [ ] Handlers: \<Handler Type>
- [ ] Others: \______

Code used:
```
$channel[$channelID;created]
all properties too
```

More:
- Aoi.js version: 1.0.1

Well... $channel function is not working, all properties don't work
![image](https://user-images.githubusercontent.com/83442808/116769397-691b0600-aa01-11eb-8f12-44638ce26e86.png)

**Comment by XzFirzal** [comment]
![FIxed](https://cdn.discordapp.com/attachments/827730677759082526/837894451015843860/aaasfgasdsdggadadgsdgssggdsdgs.png)
https://github.com/aoijs/aoi.js/commit/20f9279c33f416cc59a9135de71223a1841a4b8a
Fixed!
