### ISSUE TITLE
Unable to start bot

### ISSUE THREAD

**Issue by TeamColaDev** [aoijs/aoi.js#270]
When I attempt to start my bot I get an error which is:

`/home/container/node_modules/aoi.js/package/interpreter.js:21
    .split("\\]")
     ^`

Any help would be apperciated
![image](https://user-images.githubusercontent.com/67055603/130507927-f675b841-5afb-49e1-b877-f594431c3eda.png)

**Comment by USERSATOSHI** [comment]
> When I attempt to start my bot I get an error which is:
> 
> `/home/container/node_modules/aoi.js/package/interpreter.js:21
>     .split("\\]")
>      ^`
> 
> Any help would be apperciated
> ![image](https://user-images.githubusercontent.com/67055603/130507927-f675b841-5afb-49e1-b877-f594431c3eda.png)
> 

van i see ur Code of bot.readyCommand

**Comment by Phydose** [comment]
> > When I attempt to start my bot I get an error which is:
> > `/home/container/node_modules/aoi.js/package/interpreter.js:21 .split("\\]") ^`
> > Any help would be apperciated
> > ![image](https://user-images.githubusercontent.com/67055603/130507927-f675b841-5afb-49e1-b877-f594431c3eda.png)
> 
> can i see ur Code of bot.readyCommand. @TeamColaDev

hello so it's not the ready command but the status handler he is using

**Comment by gamelife2572** [comment]
Me too

**Comment by gamelife2572** [comment]
> > > When I attempt to start my bot I get an error which is:
> > > `/home/container/node_modules/aoi.js/package/interpreter.js:21 .split("\\]") ^`
> > > Any help would be apperciated
> > > ![image](https://user-images.githubusercontent.com/67055603/130507927-f675b841-5afb-49e1-b877-f594431c3eda.png)
> > 
> > can i see ur Code of bot.readyCommand. @TeamColaDev
> 
> hello so it's not the ready command but the status handler he is using

@TeamColaDev how to the error

**Comment by gamelife2572** [comment]
bot.readyCommand({
    channel: "862075278455996486", 
    code: `$log[Ready on $userTag[$clientID]]` //Enter the code / message.
})

This is my bot.ready commamd it was this for me

**Comment by USERSATOSHI** [comment]
> > > When I attempt to start my bot I get an error which is:
> > > `/home/container/node_modules/aoi.js/package/interpreter.js:21 .split("\\]") ^`
> > > Any help would be apperciated
> > > ![image](https://user-images.githubusercontent.com/67055603/130507927-f675b841-5afb-49e1-b877-f594431c3eda.png)
> > 
> > can i see ur Code of bot.readyCommand. @TeamColaDev
> 
> hello so it's not the ready command but the status handler he is using

@Phydose if u see the location of the error

it says interpreter.js then it says **readyCommands.js** 

which is a Handler for bot.readyCommand

which concludes that his bot.readyCommand doesn't have channel: property

**Comment by Phydose** [comment]
> > > > When I attempt to start my bot I get an error which is:
> > > > `/home/container/node_modules/aoi.js/package/interpreter.js:21 .split("\\]") ^`
> > > > Any help would be apperciated
> > > > ![image](https://user-images.githubusercontent.com/67055603/130507927-f675b841-5afb-49e1-b877-f594431c3eda.png)
> > > 
> > > 
> > > can i see ur Code of bot.readyCommand. @TeamColaDev
> > 
> > 
> > hello so it's not the ready command but the status handler he is using
> 
> @Phydose if u see the location of the error
> 
> it says interpreter.js then it says **readyCommands.js**
> 
> which is a Handler for bot.readyCommand
> 
> which concludes that his bot.readyCommand doesn't have channel: property

i had the same error while using a status handler

**Comment by USERSATOSHI** [comment]
> > > > > When I attempt to start my bot I get an error which is:
> > > > > `/home/container/node_modules/aoi.js/package/interpreter.js:21 .split("\\]") ^`
> > > > > Any help would be apperciated
> > > > > ![image](https://user-images.githubusercontent.com/67055603/130507927-f675b841-5afb-49e1-b877-f594431c3eda.png)
> > > > 
> > > > 
> > > > can i see ur Code of bot.readyCommand. @TeamColaDev
> > > 
> > > 
> > > hello so it's not the ready command but the status handler he is using
> > 
> > @Phydose if u see the location of the error
> > 
> > it says interpreter.js then it says **readyCommands.js**
> > 
> > which is a Handler for bot.readyCommand
> > 
> > which concludes that his bot.readyCommand doesn't have channel: property
> 
> i had the same error while using a status handler

status never had a handler

**Comment by Leref** [comment]
This is on your end.
the readyCommand `channel` is either invalid or incorrectly used.

**Comment by gamelife2572** [comment]
> This is on your end.
> the readyCommand `channel` is either invalid or incorrectly used.
> 

Is my one wrong

**Comment by USERSATOSHI** [comment]
> > This is on your end.
> > the readyCommand `channel` is either invalid or incorrectly used.
> > 
> 
> Is my one wrong

@TeamColaDev send ur bot.readyCommand then

**Comment by gamelife2572** [comment]
> > > This is on your end.
> > > the readyCommand `channel` is either invalid or incorrectly used.
> > > 
> > 
> > Is my one wrong
> 
> @TeamColaDev send ur bot.readyCommand then

bot.readyCommand({
channel: "",
code: $log[Ready on $userTag[$clientID]] //Enter the code / message.
})
 There my in case

**Comment by USERSATOSHI** [comment]
```js
bot.readyCommand({
channel: "",
code: `$log[Ready on $userTag[$clientID]]` 
})```

**Comment by gamelife2572** [comment]
Thanks 😂😂😁😂
