### ISSUE TITLE
reaction collector not working after bot restart

### ISSUE THREAD

**Issue by Mikquaj** [aoijs/aoi.js#271]
## Type
- [ ] Functions: $reactionCollector

Code used:
```
bot.command({
    name: "reaction-role-add",
    aliases: ["rr-add"],
    code: `
    $title[Success]
    $description[Dodano **<@&$getServerVar[rr1]>** jako reaction role, jeżeli nie będę dodawał roli daj moją role najwyżej jak możesz.]
    $color[RANDOM]
    $addTimestamp
    $footer[ReactionRole | ❤]
   $reactionCollector[$message[1];everyone;24d;$message[2];RR1;no]
    $setServerVar[rr1;$mentionedRoles[1]]
   $argsCheck[3; Spróbuj: \`$getServerVar[prefix]rr-add <messageID> <emoji> <@role>\`]
   $suppressErrors[Spróbuj tego: \`$getServerVar[prefix]rr-add <messageID> <emoji> <@role>\`
   lub sprawdź, czy mam wystarczające uprawnienia, aby nadać tę rolę i dodać reakcje]
   $onlyPerms[managechannels;Nie masz permisji!]
   `
   })

bot.awaitedCommand({
name: "RR1",
code: `
$giveRoles[$authorID;$getServerVar[rr1]]
`
})

bot.variables({
rr1: "",
})
```

More:
- Aoi.js version: 4.4.4
- Node.js version: 16.7.0
- Operating system: Windows 10

**Comment by Mikquaj** [comment]
> > 
> >  
> > ## Type
> > - [ ] Functions: $reactionCollector
> > 
> > Code used:
> > ```
> > bot.command({
> >     name: "reaction-role-add",
> >     aliases: ["rr-add"],
> >     code: `
> >     $title[Success]
> >     $description[Dodano **<@&$getServerVar[rr1]>** jako reaction role, jeżeli nie będę dodawał roli daj moją role najwyżej jak możesz.]
> >     $color[RANDOM]
> >     $addTimestamp
> >     $footer[ReactionRole | ❤]
> >    $reactionCollector[$message[1];everyone;24d;$message[2];RR1;no]
> >     $setServerVar[rr1;$mentionedRoles[1]]
> >    $argsCheck[3; Spróbuj: \`$getServerVar[prefix]rr-add <messageID> <emoji> <@role>\`]
> >    $suppressErrors[Spróbuj tego: \`$getServerVar[prefix]rr-add <messageID> <emoji> <@role>\`
> >    lub sprawdź, czy mam wystarczające uprawnienia, aby nadać tę rolę i dodać reakcje]
> >    $onlyPerms[managechannels;Nie masz permisji!]
> >    `
> >    })
> > 
> > bot.awaitedCommand({
> > name: "RR1",
> > code: `
> > $giveRoles[$authorID;$getServerVar[rr1]]
> > `
> > })
> > 
> > bot.variables({
> > rr1: "",
> > })
> > ```
> > 
> > More:
> > - Aoi.js version: 4.4.4
> > - Node.js version: 16.7.0
> > - Operating system: Windows 10 
> > 
> 
> @Mikquaj yup it won't work after restart
> and thats how reactionCollector or any other Collector works

Uh ok
On the discord server I got information that Reaction Collector does not work

**Comment by Leref** [comment]
It should but Ayaka has answered your issue already.
