### ISSUE TITLE
Can't Join Server

### ISSUE THREAD

**Issue by Kazdev0** [aoijs/aoi.js#273]
Hello, Even though my account was opened 1 month ago, I can't login to the server
Discord Username & Tag : KazDev0#6874
İd : 867386516015415296

**Comment by Kazdev0** [comment]
@Leref

**Comment by Priyanshu360-cpu** [comment]
Try changing your contact details linked with the account, this could help, extras- you shouldn't be banned from the server

**Comment by USERSATOSHI** [comment]
@Kazdev0 u are already in the server
:/
![Screenshot_2021-08-29-19-13-53-38.png](https://user-images.githubusercontent.com/73595362/131252589-1e82a6ef-9866-490a-b93e-ccfb60ade5df.png)

**Comment by Kazdev0** [comment]
![image](https://user-images.githubusercontent.com/82215788/131261781-4d18e541-c54a-4037-8ab8-0e08a99136c5.png)
@USERSATOSHI

**Comment by Kazdev0** [comment]
hm

**Comment by Kazdev0** [comment]
kick me pls

**Comment by Kazdev0** [comment]
no ı dont join server 
ı am kicked server

**Comment by Kazdev0** [comment]
a bot kicks me
