### ISSUE TITLE
Bug with $songInfo[current_duration] and $pauseSong

### ISSUE THREAD

**Issue by Priyanshu360-cpu** [aoijs/aoi.js#274]
## Type
- [ ] Functions: \$songInfo[current_duration]

Code used:
```
$pausesong and $songInfo[current_duration]
```
Bug- song's current duration doesn't stops when we use $pauseSong which in turn breaks the music system 
More:
- Aoi.js version:4.4.4

Screenshots (If any): Image or Link- https://media.discordapp.net/attachments/855337245070196747/881584844822429746/Screenshot_20210829-223305.jpg

**Comment by Akihiro0666** [comment]
Oh yeah, the current duration doesn't stop.

**Comment by DanielSDSXX** [comment]
What

**Comment by DanielSDSXX** [comment]
Add You Bot: https://discord.gg/mXpYg2Qg
