### ISSUE TITLE
Add second field value option in $getEmbed

### ISSUE THREAD

**Issue by FWTxFAIZ0881** [aoijs/aoi.js#28]
Add second field value option in $getEmbed ex: $getEmbed[$channelID;messageID;fvalue[2]] can get the second field value

**Comment by USERSATOSHI** [comment]
> Add second field value option in $getEmbed ex: $getEmbed[$channelID;messageID;fvalue[2]] can get the second field value

sure I will try making that

**Comment by DiscordBond** [comment]
I already coded all missing functions. I already submitted it here

**Comment by FWTxFAIZ0881** [comment]
So now, i can get the second fvalue or more?

**Comment by DiscordBond** [comment]
Not yet but very soon

**Comment by FWTxFAIZ0881** [comment]
Ok, thx 😊
