### ISSUE TITLE
Additional Feature for $channelPermissionsFor 

### ISSUE THREAD

**Issue by Akihiro0666** [aoijs/aoi.js#283]
## Type
- [ ] Functions: $channelPermissionsFor

## Description
so the function only works on $userID, but doesn't let us check the __everyone__'s permission. I tried using $guildID and @everyone's ID or everyone, but nothing seems to work. So I hope you add __everyone__ as an option.

**Comment by BeastBoyADI** [comment]
Hmm @USERSATOSHI what if u use `channel.permissionOverwrites.get()` for this instead of `member.permissionsIn()` as that would be more better for allowing support for role and members both

**Comment by Akihiro0666** [comment]
...

**Comment by Akihiro0666** [comment]
Are you gonna add this on v5.0.3?
