### ISSUE TITLE
MongoDB is not supported.

### ISSUE THREAD

**Issue by Alconera130** [aoijs/aoi.js#285]
why.
![Screenshot_2021-09-29-18-59-32-64_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/83458587/135256170-9a0c9d4e-6b71-41f9-b472-caea288e36fb.jpg)

**Comment by USERSATOSHI** [comment]
> why. ![Screenshot_2021-09-29-18-59-32-64_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/83458587/135256170-9a0c9d4e-6b71-41f9-b472-caea288e36fb.jpg)

did u used dbdjsmongo or what?

**Comment by Alconera130** [comment]
> > why. ![Screenshot_2021-09-29-18-59-32-64_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/83458587/135256170-9a0c9d4e-6b71-41f9-b472-caea288e36fb.jpg)
> 
> did u used dbdjsmongo or what?

i cant(?) use mongo with aoi if i dont use dbdjs.mongo :v ((to answer, yes, i used dbdjs.mongo))

**Comment by USERSATOSHI** [comment]
> i cant(?) use mongo with aoi if i dont use dbdjs.mongo :v 
@Alconera130 yup you can't use it unless I make a wrapper for mongoose (which I ain't gonna do)

**Comment by USERSATOSHI** [comment]
also send me ur database option

**Comment by Alconera130** [comment]
> also send me ur database option

```js
database:{ 
       type:"custom",
       db: dbdmongo,
       path:"./database/",//this doesn't work in quick.db 
       tables:["main"],
       promisify:true //converts quick.db to replicate as a promised db (or bluntly dbdjs.db)
    }
```
i just copy-pasted it in the documentation lol ((also to the dbdjs.mongo setup but i added useFindAndModify))

**Comment by USERSATOSHI** [comment]
> > also send me ur database option
> 
> ```js
> database:{ 
>        type:"custom",
>        db: dbdmongo,
>        path:"./database/",//this doesn't work in quick.db 
>        tables:["main"],
>        promisify:true //converts quick.db to replicate as a promised db (or bluntly dbdjs.db)
>     }
> ```
> i just copy-pasted it in the documentation lol ((also to the dbdjs.mongo setup but i added useFindAndModify))

it's type : "dbdjs.mongo" for thay

**Comment by Alconera130** [comment]
> > > also send me ur database option
> > 
> > 
> > ```js
> > database:{ 
> >        type:"custom",
> >        db: dbdmongo,
> >        path:"./database/",//this doesn't work in quick.db 
> >        tables:["main"],
> >        promisify:true //converts quick.db to replicate as a promised db (or bluntly dbdjs.db)
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > i just copy-pasted it in the documentation lol ((also to the dbdjs.mongo setup but i added useFindAndModify))
> 
> it's type : "dbdjs.mongo" for that
> 
> and make promisify false

just that? Or does it need to be case sensitive or whatsoever

**Comment by USERSATOSHI** [comment]
> i just copy-pasted it in the documentation lol ((also to the dbdjs.mongo setup but i added useFindAndModify))

i don't think there was a set-up for dbdjsmongo ij docs tho

**Comment by USERSATOSHI** [comment]
> > > > also send me ur database option
> > > 
> > > 
> > > ```js
> > > database:{ 
> > >        type:"custom",
> > >        db: dbdmongo,
> > >        path:"./database/",//this doesn't work in quick.db 
> > >        tables:["main"],
> > >        promisify:true //converts quick.db to replicate as a promised db (or bluntly dbdjs.db)
> > >     }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > i just copy-pasted it in the documentation lol ((also to the dbdjs.mongo setup but i added useFindAndModify))
> > 
> > 
> > it's type : "dbdjs.mongo" for that
> > and make promisify false
> 
> just that? Or does it need to be case sensitive or whatsoever

just change the type and make promisify false abd ur good to go
