### ISSUE TITLE
MongoDB on V4

### ISSUE THREAD

**Issue by tolisdev** [aoijs/aoi.js#286]
Hey, how can i use mongodb with aoi.js v4?
const mongoose = require('mongoose')
const mongo = require('dbdjs.mongo').default
mongoURL = 'mongourl'

mongoose.connect(mongoURL, {
    useNewUrlParser: true,
    useUnifiedTopology: true,
    useFindAndModify: false,
    keepAlive: true
})

mongo.createModel('main')

const bot = new Aoijs.Bot({
 token: token,
 prefix: "$getServerVar[prefix]",
 database: "mongo"
})

I get this error: C:\Users\Apostolos\Documents\Coding\Tolis Development Bots\TestBot\node_modules\aoi.js\package\handlers\timeoutHandling.js:4
    .all("main", {
     ^

TypeError: client.db.all is not a function
    at module.exports (C:\Users\Apostolos\Documents\Coding\Tolis Development Bots\TestBot\node_modules\aoi.js\package\handlers\timeoutHandling.js:4:6)
    at Timeout._onTimeout (C:\Users\Apostolos\Documents\Coding\Tolis Development Bots\TestBot\node_modules\aoi.js\package\events\ready.js:17:43)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)

**Comment by USERSATOSHI** [comment]
put db: mongo

**Comment by BeastBoyADI** [comment]
> Hey, how can i use mongodb with aoi.js v4? const mongoose = require('mongoose') const mongo = require('dbdjs.mongo').default mongoURL = 'mongourl'
> 
> mongoose.connect(mongoURL, { useNewUrlParser: true, useUnifiedTopology: true, useFindAndModify: false, keepAlive: true })
> 
> mongo.createModel('main')
> 
> const bot = new Aoijs.Bot({ token: token, prefix: "$getServerVar[prefix]", database: "mongo" })
> 
> I get this error: C:\Users\Apostolos\Documents\Coding\Tolis Development Bots\TestBot\node_modules\aoi.js\package\handlers\timeoutHandling.js:4 .all("main", { ^
> 
> TypeError: client.db.all is not a function at module.exports (C:\Users\Apostolos\Documents\Coding\Tolis Development Bots\TestBot\node_modules\aoi.js\package\handlers\timeoutHandling.js:4:6) at Timeout._onTimeout (C:\Users\Apostolos\Documents\Coding\Tolis Development Bots\TestBot\node_modules\aoi.js\package\events\ready.js:17:43) at listOnTimeout (node:internal/timers:557:17) at processTimers (node:internal/timers:500:7)

I used the same thing right now and it is working perfectly for me

**Comment by USERSATOSHI** [comment]
> > Hey, how can i use mongodb with aoi.js v4? const mongoose = require('mongoose') const mongo = require('dbdjs.mongo').default mongoURL = 'mongourl'
> > 
> > mongoose.connect(mongoURL, { useNewUrlParser: true, useUnifiedTopology: true, useFindAndModify: false, keepAlive: true })
> > 
> > mongo.createModel('main')
> > 
> > const bot = new Aoijs.Bot({ token: token, prefix: "$getServerVar[prefix]", database: "mongo" })
> > 
> > I get this error: C:\Users\Apostolos\Documents\Coding\Tolis Development Bots\TestBot\node_modules\aoi.js\package\handlers\timeoutHandling.js:4 .all("main", { ^
> > 
> > TypeError: client.db.all is not a function at module.exports (C:\Users\Apostolos\Documents\Coding\Tolis Development Bots\TestBot\node_modules\aoi.js\package\handlers\timeoutHandling.js:4:6) at Timeout._onTimeout (C:\Users\Apostolos\Documents\Coding\Tolis Development Bots\TestBot\node_modules\aoi.js\package\events\ready.js:17:43) at listOnTimeout (node:internal/timers:557:17) at processTimers (node:internal/timers:500:7)
> 
> I used the same thing right now and it is working perfectly for me

his Bot part is wrong

**Comment by BeastBoyADI** [comment]
Ohh
