### ISSUE TITLE
Better default erroring

### ISSUE THREAD

**Issue by cnnn666v2** [aoijs/aoi.js#289]
For example, instead of saying `random: Invalid number in [515;10]` maybe do this: `random: Invalid number in [515;10] for vars *var_name* and *var_name*`. Would be much easier than going thoruhg every single var in code and checking it's value

**Comment by BeastBoyADI** [comment]
Hmm well yeah true you could add the line index where the code errored for better ease of finding mainly when you have big codes

**Comment by USERSATOSHI** [comment]
created line system
