### ISSUE TITLE
A new feature of which maybe you would have thought but ye i wanna suggest it.

### ISSUE THREAD

**Issue by BeastBoyADI** [aoijs/aoi.js#290]
## Type
- [ ] Functions: \<Function Name>
- [ ] Callbacks: \<Callback Name>
- [ ] Handlers: \<Handler Type>
- [x] Others: New Code type

## Description
Explain how it works
Like as we know you have made `$djsEval` which is really cool but still it has many limitations which we can't deny. So what about a feature like you can select the `codeType` like we can select the command type for example awaitedCommand and so on what about adding a feature for `codeType`. So basically what it does is it defined the file code type whether it's aoi.js or discord.js. It would give us more flexibility to use discord.js command with aoi.js as `$djsEval` has really many limitations due to which we can't actually use pure discord.js for some commands. Also as i know making it would be easier i guess so as you will not need to then pass the code to interpreters and then execute the command. Instead it could be directly executed. I hope it will be added which will really make it much flexible and better to use package. Please think about this feature as i am awaiting about it and has also suggested after long thinking.

**Comment by USERSATOSHI** [comment]
>$djsEval` has really many limitations due to which we can't actually use pure discord.js
@BeastBoyADI it can do js and djs both so I don't see where its lacking

**Comment by USERSATOSHI** [comment]
> No it's still the normal discord.js eval function which limitations like return statement won't work  as it returns illegal return statement also some more stuffs like \`${name}\` doesn't work and if we use \` the code would break which is also a problem in some commands.

u can even make it a Function then use djseval to execute that function

**Comment by BeastBoyADI** [comment]
> > No it's still the normal discord.js eval function which limitations like return statement won't work  as it returns illegal return statement also some more stuffs like `${name}` doesn't work and if we use ` the code would break which is also a problem in some commands.
> 
> u can even make it a Function then use djseval to execute that function

Hmm it's a good thing which i forgot xd

**Comment by USERSATOSHI** [comment]
> Like if u use
> 
> ```js
> $djsEval[let array = ["aoi.js", "leref", "ayaka"];
> array.join("\n");yes]
> ```
> 
> It returns error unexpected token which works in my d.js bot so i guess $djsEval can't do everything which can work by executing js codes directly.

uh ok Lemma explain why 

u see we have code : \`\`

\`\` makes it a string.

now in u know in JavaScript \n is counted as `newline` so uh

for Djseval u are doing

.join("
")
instead of 

.join(" ")


**Solution?**

u can do .join("\\\n") or .join(\`\n\`)

@BeastBoyADI

**Comment by BeastBoyADI** [comment]
Oo tysm

**Comment by USERSATOSHI** [comment]
> Oo tysm
u can also use CustomFunctions to make and then use Functions in ur code like u normally do

**Comment by dbthesecond** [comment]
I tried but the problem was even if i gave correct path of the function it returned cannot find module in node_modules/aoi.js/functions/funcs/djsEval.js

**Comment by USERSATOSHI** [comment]
> I tried but the problem was even if i gave correct path of the function it returned cannot find module in node_modules/aoi.js/functions/funcs/djsEval.js

why are u requiring that function from command directly

in v5 u can do a much better way

do

```js
bot.funcs = {
default = bot.cacheManager.Group()
}

loader.load(bot.funcs,'./functions/')
```

this will load all functions u made inside function folder

then u can do $djsEval[client.funcs.default.find(x => x.name === 'your function name here').code(d)]

**Comment by dbthesecond** [comment]
I use v4
