### ISSUE TITLE
$customReply

### ISSUE THREAD

**Issue by SupernovaBotDeveloper** [aoijs/aoi.js#30]
Hi I'm Spaceflight Gaming,I have a function for aoi.js

Type- Function
$randomReply[Reply1;Reply1;etc]

Description-
This will support Variables,$randomText etc.
This will help making commands like Dank Memer Hunt Command, sometime your Rifle Brokes, sometime you die or you get something,so to make it, you should add $customReply which supports every function

**Comment by USERSATOSHI** [comment]
> Hi I'm Spaceflight Gaming,I have a function for aoi.js
> 
> Type- Function
> $randomReply[Reply1;Reply1;etc]
> 
> Description-
> This will support Variables,$randomText etc.
> This will help making commands like Dank Memer Hunt Command, sometime your Rifle Brokes, sometime you die or you get something,so to make it, you should add $customReply which supports every function

u can Already make this
using $replaceText $randomText or
to make it a chance
$replaceText $checkCondition and $random
