### ISSUE TITLE
Cooldown not worj

### ISSUE THREAD

**Issue by CreamGamer** [aoijs/aoi.js#307]
## Type
- [×] Functions: \<Function Name>
- [ ] Callbacks: \<Callback Name>
- [ ] Handlers: \<Handler Type>
- [ ] Others: \______

Code used:
```
$cooldown[1m;Please wait] 
Your Code Here
```
module.exports = {

name: "ping admin",

code:  `
<@&admin role id>
$cooldown[1m;Please wait] 
`
}
More:
- Aoi.js version: latest @dev ( https://github.com/aoijs/aoi.js#main) 
- Node.js version:nlatest
- Operating system: linux debian 10

Screenshots (If any): Image or Link

**Comment by USERSATOSHI** [comment]
ss?

**Comment by USERSATOSHI** [comment]
working fine for me
![image_2021-11-06_101724](https://user-imag@CreamGamer s.githubusercontent.com/73595362/140598290-86cfc794-139b-4a26-a3cb-a34e26e57e15.png)
@
