### ISSUE TITLE
Hi i have find some bugs :3

### ISSUE THREAD

**Issue by JikaiSH** [aoijs/aoi.js#319]
Hi, i have find some bugs and i giving it beacause i want to developers fix it, there is all errors i have find:

-Get banner function return an error

-bot.onMessageDelete dont work

-Embed error dont work too

-args check function dont work

i have found this^^ your welcome :3

-JikaiSH the best fox <3

Screen: 
Proof for get banner: https://i.imgur.com/19Ew2AZ.png

Proof for bot.onDeleteMessage: https://i.imgur.com/txMaNPG.png

Proof for embed error dont work: https://i.imgur.com/QU5xjMH.png

Proof args check dont work: https://i.imgur.com/uK1LUJM.png https://i.imgur.com/3p1q5V0.png

**Comment by USERSATOSHI** [comment]
> Hi, i have find some bugs and i giving it beacause i want to developers fix it, there is all errors i have find:
> 
> -Get banner function return an error
> 
> -bot.onMessageDelete dont work
> 
> -Embed error dont work too
> 
> -args check function dont work
> 
> i have found this^^ your welcome :3
> 
> -JikaiSH the best fox <3
> 
> Screen: Proof for get banner: https://i.imgur.com/19Ew2AZ.png
> 
> Proof for bot.onDeleteMessage: https://i.imgur.com/txMaNPG.png
> 
> Proof for embed error dont work: https://i.imgur.com/QU5xjMH.png
> 
> Proof args check dont work: https://i.imgur.com/uK1LUJM.png https://i.imgur.com/3p1q5V0.png

@JikaiSH 
first 

the error says u did

useravatar[id here] but where is the $


second is a  bug i fixed it

third embed-errors are changed to support multiple embeds feature

new usage is {newEmbed:{title:hi}} like this

4th one i need ur code to see cause  its working fine

also u need to be on 5.0.2

**Comment by JikaiSH** [comment]
> > Hi, i have find some bugs and i giving it beacause i want to developers fix it, there is all errors i have find:
> > -Get banner function return an error
> > -bot.onMessageDelete dont work
> > -Embed error dont work too
> > -args check function dont work
> > i have found this^^ your welcome :3
> > -JikaiSH the best fox <3
> > Screen: Proof for get banner: https://i.imgur.com/19Ew2AZ.png
> > Proof for bot.onDeleteMessage: https://i.imgur.com/txMaNPG.png
> > Proof for embed error dont work: https://i.imgur.com/QU5xjMH.png
> > Proof args check dont work: https://i.imgur.com/uK1LUJM.png https://i.imgur.com/3p1q5V0.png
> 
> @JikaiSH first
> 
> the error says u did
> 
> useravatar[id here] but where is the $
> 
> second is a bug i fixed it
> 
> third embed-errors are changed to support multiple embeds feature
> 
> new usage is {newEmbed:{title:hi}} like this
> 
> 4th one i need ur code to see cause its working fine
> 
> also u need to be on 5.0.2

hewo^^, im already in 5.0.2 so for the second bug it will be fixed on a other update ?

there is the code: https://i.imgur.com/WSyvgHm.png

i know i dont have put the new embed system but its not the error^^

**Comment by USERSATOSHI** [comment]
> > the error says u did
> > useravatar[id here] but where is the $
> > second is a bug i fixed it
> > third embed-errors are changed to support multiple embeds feature
> > new usage is {newEmbed:{title:hi}} like this
> > 4th one i need ur code to see cause its working fine
> > also u need to be on 5.0.2
> 
> @USERSATOSH
> 
> hewo^^, im already in 5.0.2 so for the second bug it will be fixed on a other update ?
> 
> there is the code: https://i.imgur.com/WSyvgHm.png
> 
> i know i dont have put the new embed system but its not the error^^

ok so i checked the code

u have >2 which means u need to put atleast 3 arguments

**Comment by JikaiSH** [comment]
hooo ok so i need to put >1 ?

**Comment by USERSATOSHI** [comment]
yeah
\

**Comment by JikaiSH** [comment]
oki^^ thx for helping me, and when will you fix the bot.onMessageDelete ?

**Comment by USERSATOSHI** [comment]
fixed for v5.0.3

**Comment by JikaiSH** [comment]
oki thx^^, and im really sorry for disturb you but is as been delete because i was have an error with this and i have check on node_modules and its gone. https://i.imgur.com/KSeGzEc.png

**Comment by JikaiSH** [comment]
@USERSATOSHI

**Comment by USERSATOSHI** [comment]
> oki thx^^, and im really sorry for disturb you but is messageSlice as been delete because i was have an error with this and i have check on node_modules and its gone. https://i.imgur.com/KSeGzEc.png

use
$messageSlice[1;$argsCount]

**Comment by JikaiSH** [comment]
oki thx <3
