### ISSUE TITLE
Bot dont work after doing 1 command

### ISSUE THREAD

**Issue by JikaiSH** [aoijs/aoi.js#323]
Hewwwo when i put the new 5.0.3 version the bot work for 1 command i do and after PUF bot dont work...
I have put the old version 5.0.2 and it work correctly._.

**Comment by USERSATOSHI** [comment]
check console

**Comment by JikaiSH** [comment]
@USERSATOSHI console just say the bot is online 0 error

**Comment by JikaiSH** [comment]
I know the problem its the $alwaysExecute Function make my bot not responding after doing 1 command. so you have a new bug to fix^^ @USERSATOSHI

**Comment by JikaiSH** [comment]
Ho nooo its not this...

```
 //if antilink is on v2
  bot.command({
  name: "$alwaysExecute",
  code: 
  `
  <@$authorID> Tu ne peut pas envoyer de liens dans \`$serverName\` Raison: **Antilink Activé**
  
  $deletecommand
  
  $onlyIf[$getServerVar[antilink]==true;]
  $onlyIfMessageContains[$message;https://discord.gg;]
  $blackList[role;904320788704931841;904320750478065724;904320787924787260;904320735126900836;904320777795555368;904320784053436426;904320781666906162;904320779666219048;]  $blackList[globalUser;904122169078980638;$ownerID;]
  `
  })
```

this is the blacklist function he block the bot to respond beacause i have say the owner is blacklist ;-;
