### ISSUE TITLE
dbdjs.mongo set and get dont work for socket.io while making dashboard and 

### ISSUE THREAD

**Issue by LegacyDeveloper** [aoijs/aoi.js#331]
hi! so im making a bot dashboard rn and i have mongo for my bot as a database, and it works, but now i decided to make a bot dashboard, and as aoojs cant work like djs does, i decided to use a database connection instead of djs to setup my vars trought dashboard, so no errors but it just dont set and dont get, i used this:

dbdmongo.set('main', 'prefix', newData)
i defined newData and it works for djs but not for database, for get:
dbdmongo.get('main', 'prefix')

please fix this because all my data is stored in mongo and no other database uses aoijs and is better than mongo.

**Comment by ytmnsa** [comment]
Hi I work at mongoDB, 
first of all, it's good to have a customer like you! thanks for using mongoDB!!

now for your problem, maybe because dbdjs.mongo set and get dont work for socket.io.
message me if you need anything my discord is Moayyed#7444

**Comment by USERSATOSHI** [comment]
> hi! so im making a bot dashboard rn and i have mongo for my bot as a database, and it works, but now i decided to make a bot dashboard, and as aoojs cant work like djs does, i decided to use a database connection instead of djs to setup my vars trought dashboard, so no errors but it just dont set and dont get, i used this:
> 
> dbdmongo.set('main', 'prefix', newData) i defined newData and it works for djs but not for database, for get: dbdmongo.get('main', 'prefix')
> 
> please fix this because all my data is stored in mongo and no other database uses aoijs and is better than mongo.

aoijs' client.db works differently

its not same as the original dbdjsmongo usage

because its generalised.

@LegacyDeveloper

**Comment by USERSATOSHI** [comment]
> Hi I work at mongoDB, first of all, it's good to have a customer like you! thanks for using mongoDB!!
> 
> now for your problem, maybe because dbdjs.mongo set and get dont work for socket.io. message me if you need anything my discord is

what i think is that he used aoijs client.db and because db methods are heavily changed to support generalisation 
the original method will give error because it is totally different

**Comment by LegacyDeveloper** [comment]
no i didnt

**Comment by jisachao** [comment]
![image](https://user-images.githubusercontent.com/58595500/145170808-5b336f0c-feb0-45b4-9733-9a3be35ead2a.png)
Idk why I am getting this error 

this is my main code ( in index.js ) 

```
const mongoose = require('mongoose')
const dbdmongo = require('dbdjs.mongo').default
const mongoURL = "mongodb+srv://jisa:jisalovesisabella@cluster0.smwhi.mongodb.net/myFirstDatabase?retryWrites=true&w=majority"
mongoose.connect(mongoURL, {
  useNewUrlParser: true,
  useUnifiedTopology: true,
  useFindAndModify: true,
  keepAlive: true
})

```
```

const bot = new aoijs.Bot({
token: token, //Discord Bot Token
prefix: prefix, //Discord Bot Prefix
mobile: true, 
intents : ['guilds','guildMessages','guildMembers'],
database : {
type : "dbdjs.mongo",
db : require('dbdjs.mongo'),
tables : ['main'],
},
})

```

it says `useFindAndModify` is not supported , when i remove it, the code runs but then stops and shows this error 
![image](https://user-images.githubusercontent.com/58595500/145171387-e33b005a-c347-45d9-8a5b-b8b1a9af16ae.png)

**Comment by USERSATOSHI** [comment]
> ![image](https://user-images.githubusercontent.com/58595500/145170808-5b336f0c-feb0-45b4-9733-9a3be35ead2a.png)
> Idk why I am getting this error 
> 
> this is my main code ( in index.js ) 
> 
> ```
> const mongoose = require('mongoose')
> const dbdmongo = require('dbdjs.mongo').default
> const mongoURL = "mongodb+srv://xxx:xxx@cluster0.smwhi.mongodb.net/myFirstDatabase?retryWrites=true&w=majority"
> mongoose.connect(mongoURL, {
>   useNewUrlParser: true,
>   useUnifiedTopology: true,
>   useFindAndModify: true,
>   keepAlive: true
> })
> 
> ```
> ```
> 
> const bot = new aoijs.Bot({
> token: token, //Discord Bot Token
> prefix: prefix, //Discord Bot Prefix
> mobile: true, 
> intents : ['guilds','guildMessages','guildMembers'],
> database : {
> type : "dbdjs.mongo",
> db : require('dbdjs.mongo'),
> tables : ['main'],
> },
> })
> 
> ```
> 
> it says `useFindAndModify` is not supported , when i remove it, the code runs but then stops and shows this error 
> ![image](https://user-images.githubusercontent.com/58595500/145171387-e33b005a-c347-45d9-8a5b-b8b1a9af16ae.png)
> 

@jisachao because latest mongoose doesn't support `useFindAndModify`

**Comment by jisachao** [comment]
@USERSATOSHI then why is it showing an error when i remove it?

**Comment by USERSATOSHI** [comment]
u have to use 
legacy version of mongoose

**Comment by jisachao** [comment]
what's the version code of legacy version? like : 
![image](https://user-images.githubusercontent.com/58595500/145330800-88e354f9-d6d4-4b11-aef2-882e0359ced5.png)

**Comment by LegacyDeveloper** [comment]
> what's the version code of legacy version? like : ![image](https://user-images.githubusercontent.com/58595500/145330800-88e354f9-d6d4-4b11-aef2-882e0359ced5.png)

use v5.13.9

**Comment by jisachao** [comment]
![image](https://user-images.githubusercontent.com/58595500/145506662-aaec89f6-b51c-4c3a-ad85-ef5111675406.png)
still shows error ;-;

**Comment by USERSATOSHI** [comment]
closed due to inactivity
