### ISSUE TITLE
Weird error rooted in the package

### ISSUE THREAD

**Issue by TecDeveloper** [aoijs/aoi.js#339]
## Type
- [ ] Functions: \<Function Name>
- [ ] Callbacks: \<Callback Name>
- [ ] Handlers: \<Handler Type>
- [x] Others: The example code itself.

Code used:
```
const aoijs = require("aoi.js")

const bot = new aoijs.Bot({
token: process.env.TOKEN,
prefix: "."
})
```

More:
- Aoi.js version: 5.0.6
- Node.js version: 12.22.6
- Operating system: Docker

Screenshots (If any): 
![C7389A67-0BCD-47DF-91A5-455BA6475957](https://user-images.githubusercontent.com/67659592/147411983-a6499a1c-ee64-4b50-bc1b-bd940208356e.jpeg)

## My Own Note
I have not used Aoi.js for a while after it was switched from dbd.js, but when I try the example code given in the official packages [readme](https://npmjs.com/package/aoi.js), I encounter with this error. What is the cause of this problem? (It comes from node_modules so probably it is a bug.)

**Comment by Leref** [comment]
nodejs 16.6.0 and above is required.

**Comment by TecDeveloper** [comment]
Thanks for the quick fix

**Comment by TecDeveloper** [comment]
Nope, didn't fix. Upgraded to 17.2.0 (latest), same problem still.

**Comment by Leref** [comment]
Whatever you're using to Host your Bot, isn't using nodejs 16.6.0 and above.
Verify you've updated the nodejs correctly.
Based upon your screenshot it's using Replit, which doesn't have nodejs 16.6.0 by default.

**Comment by Juhan280** [comment]
> Nope, didn't fix. Upgraded to 17.2.0 (latest), same problem still.

What error do you get now? Show an screenshot. If it is same error, it means nodejs version isn't >=16.6.x

**Comment by USERSATOSHI** [comment]
> Nope, didn't fix. Upgraded to 17.2.0 (latest), same problem still.

@TecDeveloper did u install node
if yes
thats not nodejs
so it wont work

**Comment by TecDeveloper** [comment]
Sorry for the inconvenience, fixed it myself after some geeking. For reference, you MUST do this to avoid any issues in Replit:

1. Create .replit file

2. Paste the code below

>! `run = """
npm init -y && npm i --save-dev node@17.2.0 && npm config set prefix=$(pwd)/node_modules/node && export PATH=$(pwd)/node_modules/node/bin:$PATH
node index.js
"""`

It should work now. Unless you do this, replit will rollback to 12.22.6 every time you open it.
