### ISSUE TITLE
Fix $randomEmoji

### ISSUE THREAD

**Issue by berat141** [aoijs/aoi.js#34]
## Type
- [x ] Functions: $randomEmoji
- [ ] Callbacks: 
- [ ] Handlers: 
- [ ] Others:

Code used:
![84E09B8C-DEF2-4D4B-A663-4DC38D873E31](https://user-images.githubusercontent.com/79844920/116779286-192e5480-aa7e-11eb-9295-0903193e957d.jpeg)
![DA17922E-C8F1-40F8-BB74-F22C5350BD38](https://user-images.githubusercontent.com/79844920/116779283-15023700-aa7e-11eb-8cc2-1c4fe5ad21cc.png)

Your Code Here
d!eval $randomEmoji (this is how i used it)

More:
- Aoi.js version:
- Node.js version:
- Operating system:

Screenshots (If any): Image or Link

**Comment by XzFirzal** [comment]
https://github.com/aoijs/aoi.js/commit/1e5469d2533bf02d38cb612b1ea6c958af904f32
