### ISSUE TITLE
Added $setNsfwChannel

### ISSUE THREAD

**Issue by BranGamer145** [aoijs/aoi.js#35]
## Type
- [ ] Functions: $setNsfwChannel

## Description
Please add $setNsfwChannel That's very helpful :'-!

**Comment by berat141** [comment]
$editChannel exists ?

**Comment by BranGamer145** [comment]
> $editChannel exists ?

hmmm It looks like no :\

**Comment by USERSATOSHI** [comment]
> > $editChannel exists ?
> 
> hmmm It looks like no :\

it exist :/
![Uploading Screenshot_2021-05-01-17-18-02-81.png…]()

**Comment by BranGamer145** [comment]
> > > $editChannel exists ?
> > 
> > 
> > hmmm It looks like no :\
> 
> it exist :/
> ![Screenshot_2021-05-01-17-18-02-81](https://user-images.githubusercontent.com/73595362/116781578-5e17b280-aaa1-11eb-8609-eb7e61a2629a.png

What is the example like?

**Comment by Kino7916** [comment]
No need for function since $editChannel already provided.
