### ISSUE TITLE
$skipTo not working?

### ISSUE THREAD

**Issue by Alconera130** [aoijs/aoi.js#36]
![Screenshot_2021-05-01-19-13-14-44](https://user-images.githubusercontent.com/83458587/116781135-9b853b80-aab3-11eb-9f5e-7d17a3b1e278.jpg)

**Comment by USERSATOSHI** [comment]
ok lemma check it

**Comment by USERSATOSHI** [comment]
@Alconera130 what version are you on?

**Comment by Alconera130** [comment]
latest (1.0.1)

**Comment by Alconera130** [comment]
just noticed that $suppressErrors doesnt suppress it, lemme just take a look if im mistaken

**Comment by Kino7916** [comment]
New commit should fix the problem
