### ISSUE TITLE
aoi.ts when

### ISSUE THREAD

**Issue by Weredok** [aoijs/aoi.js#371]
library writted on typescript, why .js?

**Comment by USERSATOSHI** [comment]
> library writted on typescript, why .js?

uh because u still have to  transpile ur ts code to js to execute it?

**Comment by USERSATOSHI** [comment]
plus not like u cant use a js package in ts

so if u want to use ts then use it

**Comment by Weredok** [comment]
> plus not like u cant use a js package in ts
> 
> so if u want to use ts then use it

im just talking the pkg name. are leref planning to change this?

**Comment by Leref** [comment]
no.
