### ISSUE TITLE
nodejs 16 needed.

### ISSUE THREAD

**Issue by Spyei** [aoijs/aoi.js#380]
error on glitch.com
![eror](https://user-images.githubusercontent.com/105593678/174445004-e2458677-ede6-42e4-b650-beee366d9b3d.png)

![error2](https://user-images.githubusercontent.com/105593678/174445013-b7ba408f-5be6-47ff-9709-1b691be2e863.png)

**Comment by USERSATOSHI** [comment]
> 

you need nodejs v16.9.0 for aoijs to work

**Comment by Leref** [comment]
Even the latest v5.2.0 now prompts a new error throw to use nodejs 16.6+
