### ISSUE TITLE
A few properties don't work on $user function.

### ISSUE THREAD

**Issue by Neodevils** [aoijs/aoi.js#383]
https://github.com/AkaruiDevelopment/aoi.js/blob/0d94fbe6dfe95be1b2e176e27f6be91c01338e11/src/utils/helpers/functions.js#L298

**Comment by Neodevils** [comment]
As far as I have seen, those properties don't work;
- accentColor
- banner
- bannerURL
- createdAt
- dmChannel.

**Comment by USERSATOSHI** [comment]
they are working

accentColor wont return anything if user uses default 
banner needs nitro 
createdAt works
dmChannel needs a dm before to get it

**Comment by Neodevils** [comment]
Problems solved.
