### ISSUE TITLE
$newState and $oldState issues

### ISSUE THREAD

**Issue by scriptyyy13** [aoijs/aoi.js#391]
Example code used:
```
{
    type: "voiceStateUpdate",
    $if : 'v4',
    channel: '998943588547305542',
    code: `
joined
$onlyIf[$newState[channelID]!=;2]
$onlyIf[$oldState[channelID]==;1]`
}
```

The unexpected error message or issue: 
```
this code returns: 2, when the user joins the voice channel.
```

Information:
- aoi.js version: 5.5.0
- node.js version: 17.1.0
- Operating system: linux

**Comment by USERSATOSHI** [comment]
the option is `channelId` 
and options are case sensitive

**Comment by scriptyyy13** [comment]
> the option is `channelId` 
> and options are case sensitive

$channelID return channel where logs have been sent.

**Comment by USERSATOSHI** [comment]
> > the option is `channelId`
> > and options are case sensitive
> 
> $channelID return channel where logs have been sent.

yes and that's intentional 
so not a bug 👍

**Comment by Leref** [comment]
Resolved.
