### ISSUE TITLE
$serverMFALevel "undefined" issue

### ISSUE THREAD

**Issue by Neodevils** [aoijs/aoi.js#393]
## Type
- [x] Functions: $serverMFALevel

Example code used:
```
$serverMFALevel[$guildID]
```

The unexpected error message or issue: 
```
undefined
```

Information:
- aoi.js version: v5.5.5
- node.js version: v17+

**Comment by Leref** [comment]
v5 will no longer receive updates, due to v6.0.0 being worked on.
Within less than a month, it should be released.
