### ISSUE TITLE
$checkcondition in $alwaysexecute

### ISSUE THREAD

**Issue by yasn1** [aoijs/aoi.js#395]
All my $alwaysexecute commands had the $checkcondition code. But if something like $onlyif[$message==abc;] happens and someone sends "\" the botbot is spamming the error.

![IMG_20220725_234706](https://user-images.githubusercontent.com/71357231/180874160-b486b263-6c1c-4301-85d0-d17b25f79fa5.jpg)

**Comment by Kee7702** [comment]
Looking over documentation, I found [$suppressErrors](https://aoi.js.org/docs/functions/suppresserrors). This isn't the best solution and will still execute the command, but it should prevent the error from showing. If you might want a different solution, you can try [$uri](https://aoi.js.org/docs/functions/uri/) and encode the message, though I'm not certain it'll fix that specific error (untested)

**Comment by Leref** [comment]
No changes.
