### ISSUE TITLE
onlyGuild: false

### ISSUE THREAD

**Issue by sr-star-trek** [aoijs/aoi.js#398]
## Type
- [ ] Functions: \<Function Name>
- [ ] Callbacks: \<Callback Name>
- [ ] Handlers: \<Handler Type>
- [x] Others: \______

Example code used: MD commands
```
Your code here
onlyGuild: false
```

The unexpected error message or issue: No working
```
Your error message here
Does not work onlyGuild: false
```

Information:
- aoi.js version: 5.5.5
- node.js version: 18
- Operating system: Android

Screenshots (If any):  
![IMG_20220729_105808](https://user-images.githubusercontent.com/58307892/181732096-93ff387c-99ab-4f4b-897a-ef35a9957d0c.jpg)
![Screenshot_2022-07-29-10-58-16-612_com discord](https://user-images.githubusercontent.com/58307892/181732132-4a636bf7-d928-4365-b2b0-b97c013233b2.jpg)
![Screenshot_2022-07-29-11-09-27-003_com android chrome](https://user-images.githubusercontent.com/58307892/181732169-99a7f4f8-10fa-4555-a8f7-39f070869ece.jpg)

**Comment by USERSATOSHI** [comment]
u need to add 

executeAt : "dm" 

to make that cmd dm only

"both" for guild + dm

**Comment by USERSATOSHI** [comment]
default is "guild" for guild Only

**Comment by sr-star-trek** [comment]
> u need to add
> 
> executeAt : "dm"
> 
> to make that cmd dm only
> 
> "both" for guild + dm

No working

**Comment by USERSATOSHI** [comment]
send the  command

**Comment by Kee7702** [comment]
If it didn't work, I assume you may have misread the message and may have done something like this:
```
bot.onMessage({
  guildOnly: false,
  executeAt: "dm"
})
```
when it is intended to be included in the `bot.command()` function. If you did it like the code below, you can try appending `DIRECT_MESSAGES` to the list of intents. I noticed that it's been about a week so I figured I'd comment to hopefully save time for everyone.
```
bot.command({
  executeAt: "dm",
  name: "message",
  code: `$message`
});
```
@sl1pUK

**Comment by Leref** [comment]
No changes, closing issue.
