### ISSUE TITLE
$loopMode

### ISSUE THREAD

**Issue by TioSilvaa** [aoijs/aoi.js#399]
## Type
- [ ] Functions: $loopMode[queue]
- [ ] Handlers: \<Handler Type>
- [ ] Others: \______

Example code used:

$loopMode[queue]
$wait[5s]
$playTrack[platform;any song/playlist]
```

The unexpected error message or issue: 
```
crashing the entire music system, causing the bot to exit the call. 

plays between 60 songs at most, and then leaves all the calls. 

[does not turn off the bot, only the music functions that stop]

(already checked, and yes $loopMode is the problem)
```


Information:
- aoi.js version: 5.5.5
- node.js version: 17.2

Screenshots (If any): no error message, it just crashes and exits

**Comment by USERSATOSHI** [comment]
send the full console error

cause no crash error were provided 

nor any failed js error log has been provided

if it crashes

send that crash error

**Comment by USERSATOSHI** [comment]
and the unexpected error message is not explaining anything

**Comment by USERSATOSHI** [comment]
also tested it rn , no crash error and the music is working fine
![image](https://user-images.githubusercontent.com/73595362/182901939-7cca81b8-4f61-40df-a6e9-8cd6e18e7ce1.png)

**Comment by TioSilvaa** [comment]
again. No error message appears, either on the panel or on discord. I spent hours watching this.

The bot PLAYS some songs for up to hours, then crashes. please read!

→ HAS NO MESSAGE, DOES NOT APPEAR 
→ I TESTED
→ USING DAYS TO SEE.

I disabled the function, and the bot plays music normally for hours and even days, strange

👍❤️

**Comment by USERSATOSHI** [comment]
![image](https://user-images.githubusercontent.com/73595362/182902617-d068f87e-2519-47e7-aae0-468b2c57ba68.png)
just replying to this
u worded it as crash 
and crash ALWAYS sends an error message

**Comment by TioSilvaa** [comment]
**if it's going to be of any help...**
![errorone](https://user-images.githubusercontent.com/68887608/182904011-384e9d41-1035-4fed-baed-be7ec8c9adfb.png)

and :

- image[0].url not found ?
- URL 403

only errors that appear visibly!

→ counting: 1d 5h playing music WITHOUT $LOOPMODE FUNCTION (repeatedly adding the same music)
→ counting 6h with active $loopMode (with the same songs )

if it's crashing, it is. because it leaves the call on all servers !

**Comment by TioSilvaa** [comment]
![Screenshot_20220804-134342-090](https://user-images.githubusercontent.com/68887608/182905557-62c22cc8-8c27-4b27-abdb-aa12ad9bfdcf.png)
![Screenshot_20220804-134406-449](https://user-images.githubusercontent.com/68887608/182905565-bc394509-e63c-4448-bad0-43905d2fc69d.png)

703 songs played so far, without going out alone.


using $loopMode, this doesn't play 70 songs.
🤗

**Comment by USERSATOSHI** [comment]
do u have memory cache enabled

**Comment by TioSilvaa** [comment]
my lord christ. 😴

if you read well what I wrote, you will see that I said that I tested it in every way for hours and hours.

**Comment by USERSATOSHI** [comment]
> my lord christ. 😴
> 
> if you read well what I wrote, you will see that I said that I tested it in every way for hours and hours.

u do know that loop on cache saves everything to memory 
hence i asked did u enable caching or not

**Comment by TioSilvaa** [comment]
test

**Comment by TioSilvaa** [comment]
active cache: crashing
cache disabled: crashing
disk cache: crashing
Memory cache: crashing

$loopMode off: working perfectly 
$loopMode on: bot exiting all calls

**Comment by USERSATOSHI** [comment]
> **if it's going to be of any help...** ![errorone](https://user-images.githubusercontent.com/68887608/182904011-384e9d41-1035-4fed-baed-be7ec8c9adfb.png)
> 
> and :
> 
> * image[0].url not found ?
> * URL 403
> 
> only errors that appear visibly!
> 
> → counting: 1d 5h playing music WITHOUT $LOOPMODE FUNCTION (repeatedly adding the same music) → counting 6h with active $loopMode (with the same songs )
> 
> if it's crashing, it is. because it leaves the call on all servers !

![image](https://user-images.githubusercontent.com/73595362/182910474-c1757172-703d-4ae6-b2e7-f19f3e3d83f0.png)
this was the breaking error....

**Comment by USERSATOSHI** [comment]
but it's more of aoi.music issue than aoi.js
so wait for v2 rewrite ig

**Comment by TioSilvaa** [comment]
to avoid the image[0].url error, I am using replaceText

**Comment by USERSATOSHI** [comment]
like i said this is more related to aoi.music than aoi.js 
so wait for aoi.music v2 rewrite
