### ISSUE TITLE
$sendMessage is bugged

### ISSUE THREAD

**Issue by Just-Mohamed** [aoijs/aoi.js#40]
$sendMessage has two fields but the second one is optional right? 
It gave this error in the photo for some reason
![Screenshot_20210501-132154](https://user-images.githubusercontent.com/60315196/116781655-9d83d600-aa84-11eb-96fa-a43851e06302.png)

**Comment by USERSATOSHI** [comment]
> $sendMessage has two fields but the second one is optional right?
> It gave this error in the photo for some reason
> ![Screenshot_20210501-132154](https://user-images.githubusercontent.com/60315196/116781655-9d83d600-aa84-11eb-96fa-a43851e06302.png)

Second one is not optional
