### ISSUE TITLE
$onResourceUpdate

### ISSUE THREAD

**Issue by Kee7702** [aoijs/aoi.js#400]
## Type
- [x] Functions: $onResourceUpdate[channelID;channelID;...;api;interval;retry?;save?]
- [ ] Callbacks: \<Callback Name>
- [ ] Handlers: \<Handler Type>
- [ ] Others: \______

## Description
This function would essentially attempt to fetch a JSON api and would execute the code when the response is changed from the last known cached response. Below is a table describing the specifications of the parameters specified above, as well as a potential usage of this function in code.

Practicality of this function:
You could use this to fetch changes with the default Uploads playlist created by YouTube for every channel and then take the JSON response data and use it with `$jsonRequest` to create video upload notifications in a Discord server

| Field | Description | Type | Required |
| - | - | - | - |
| channelID | A channel ID or list of channel IDs separated by `;` which the command will output into | channelID | yes |
| api | The api from which the specified response is to be retrieved | link | yes |
| interval | The wait time in minutes before checking resource again | number | yes |
| retry | If response is different from cache, fetch again a set count of times before running code | number | no |
| save | Store cached response in the event of bot outages | boolean | no |
```js
//Will check the commits for this repository, and when updated it will try 3 times in intervals of 2 minutes before sending 'Repository updated!' in channel 1005053608666079313.
//This specific code would be around 6-8 minutes delayed from the live repository.
bot.command({
  name: "$onResourceUpdate[1005053608666079313;https://api.github.com/repos/AkaruiDevelopment/aoi.js/commits;2;3]",
  code: `Repository updated!`
});
```

**Comment by USERSATOSHI** [comment]
already doable with loopCommand and cache functions

**Comment by Leref** [comment]
Solved.
