### ISSUE TITLE
Priority to $onlyIf

### ISSUE THREAD

**Issue by Aashik-001** [aoijs/aoi.js#402]
The Code:
  
{
    name: "ty ?cancle",
    category: "TOURNEY",
    description: "CANCLE A USER'S REGISTRATION.",
    usage: "?ty ?cancle <REGISTRATION MESSAGE IN-REFERENCE",
    example: "NA",
    note: "NA",
    preview: "NA",
    $if: "v4",
    code: `
    
	$if[$messageExists[$advancedTextSplit[$getUserVar[$getServerVar[$getChannelVar[TyGroupID;$channelID]];$getMessage[$channelID;$referenceMessageID;userID]];_;3];$getChannelVar[TourneyCT;$channelID]]==true]
	$editMessage[$get[CT];Your slot is cancelled;$get[CTC]]

    
    $else
    $endif
    $onlyIf[$referenceMessageID!=;Error]
    $onlyIf[$getChannelVar[TyGroupID;$channelID]!=;{newEmbed:{author:COULDN'T PROCESS YOUR REQUEST}{title:THIS CHANNEL DOESN'T SUPPORTS TRACKING}{footer:$toUppercase[$UserName[$clientID]]}{color:RED}}]
    

    
    `
},
    
Issue:
$onlyIf returns it's error message but $if block still checks it's statement and return an extra error.

Information:
- aoi.js version: 5.5.5

Screenshots (If any): Image or Link
https://media.discordapp.net/attachments/944097051665387541/1006820106594172958/1660115015010.png

**Comment by USERSATOSHI** [comment]
response in #405
