### ISSUE TITLE
Let us use $get inside $if block in $if: "V4"

### ISSUE THREAD

**Issue by Aashik-001** [aoijs/aoi.js#403]

**Comment by Neodevils** [comment]
What's difference between $let and $var then?

**Comment by USERSATOSHI** [comment]
v4 $if design doesnt allow it
just use v5 $if for that

**Comment by Aashik-001** [comment]
v5 if doesn't allows other functions in true/false field

**Comment by USERSATOSHI** [comment]
dont use v5 if like v4 if
```php
$if[1==1]
$sendMessage[hi]
$else
$sendMEssage[bye]
$endif
```
can be converted to
```php
$sendMessage[$if[1==1;hi;bye]]
```

**Comment by Aashik-001** [comment]
What about this?
$if[1==1]
$sendMessage[poor guy;no]
$setUserVar[iq;1]
$else
$sendMessage[free;no]
$setUserVar[iq;undefined]
$endif

**Comment by USERSATOSHI** [comment]
```php
$sendMessage[$if[1==1;poor guy;free];no]
$setUserVar[iq;$if[1==1;1;undefined]]
```

**Comment by Leref** [comment]
Resolved.
