### ISSUE TITLE
$edinChannel Dosent works

### ISSUE THREAD

**Issue by scriptyyy13** [aoijs/aoi.js#404]
$editChannel dosent works on voice channels.

i run `$editChannel[$voiceID;$default;$default;$default;$default;$default;1;no]`

and this do nothing.

pls fix this

**Comment by USERSATOSHI** [comment]
well u cant set bitrate of a channel to 1 so it wont do anything
plus u are setting userLimit to `no` which is also wrong

**Comment by scriptyyy13** [comment]
> well u cant set bitrate of a channel to 1 so it wont do anything
> plus u are setting userLimit to `no` which is also wrong

i used `$editChannel[$voiceID;$default;$default;$default;$default;$default;$default;1]`  and nothing had happened

**Comment by USERSATOSHI** [comment]
what are u trying to do

**Comment by scriptyyy13** [comment]
> what are u trying to do

i am trying to set limit of users in voice channel

**Comment by USERSATOSHI** [comment]
if u only want that then just do
```php
$editChannel[$voiceId;{
  "userLimit" : 1 
  }]
  ```

**Comment by scriptyyy13** [comment]
and how to rename channel?

use this: `$editChannel[$voiceId;{
  "name" : "name lol"
  }]` ?
