### ISSUE TITLE
Why Executing (checking) condition inside $if when $onlyIf denies the execution of whole code?

### ISSUE THREAD

**Issue by Aashik-001** [aoijs/aoi.js#405]

**Comment by USERSATOSHI** [comment]
because v4 $if's conditions executes before any function in your code

**Comment by Aashik-001** [comment]
This doesn't helps in any way

**Comment by USERSATOSHI** [comment]
> This doesn't helps in any way

it does
thats how u are able to use functions in v4 if

**Comment by USERSATOSHI** [comment]
its basically

$if[1==1]
hi
$else
bye
$endif

first v4 if executes and check each condition then replace 
whole
```
$if[.....]
.....
$endif
some other code here
```
with the true condition's code

so the code becomes
```
hi
some other code here
```

thats how it works

**Comment by Aashik-001** [comment]
Is there any way to avoid it? Without using V5 if coz it doesn't supports functions inside it.

**Comment by USERSATOSHI** [comment]
then dont use $get

plus ur v4 if can easily be converted to v5 if

**Comment by USERSATOSHI** [comment]
cause 90% of v4 if code are convertable to v5 if code

**Comment by Leref** [comment]
Solved.
