### ISSUE TITLE
Docs client status in v6 is wrong

### ISSUE THREAD

**Issue by Aluwi21** [aoijs/aoi.js#406]
Check the [v6 Docs](https://aoi.js.org/docs/6.0.0/guides/client-status)

**Comment by USERSATOSHI** [comment]
what exactly is wrong

**Comment by Aluwi21** [comment]
> what exactly is wrong

Is in the script
`bot.status.add({
    name: "Client Status Messagw",
    duration: 12000`
Where the `})` and the typo?

**Comment by USERSATOSHI** [comment]
you were supposed to make the issue in documentation repo 

but ok

**Comment by Leref** [comment]
Issue has been solved and report this onto documentation repository.
