### ISSUE TITLE
Bug: song info

### ISSUE THREAD

**Issue by Mrshord** [aoijs/aoi.js#409]
### Bug Type

Function

### Bugged function

```js
$songinfo[userID]
```

### Version of aoi.js

v5.5.5 (Default)

### Version of Node.js

v16.6.0

### Excepted Output

In $songinfo[userID] 
Unidentified

### Relevant log output

```shell
No log
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by USERSATOSHI** [comment]
user.id

**Comment by Leref** [comment]
Resolved.
