### ISSUE TITLE
Add scheduled event functions

### ISSUE THREAD

**Issue by Weredok** [aoijs/aoi.js#410]
### Featuring Type

Function

### So, what is it about?

Add scheduled event functions. For example: 
`$createEvent[guildID;title;description;location type (stage, voice or other);location (id or text);start;end;returnId]` - creating scheduled event on guild
`$modifyEvent[eventID;option;new value]` -  editing scheduled event with options
`$deleteEvent[eventID;reason]` - deleting scheduled event
`$startEvent[eventID;notify  everyone]` - start scheduled event 
`$endEvent[eventID;reason]` - end scheduled event
`$eventInfo[eventID;option]` - get event info with options
`$createEventInvite[eventID;duration]` - creating invite for event
`$getEventID[event name]` - returning event id with name

Discord.js have this functions: https://discord.js.org/#/docs/discord.js/main/class/GuildScheduledEvent

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Leref** [comment]
v5 will no longer be receiving updates, but this can be some functions added onto the next version. (6.0.0)

**Comment by Leref** [comment]
Has been added in next update.
