### ISSUE TITLE
Modifying and editing types

### ISSUE THREAD

**Issue by Weredok** [aoijs/aoi.js#412]
### Featuring Type

Others

### So, what is it about?

To make the code cleaner , add a new editing and modifying ways. For example:
`$editChannel[channelId;name;topic;limit;bitrait;position;rawPoisition;parentId]` - A **editing channel**
`$modifyChannel[channelId;option;new option value]` -  A **modifying an option in channel**

Then if i need change channel `position` i dont need use $editChannel, i just use `$modifyChannel[$channelId;position;0]`. 
I suggest this not only for editing channels, but also for roles, guilds, threads and events .

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Neodevils** [comment]
You can make it with JSON parser. It allows you to access any *channel* options.

**Comment by Leref** [comment]
It doesn't sound ethical for two functions, same purpose when both can do one as a whole.
