### ISSUE TITLE
$varExists

### ISSUE THREAD

**Issue by Modyes** [aoijs/aoi.js#413]
### Featuring Type

Function

### So, what is it about?

Checks if the variable exists on the client and returns boolean(true/false)
example: $varExists[smthidkidjdidj]
bot: false (as it doesn't exist)
and if it exists "true"
I know it's easy to do using $djsEval but if there's $createVar and $deleteVar why not $varExists

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by Bumblebee-3** [comment]
Hey, @Mody-0 , as you already know, aoi.js v5 will not be getting updated further. So, here is a simple method in which you could solve your problem with aoi's custom functions feature.

```javascript

bot.functionManager.createCustomFunction({
  name: "$varExists",
  type: "djs",
  code: async d => {
        
  const data = d.util.openFunc(d);
  const [varName] = data.inside.splits;
  var b = await d.client.variableManager.cache.get(varName);
  if (b != undefined){
    data.result= true;
  }
  else{
    data.result= false;
  }
    
  return {
    code: d.util.setCode(data)
  }}
})
```

Hope this helps!
