### ISSUE TITLE
respondToBots per command

### ISSUE THREAD

**Issue by Modyes** [aoijs/aoi.js#414]
### Featuring Type

Others

### So, what is it about?

I saw that respondToBots can be added only on <client>.onMessage({}) and that would enable/disable responding to bots for all commands but how about changing that to be per command, so that we can enable or disable respondToBots for one specific command and of course it should be disabled by default for all commands, why? because sometimes people like me would want to enable 1 specific command to respond to bots and keep the others disabled, I mean we can actually do it using onlyifs but then we will have to go over all the commands to disable them from responding to bots and some users like me who already have like 150+ commands cannot just do that, we can but it's a real pain, so yeah.. respondToBots per command would be a great addition to aoi.js.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Neodevils** [comment]
👍🏻

**Comment by ElTuna** [comment]
Funny fact... You could have edited your +150 commands while this thread was pending and you would have already finished xdxd

**Comment by Leref** [comment]
Not sure at the moment, but it's entirely meant to be enabled or not, and using condition statement.
