### ISSUE TITLE
Bug: Issues with $createObject while parsing a JSON object.

### ISSUE THREAD

**Issue by obscuremusic** [aoijs/aoi.js#415]
### Bug Type

Function

### Bugged function

```js
$getObject

$createObject[{
  "operationName": "getRandomPluginsBySection",
  "variables": {
    "section": "instruments",
    "OSFilterOpts": [
      "win32",
      "win64",
      "allmacos",
      "linux"
    ]
  },
  "query": "query getRandomPluginsBySection($section: String!, $OSFilterOpts: [String]!) {\n  getRandomPluginsBySection(section: $section, OSFilterOpts: $OSFilterOpts) {\n    pluginID\n    fx_cat\n    fx\n    name\n    text\n    dev\n    win32\n    win64\n    winaax\n    osx\n    os9\n    macaax\n    vst\n    linux\n    macau\n    macrtas\n    img\n    rate\n    __typename\n  }\n}\n"
}]
```

### Version of aoi.js

v5.5.5 (Default)

### Version of Node.js

v16.16.0 (LTS)

### Excepted Output

I want to use the object as the body of an HTTP request, however the aforementioned code throws an error.

### Relevant log output

```shell
AoiError: $createObject: Failed To Create Object With Reason: SyntaxError: Unexpected token 
 in JSON at position 282  
 { 
   lineNumber : 44,
   line : `undefined`,
   path : "undefined" 
 }
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by USERSATOSHI** [comment]
what this in cmd or eval?

**Comment by lethiferal** [comment]
> what this in cmd or eval?
> 

It's a command.

**Comment by USERSATOSHI** [comment]
> > what this in cmd or eval?
> > 
> 
> It's a command.

ah then for cmd u need to escape new line (\n) 

because if you don't do that ,

then \n will be counted by the string in which ur code is

rather than the json

**Comment by lethiferal** [comment]
I tried minifying it too but no luck. Still says the JSON isn't valid.

**Comment by USERSATOSHI** [comment]
minify is not the issue 

issue is the \n in ur json

**Comment by lethiferal** [comment]
> minify is not the issue 
> 
> issue is the \n in ur json

Sorry i misunderstood,
I'll let you know if it works, thanks.

**Comment by Leref** [comment]
Resolved.
