### ISSUE TITLE
Bug: Cannot get message arguments in nonPrefixed commands

### ISSUE THREAD

**Issue by Modyes** [aoijs/aoi.js#416]
### Bug Type

Function

### Bugged function

```js
$message
```

### Version of aoi.js

v5.5.5 (Default)

### Version of Node.js

v16.6.0

### Excepted Output

it should be returning the author's message in the command, but instead it returns the command name in nonPrefixed commands I tried to specify args like $message[0] or $message[1], $message[2] and $message[1] returned the command name, anything else is just empty.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by USERSATOSHI** [comment]
can u send ss

**Comment by Mody-0** [comment]
@USERSATOSHI 
![Screenshot_20220828_004403](https://user-images.githubusercontent.com/84382848/187050535-4e535a94-47f5-4230-b07e-d12e2e7fea52.jpg)
![Screenshot_20220828_004323](https://user-images.githubusercontent.com/84382848/187050538-5e9af5c6-4338-4f9f-a63c-41a71eb0e5d4.jpg)

**Comment by Modyes** [comment]
Nevermind.. $message[2] returns first message argument, it didn't work out the first time but now it did.
