### ISSUE TITLE
$sendMessage is bugged

### ISSUE THREAD

**Issue by Just-Mohamed** [aoijs/aoi.js#42]
i am getting this error for some reason 
![Screenshot_20210501-132154](https://user-images.githubusercontent.com/60315196/116781913-54348600-aa86-11eb-9f20-4719d3291788.png)

**Comment by soudblox** [comment]
@Just-Mohamed the usage of $sendMessage is `$sendMessage[message;return message id (yes or no)]` none of the fields are optional

**Comment by USERSATOSHI** [comment]
> @Just-Mohamed the usage of $sendMessage is `$sendMessage[message;return message id (yes or no)]` none of the fields are optional

dev branch has optional field system
@soudblox

**Comment by Kino7916** [comment]
New commit in dev branch should fix the issue.
