### ISSUE TITLE
Add a true $alwaysExecute

### ISSUE THREAD

**Issue by ServerDeveloper9447** [aoijs/aoi.js#421]
### Featuring Type

Function

### So, what is it about?

It's like the already existing $alwaysExecute function but doesn't depend on a message trigger. It will run no matter if the user is sending any messages or not.

Just like the `.setInterval()` function of JavaScript. It will run independently within a defined interval of time.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by USERSATOSHI** [comment]
so basically a bot.loopCommand
