### ISSUE TITLE
Comment func

### ISSUE THREAD

**Issue by Aluwi21** [aoijs/aoi.js#422]
### Featuring Type

Function

### So, what is it about?

Igroning a test in commend func 
Like $igr[im will not executed]

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Bumblebee-3** [comment]
Hey, aoi.js v5 will not be updated further. Here is a simple method (using aoi.js custom functions) in which you can create such a function yourself:
```javascript
bot.functionManager.createCustomFunction({
  name: "$ignore",
  type: "djs",
  code: async d => {
        
  const data = d.util.openFunc(d);
    const [message] = data.inside.splits;
    //do whatever you want with message...
  //console.log(message);

        
        
  return {
    code: d.util.setCode(data)
  }}
});
```

Hope this helps!

**Comment by Leref** [comment]
This was already in the plans of v6.0.0
It will be referred as `$ignoreCode`.
