### ISSUE TITLE
Add Webserver Function

### ISSUE THREAD

**Issue by SPYNARY** [aoijs/aoi.js#424]
### Featuring Type

Others

### So, what is it about?

Hi , I was thinking about how to use the express package with my aoi bot but there is no practical way to create a webserver for aoi, would it be possible to create an external plugin to create a webserver with aoi ?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Bumblebee-3** [comment]
By WebServer I presume you mean something like a dashboard or a developer panel. While Akarui Team has already released a developer panel [link here](https://www.npmjs.com/package/@akarui/aoi.panel), a similar feature is going to be released soon for dashboards. But till then, you could learn the basics of express, and use 
```javascript
bot.db.set("main", "variable name", "server id / user id", "new value");
```
and of course, you could create a login with discord system with discord-oauth2.
Hope this helps!

**Comment by SPYNARY** [comment]
Can you send me the code for get value of variable ?

**Comment by Bumblebee-3** [comment]
@SPYNARY Here is the code to get a variable
```js
await bot.db.get("main","var name","id of channel/server/user")
```

**Comment by pythoniaweb** [comment]
hey read https://github.com/Faf4a/aoi.js-documentation/tree/v6/src/guides/akarui/aoi.panel and https://github.com/Faf4a/aoi.js-documentation/blob/v6/src/guides/akarui/aoi.panel/advanced.md if you wish to make advenced aoi.js panel
