### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by Parades16** [aoijs/aoi.js#426]
### Bug Type

Function

### Bugged function

```js
It responds as false even though there is a var here's the code

bot.command({
  name:"varE",
  code:`$varExists[prefix]`
})

bot.command({
  name:"varE",
  code:`$varExists[$message]`
})

bot.command({
  name:"varE",
  code:`$varExists`
})

I used all of these three codes, what's the write code?
```

### Version of aoi.js

v5.5.5 (Default)

### Version of Node.js

v16.6.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zerealone** [comment]
I suggest you use my package: https://www.npmjs.com/package/more-aoi.js
It have this function, and it working with any type of variable.
If you want to you can see how I did it by looking here: https://github.com/zerealone/more-aoi.js/blob/master/lib.js
~ Amit

**Comment by USERSATOSHI** [comment]
![image](https://user-images.githubusercontent.com/73595362/200859023-904c5e18-7831-42d9-b680-2f70e4b12b81.png)
this function doesn't seems to exist in src code

**Comment by Parades16** [comment]
aoi.js has a new function. We can add our own codes their Ayaka. AYAKA. AYAKA.

I do not need this btw fixed it already lol LLLLLLLL
