### ISSUE TITLE
current_duration & duration_left Bugged and returns 0 always [Lavalink]

### ISSUE THREAD

**Issue by MustafaAmsy** [aoijs/aoi.js#43]
## Type
- [x] Functions: $lavalinkExecute
- [ ] Callbacks: None
- [ ] Handlers: None
- [ ] Others: \______

Code used:
```
$lavalinkExecute[songinfo;duration_left] + $lavalinkExecute[current_duration]
```

More:
- Aoi.js version: 1.0.1
- Node.js version: Idk

**Comment by soudblox** [comment]
$djsEval[process.version;yes] to get Node.js version

![image](https://user-images.githubusercontent.com/73058244/116786959-b794d700-aacb-11eb-8678-025cc171af45.png)

current_duration doesn't work, can replicate, but not duration_left

**Comment by Kino7916** [comment]
> $djsEval[process.version;yes] to get Node.js version
> 
> ![image](https://user-images.githubusercontent.com/73058244/116786959-b794d700-aacb-11eb-8678-025cc171af45.png)
> 
> current_duration doesn't work, can replicate, but not duration_left

It's probably Event Handler problem, I will check.

**Comment by Kino7916** [comment]
New commit in dev branch should resolve the issue.
