### ISSUE TITLE
Bug: $addField

### ISSUE THREAD

**Issue by ryzmae** [aoijs/aoi.js#431]
### Bug Type

Function

### Bugged function

```js
The $addField function is not working for mutiple fields
```

### Version of aoi.js

v6.0.0 (Unstable Version)

### Version of Node.js

v18.6.0+ (Latest)

### Excepted Output

I tried using it an Help.js file

### Relevant log output

```shell
There was no output just nothing
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by USERSATOSHI** [comment]
fixed in : c6e6b52e0b8b0636932f5e824f01eb464cac31ac
