### ISSUE TITLE
Bug: $getBotInvite not work with button

### ISSUE THREAD

**Issue by Aluwi21** [aoijs/aoi.js#433]
### Bug Type

Function

### Bugged function

```js
$addButton[1;Label;link;$getBotInvite]
V6
```

### Version of aoi.js

v5.0.0

### Version of Node.js

v16.6.0

### Excepted Output

![Screenshot_2022-12-07-12-20-29-208_com sec android app sbrowser](https://user-images.githubusercontent.com/104754516/206097446-5ad01e08-fa8d-4665-a42b-ded9a3094357.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by USERSATOSHI** [comment]
$addButton[1;Label;link;$nonEscape[$getBotInvite]]

**Comment by Aluwi21** [comment]
Oh ok

**Comment by Leref** [comment]
Resolved.
