### ISSUE TITLE
Bug: $addField cant use multiple in 1 index

### ISSUE THREAD

**Issue by Aluwi21** [aoijs/aoi.js#434]
### Bug Type

Function

### Bugged function

```js
$addField[]
V6
```

### Version of aoi.js

v5.0.0

### Version of Node.js

v16.6.0

### Excepted Output

![IMG_20221207_212213](https://user-images.githubusercontent.com/104754516/206205328-8101ba54-c762-4a6d-b7b0-4af59fa865da.jpg)
![IMG_20221207_213247](https://user-images.githubusercontent.com/104754516/206206636-29dd98cd-d0ef-4d7e-90c0-6ea6fbb4a594.jpg)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Aluwi21** [comment]
Ups, wrong upload

**Comment by Aluwi21** [comment]
Fixed

**Comment by USERSATOSHI** [comment]
fixed in : c6e6b52e0b8b0636932f5e824f01eb464cac31ac
