### ISSUE TITLE
Bug: Cant create func

### ISSUE THREAD

**Issue by Aluwi21** [aoijs/aoi.js#435]
### Bug Type

Handler

### Bugged function

```js
bot custum function
```

### Version of aoi.js

v5.0.0

### Version of Node.js

v16.6.0

### Excepted Output

![Screenshot_2022-12-13-05-06-17-582_com sec android app sbrowser](https://user-images.githubusercontent.com/104754516/207165689-9ef150b3-3025-4d2c-a03a-35005e67c13a.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Aluwi21** [comment]
fix that and i need that

**Comment by Parades16** [comment]
Well, you will have to use

bot.functionManager.createFunction({

In v6 its changed and also make sure to read the changelogs before asking for help.

**Comment by USERSATOSHI** [comment]
In v6 it's createFunction

**Comment by Leref** [comment]
No changes. Closing.
