### ISSUE TITLE
Bug: $getAuditLogs doesn't return target ID

### ISSUE THREAD

**Issue by DarkSpencer** [aoijs/aoi.js#436]
### Bug Type

Function

### Bugged function

```js
$getAuditLogs {target.id} doesn't return a user ID
```

### Version of aoi.js

v5.5.5 (Default)

### Version of Node.js

v18.6.0+ (Latest)

### Excepted Output

It returns some random numbers but it isn't a user ID

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by USERSATOSHI** [comment]
fixed it in : b873d83e3ea5c300a26cfcf271a3bebf1422936f
