### ISSUE TITLE
Bug: $interactionEdit returns [object Object] after execution

### ISSUE THREAD

**Issue by ethann2004** [aoijs/aoi.js#437]
### Bug Type

Function

### Bugged function

```js
$interactionEdit[test;;;;users]

$interactionDeferUpdate
```

### Version of aoi.js

v6.0.0 (Unstable Version)

### Version of Node.js

v18.6.0+ (Latest)

### Excepted Output

$interactionEdit works how it's suppose to but after the command was executed, it returns [object Object]

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Huguitis** [comment]
I can confirm.

**Comment by USERSATOSHI** [comment]
actually it's $interactionDeferUpdate that is returning the [Object object]
but noted
