### ISSUE TITLE
Add "token" parameter in $webhookExists

### ISSUE THREAD

**Issue by DarkSpencer** [aoijs/aoi.js#439]
### Featuring Type

Function

### So, what is it about?

I think there should be an optional "token" parameter in $webhookExists. So like `$webhookExists[id;token]`. This allows us to see if a certain webhook exists in a channel which can be helpful for people who uses webhooks for logging. Sorry if I'm wrong but I think `client.fetchWebhook` has an optional "token" parameter.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by USERSATOSHI** [comment]
@Leref will this confict with your pending commits?

**Comment by Leref** [comment]
No, this can be merged.
