### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by pythoniaweb** [aoijs/aoi.js#443]
### Featuring Type

Function

### So, what is it about?

Discord added timeout function can you add timeout please
Example from discord js 
```
guildMember.timeout(5 * 60 * 1000, 'They deserved it')
  .then(console.log)
  .catch(console.error);
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Leref** [comment]
It's already been a thing.
Use the latest version (6.1.1.) at this time.

`$timeoutMember[guildID;memberID;timeout;timeoutEndsAt;reason]`

**Comment by pythoniaweb** [comment]
thanks but why it isnt at docs?

**Comment by pythoniaweb** [comment]
@Leref

**Comment by Faf4a** [comment]
Documentation is currently not updated, if you want you can [check this](https://github.com/Faf4a/aoi.js-documentation/blob/v6/src/functions/Calling/timeoutMember.md) in the meanwhile.

**Comment by pythoniaweb** [comment]
oh k

**Comment by pythoniaweb** [comment]
and what about timeoutmembers permission its missing

**Comment by Faf4a** [comment]
It's not missing in the latest version (6.1.1).

`moderatemembers`, instead of `timeoutmembers`.
