### ISSUE TITLE
Bug: play track dont work aoi.js music linux

### ISSUE THREAD

**Issue by pythoniaweb** [aoijs/aoi.js#444]
### Bug Type

Function

### Bugged Function

```js
module.exports = {
  name: "play",
  $if: "v4", //enabling pseudo $if
  code: `
    $playTrack[https://www.youtube.com/watch?v=dQw4w9WgXcQ;youtube]
    

    $if[$hasPlayer==false]
        $joinVc
    $endif

    $onlyif[($voiceId[$clientId]!=)&&($voiceId[$clientId]==$voiceId);you are not in the same voice channel]
    $onlyif[$voiceId!=;join a voice channel before using play cmd]
    `,
};
```

### Version of aoi.js

v6-dev

### Version of Node.js

v19.6.0 (Current)

### Excepted Output

Error: Error: Cannot find module '@discordjs/opus'
Require stack:
- /home/runner/adsasdfsa/node_modules/prism-media/src/util/loader.js
- /home/runner/adsasdfsa/node_modules/prism-media/src/opus/Opus.js
- /home/runner/adsasdfsa/node_modules/prism-media/src/opus/index.js
- /home/runner/adsasdfsa/node_modules/prism-media/src/index.js
- /home/runner/adsasdfsa/node_modules/@discordjs/voice/dist/index.js
- /home/runner/adsasdfsa/node_modules/@akarui/aoi.music/lib/newstruct/audioPlayer.js
- /home/runner/adsasdfsa/node_modules/@akarui/aoi.music/lib/index.js
- /home/runner/adsasdfsa/index.js
Error: Cannot find module 'node-opus'
Require stack:
- /home/runner/adsasdfsa/node_modules/prism-media/src/util/loader.js
- /home/runner/adsasdfsa/node_modules/prism-media/src/opus/Opus.js
- /home/runner/adsasdfsa/node_modules/prism-media/src/opus/index.js
- /home/runner/adsasdfsa/node_modules/prism-media/src/index.js
- /home/runner/adsasdfsa/node_modules/@discordjs/voice/dist/index.js
- /home/runner/adsasdfsa/node_modules/@akarui/aoi.music/lib/newstruct/audioPlayer.js
- /home/runner/adsasdfsa/node_modules/@akarui/aoi.music/lib/index.js
- /home/runner/adsasdfsa/index.js
Error: Cannot find module 'opusscript'
Require stack:
- /home/runner/adsasdfsa/node_modules/prism-media/src/util/loader.js
- /home/runner/adsasdfsa/node_modules/prism-media/src/opus/Opus.js
- /home/runner/adsasdfsa/node_modules/prism-media/src/opus/index.js
- /home/runner/adsasdfsa/node_modules/prism-media/src/index.js
- /home/runner/adsasdfsa/node_modules/@discordjs/voice/dist/index.js
- /home/runner/adsasdfsa/node_modules/@akarui/aoi.music/lib/newstruct/audioPlayer.js
- /home/runner/adsasdfsa/node_modules/@akarui/aoi.music/lib/index.js
- /home/runner/adsasdfsa/index.js
    at Object.loader [as require] (/home/runner/adsasdfsa/node_modules/prism-media/src/util/loader.js:12:9)
    at loadOpus (/home/runner/adsasdfsa/node_modules/prism-media/src/opus/Opus.js:17:17)
    at new OpusStream (/home/runner/adsasdfsa/node_modules/prism-media/src/opus/Opus.js:46:10)
    at new Encoder (/home/runner/adsasdfsa/node_modules/prism-media/src/opus/Opus.js:149:5)
    at Object.transformer (/home/runner/adsasdfsa/node_modules/@discordjs/voice/dist/index.js:1675:22)
    at /home/runner/adsasdfsa/node_modules/@discordjs/voice/dist/index.js:1855:58
    at Array.map (<anonymous>)
    at createAudioResource (/home/runner/adsasdfsa/node_modules/@discordjs/voice/dist/index.js:1855:39)
    at AudioPlayer.play (/home/runner/adsasdfsa/node_modules/@akarui/aoi.music/lib/newstruct/audioPlayer.js:73:56)

### Relevant log output

```shell
Error: Error: Cannot find module '@discordjs/opus'
Require stack:
- /home/runner/adsasdfsa/node_modules/prism-media/src/util/loader.js
- /home/runner/adsasdfsa/node_modules/prism-media/src/opus/Opus.js
- /home/runner/adsasdfsa/node_modules/prism-media/src/opus/index.js
- /home/runner/adsasdfsa/node_modules/prism-media/src/index.js
- /home/runner/adsasdfsa/node_modules/@discordjs/voice/dist/index.js
- /home/runner/adsasdfsa/node_modules/@akarui/aoi.music/lib/newstruct/audioPlayer.js
- /home/runner/adsasdfsa/node_modules/@akarui/aoi.music/lib/index.js
- /home/runner/adsasdfsa/index.js
Error: Cannot find module 'node-opus'
Require stack:
- /home/runner/adsasdfsa/node_modules/prism-media/src/util/loader.js
- /home/runner/adsasdfsa/node_modules/prism-media/src/opus/Opus.js
- /home/runner/adsasdfsa/node_modules/prism-media/src/opus/index.js
- /home/runner/adsasdfsa/node_modules/prism-media/src/index.js
- /home/runner/adsasdfsa/node_modules/@discordjs/voice/dist/index.js
- /home/runner/adsasdfsa/node_modules/@akarui/aoi.music/lib/newstruct/audioPlayer.js
- /home/runner/adsasdfsa/node_modules/@akarui/aoi.music/lib/index.js
- /home/runner/adsasdfsa/index.js
Error: Cannot find module 'opusscript'
Require stack:
- /home/runner/adsasdfsa/node_modules/prism-media/src/util/loader.js
- /home/runner/adsasdfsa/node_modules/prism-media/src/opus/Opus.js
- /home/runner/adsasdfsa/node_modules/prism-media/src/opus/index.js
- /home/runner/adsasdfsa/node_modules/prism-media/src/index.js
- /home/runner/adsasdfsa/node_modules/@discordjs/voice/dist/index.js
- /home/runner/adsasdfsa/node_modules/@akarui/aoi.music/lib/newstruct/audioPlayer.js
- /home/runner/adsasdfsa/node_modules/@akarui/aoi.music/lib/index.js
- /home/runner/adsasdfsa/index.js
    at Object.loader [as require] (/home/runner/adsasdfsa/node_modules/prism-media/src/util/loader.js:12:9)
    at loadOpus (/home/runner/adsasdfsa/node_modules/prism-media/src/opus/Opus.js:17:17)
    at new OpusStream (/home/runner/adsasdfsa/node_modules/prism-media/src/opus/Opus.js:46:10)
    at new Encoder (/home/runner/adsasdfsa/node_modules/prism-media/src/opus/Opus.js:149:5)
    at Object.transformer (/home/runner/adsasdfsa/node_modules/@discordjs/voice/dist/index.js:1675:22)
    at /home/runner/adsasdfsa/node_modules/@discordjs/voice/dist/index.js:1855:58
    at Array.map (<anonymous>)
    at createAudioResource (/home/runner/adsasdfsa/node_modules/@discordjs/voice/dist/index.js:1855:39)
    at AudioPlayer.play (/home/runner/adsasdfsa/node_modules/@akarui/aoi.music/lib/newstruct/audioPlayer.js:73:56)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pythoniaweb** [comment]
PS: npm install dint help
npm ERR! code ETARGET
npm ERR! notarget No matching version found for aoi.js@^7.0.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2023-03-12T09_46_23_630Z-debug-0.log

**Comment by Faf4a** [comment]
First of all, v7.0.0 doesn't even "fully" exist yet, meaning it has no functionality. Also why are you using the dev version use aoi.js@6.1.1 instead. Also,
```diff
+ $if: "old
- $if: "v4"
```

Make sure to install, `@akarui/aoi.music`, `opusscript` & ` ffmpeg-static`.

**Comment by pythoniaweb** [comment]
Ooof thanks this helped
