### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by CycloneAddons** [aoijs/aoi.js#449]
### Bug Type

Function

### Bugged Function

```js
$stringStartsWith[$get[m];$getGuildVar[prefix]ping]
$let[m;$toLowerCase[$message]]

Aoi.js v6.1.1
```

### Version of aoi.js

v6.0.0

### Version of Node.js

v18.14.0 (LTS)

### Excepted Output

![Screenshot_2023-04-08-14-09-41-842_com replit app](https://user-images.githubusercontent.com/90061864/230765193-57575512-15d0-4a8a-b754-d8736f09764e.jpg)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by USERSATOSHI** [comment]
![image](https://user-images.githubusercontent.com/73595362/230770992-eac9136b-64e1-4f44-a081-796872391c76.png)

@CycloneAddons working fine

**Comment by Neodevils** [comment]
@CycloneAddons `$stringStartsWith[text;letters]` works fine on **v6.1.1**.

**Comment by USERSATOSHI** [comment]
closed due to inacitivity
