### ISSUE TITLE
Bug: $ping

### ISSUE THREAD

**Issue by christophergarcia-KS** [aoijs/aoi.js#454]
### Bug Type

Function

### Bugged Function

```js
module.exports = {
  name: "ping",
  code: ` pong $ping ms`
}
```

### Version of aoi.js

v6.0.0

### Version of Node.js

v19.6.0 (Current)

### Excepted Output

to send the ping of the bot it's sends -1 which is not normal.

### Relevant log output

```shell
pong -1 ms
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by USERSATOSHI** [comment]
Are u sure u used it in bot cmd

If u tried that on ready cmd then it will send -1 as it hasn't ping the websocket yet

**Comment by christophergarcia-KS** [comment]
NVM I fixed it.
