### ISSUE TITLE
Bug: Leaderboard doesn't work correctly.

### ISSUE THREAD

**Issue by NanotechPikachu** [aoijs/aoi.js#455]
### Bug Type

Function

### Bugged Function

```js
module.exports = {
      name: "xxx",
      type: "interaction",
      prototype: "select menu",
      code: `
$interactionReply[;{newEmbed:{title: Giveaways Pending List}{description:$replaceText[$rawLeaderboard[gw_pending;asc;user;{top} | {tag} | {id} | {value};10;1];827287;Nitro Basic]}{color:Random}{timestamp}};;;everyone;true]`
}]
```

### Version of aoi.js

v6.0.0

### Version of Node.js

v18.14.0 (LTS)

### Excepted Output

I expect the output be like 
`1 | NanotechPikachu#6406 | My ID | Nitro Basic`
As i have used $replacetext to replace the number that i will add in the var by using the command or eval. 
The problem is that, the reply from my bot is like
`1 |  unverified | pending | NaN`

The problem is not only with `$rawLeaderboard` but, also with `$userLeaderboard` etc aka the leaderboard group.

Also, the leaderboard isn't adding new values when i add another value to the var and only shows the one i first added.

I hope this issue can be **solved** in the future versions. For the time being, using leaderboard is a no go and i have came to this conclusion as i talked with 2 others and they too are experiencing the same problem.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NanotechPikachu** [comment]
Oh sorry. Before I forget, the actual AOI version is **6.2.6** and NodeJS version is **18.16.0**.

**Comment by Leref** [comment]
Leaderboard function has been updated and resolved with username type and replace.
If this continues in next update, open this issue.
