### ISSUE TITLE
Bug: $setChannelVar does not save data permanently.

### ISSUE THREAD

**Issue by Modyes** [aoijs/aoi.js#456]
### Bug Type

Function

### Bugged Function

```js
$setChannelVar[VarName;Value]
```

### Version of aoi.js

v6.0.0

### Version of Node.js

v19.6.0 (Current)

### Excepted Output

$setChannelVar[VarName;Value] should save the data permanently, have it stored in the database even after the server restarts. 

### Relevant log output

Well it saves the data, and I'm able to get it using $getChannelVar[VarName] but once I restart the server all the data on $getChannelVar disappears and the issue is only on that function as I've tried other variable functions and all of them save/get the data properly except get or set ChannelVar.
I know the first thing that is going to be on your mind is "probably its a host issue" well no its not as I've also tried a lot of different hosting services including my own VPS, and all of them had the same issue so yeah it's not a host problem.

to reproduce the problem you just need to do a few simple steps
1- use the function $setChannelVar to save some data on some channel
2- restart the server
3- use the function $getChannelVar to get that data you just saved.. it's gone
Note: I use aoi.js v6.1.1 and default database.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by USERSATOSHI** [comment]
can you send your database setup also are u using v6.0.0 or v6.2.x ?

**Comment by Modyes** [comment]
I don't have a "database setup" it's basically just that
```js
const bot = new aoijs.AoiClient({
  token: "",
  prefix: "$",
    mobilePlatform: true,
    suppressAllErrors: true,
  intents: ["MessageContent","GuildMessages","Guilds","GuildMembers","GuildWebhooks","GuildVoiceStates","GuildBans","GuildEmojisAndStickers","GuildPresences","GuildIntegrations"],
  events: ["onMessage","onInteractionCreate","onChannelCreate","onJoin","onMessageDelete","onFunctionError"]
  })

const loader = new aoijs.LoadCommands(bot);
loader.load(bot.cmd,'./commands/') 
```


And I use v6.1.1

**Comment by USERSATOSHI** [comment]
can you send a screenshot cause i cant seem to replicate this

**Comment by USERSATOSHI** [comment]
```js
const bot = new aoijs.AoiClient({
  token: "",
  prefix: "$",
    mobilePlatform: true,
    suppressAllErrors: true,
  intents: ["MessageContent","GuildMessages","Guilds","GuildMembers","GuildWebhooks","GuildVoiceStates","GuildBans","GuildEmojisAndStickers","GuildPresences","GuildIntegrations"],
  events: ["onMessage","onInteractionCreate","onChannelCreate","onJoin","onMessageDelete","onFunctionError"],
database: {
  db: require("aoi.db"),
  type: "aoi.db",
  tables: ["main"],
  path: "./database/",
  extraOptions: {
    dbType : "KeyValue",
  }
}
  })

const loader = new aoijs.LoadCommands(bot);
loader.load(bot.cmd,'./commands/') 
```

try this @Mody-0

**Comment by USERSATOSHI** [comment]
closed due to inactivity, Please open if there is an update
