### ISSUE TITLE
New Function

### ISSUE THREAD

**Issue by devlordduck** [aoijs/aoi.js#459]
### Featuring Type

Function

### So, what is it about?

Can you please add function $fetchMessages that will work like this:
`$fetchMessages[5;$channelID]` -> `[{content: "content of message", author: object, channel: object, id: 12345}, {}, {}, {}, {}]`?

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by Leref** [comment]
All fetch functions will be changed in next update.
