### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by Paoloooooooooo** [aoijs/aoi.js#461]
### Bug Type

Function

### Bugged Function

```js
$textTrim[Imagine          a          string package    .]
```

### Version of aoi.js

v6.2.6 - v7.0.0

### Version of Node.js

v19.6.0 (Current)

### Excepted Output

It's supposed to remove extra spaces but it did nothing
<img width="521" alt="image" src="https://github.com/AkaruiDevelopment/aoi.js/assets/131975324/82646eda-c895-4679-9db5-7bef5c054ea6">

### Relevant log output

```shell
No error, it just doesn't do what it's supposed to do
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by USERSATOSHI** [comment]
It trims the start and the end not in between
