### ISSUE TITLE
Hybrid Slash Commands

### ISSUE THREAD

**Issue by Balghae** [aoijs/aoi.js#463]
### Featuring Type

Function

### So, what is it about?

By a hybrid slashcommand I mean that it is possible for a slash command to execute a prefix command without having to rewrite the command.
I have the idea that the `{execute:<command name>}` or `{executHybrid:<command name>}` option can be integrated within the `$interactionReply`.
Also adding the `hybrid` command type, in this way it will be possible to execute the prefix command and its slash counterpart (if any) without having to write another code.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Faf4a** [comment]
i dont think thats how discord works

**Comment by ddodogames** [comment]
You can't do that pretty sure. Moreover, why do you need it? You can just create a prefix and slash command under the same name and create both of commands for them to respond.

No offense but this sounds like something to feed lazy people in my opinion, it's fine if it's not like that.
