### ISSUE TITLE
Suggestions for the akarui@aoi.invite package

### ISSUE THREAD

**Issue by oyrn** [aoijs/aoi.js#464]
### Featuring Type

Others

### So, what is it about?

Here are some suggestions for the package.

$inviteCodes[(option) userID;(option) splitter]
He sends all his invitation links 
example :
$inviteCodes[$authorID; , ] 

-
$inviteCount[(option) userID;codes...]
Indicates the number of people who joined by invitation code
example:
$inviteCount[$authorID;aoi-js;djs]

-
$splitter
It replaces ";" In the code without escaping
example:
$randomText[$authorID$splitter$clientID]
`
$clientOwnerIDs[$splitter]

-
$invited[userID;mention or ID]
He sends a mention of the person who invited him
example:
$invited[$authorID;mention]

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Leref** [comment]
Invite info code related and more functions have been added to @akarui/aoi.invite package as aoi.js will move AoiInvite Class into a package.
