### ISSUE TITLE
Forum functions

### ISSUE THREAD

**Issue by ethann2004** [aoijs/aoi.js#465]
### Featuring Type

Function

### So, what is it about?

For `v6.4.0`, can we be introduced to forum functions?

Examples: `$createForumPost[channelID;Title;Description;Attachment;tags]`, `$getForumTagID[channelID;tagName]`, `$getForumTagName[channelID;tagID?]`, etc

Forums been out for a while and will be amazing to see in aoi.js

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Cyberghxst** [comment]
Forum posts are in fact thread channels so, you can create your stuff with thread functions.
