### ISSUE TITLE
Invite System Update

### ISSUE THREAD

**Issue by waifusprotector** [aoijs/aoi.js#471]
### Featuring Type

Others

### So, what is it about?

The invite system implemented in v6.4 feels very incomplete, the docs don't nearly provide enough information & examples regarding the functions' usage, and some important functions that allow the modification of invites are missing, for example, adding/removing invites/fakeinvites, there are some other generic functions that you could add like invite leaderboards, resetting a guild's invites, and if possible functions that display all of a specific user's invites & invited members. 

I apologize if anything i suggested here is already implemented, the docs don't explain much so i hope you understand. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by USERSATOSHI** [comment]
this is already being implemented in a new package `@akarui/aoi.invites` and it has accounted for most of the functions that were missing

**Comment by Leref** [comment]
resolved
