### ISSUE TITLE
Prevent all functions from running inside $if's

### ISSUE THREAD

**Issue by Balghae** [aoijs/aoi.js#473]
### Featuring Type

Others

### So, what is it about?

I suggest that the functions inside the `$if`'s stop executing unless what you want to validate is true or false, because generally even if it is true or false, all the functions inside the $ifs are executed.
I suggest this because in general using `$ifAwaited` for everything that involves functions is more complicated especially when you have many `$if`'s in your code.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Faf4a** [comment]
`$if: old` exists for the time being, also the usage and execution of `$if[]` will change entirely in v7.
