### ISSUE TITLE
Bug: aoi.parser timestamp/field inline support

### ISSUE THREAD

**Issue by ethann2004** [aoijs/aoi.js#475]
### Bug Type

Extensions

### Bugged Function

```js
module.exports = {
    name: "announce",
    prototype: "slash",
    type: "interaction",
    code: `
    $interactionReply[;
        {newEmbed:
            {description:$slashOption[message]}
            {footer:Sent by $interactionData[author.username]}
            {timestamp:$datestamp}
        };;;users;false]

    $onlyIf[$interactionData[author.id]==$interactionData[guild.ownerId];]

    $suppressErrors`
}
```

### Version of aoi.js

v6.2.6

### Version of Node.js

v19.6.0 (Current)

### Excepted Output

aoi.js: v6.4.0
 @akarui/aoi.parser: v1.0.1

Just reporting that `{timestamp:ms}` console logs the ms that is entered. Also, it seems like you forgot to give support for true/false in `{field}` inline.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by USERSATOSHI** [comment]
You are not supposed to use {timestamp:ms} 

ms meant that u can add ur own timestamp

But to use default use {timestamp}

For inline aoi.parser uses yes/no instead of true/false iirc

**Comment by ethann2004** [comment]
I remember seeing a [commit](https://github.com/AkaruiDevelopment/aoi.parser/commit/8bb3b9d2b3e4f0d23b7ce5e82e0b15c88c891ec5) on your repository saying true/false support. True/false is supported for basically everything besides field inline. The code I gave above was just an example of the embed I'm using. I put a custom ms in `{timestamp}` in my code and it gets console log.

**Comment by Leref** [comment]
true of false is supposed to be supported, @USERSATOSHI should look into more of it.

**Comment by Leref** [comment]
@USERSATOSHI any updates?

**Comment by Leref** [comment]
no clear indication, try making a new issue If issue occurs again at https://github.com/AkaruiDevelopment/aoi.parser
