### ISSUE TITLE
V6.1.1 | $clear

### ISSUE THREAD

**Issue by GBlade0607** [aoijs/aoi.js#510]
### Bug Type

Function

### Bugged Function

```js
module.exports = {
name: "sil",
aliases: ["clear"],
$if: "old",
code:
`
$if[$isNumber[$message[1]]!=false]

$sendMessage[Kanaldan $clear[$channelID;$message[1];everyone;true] tane mesaj sildim. {extraOptions:{delete:5s}}]

$wait[1s]

$deletecommand

$onlyIf[$message[1]<=1000;En az 1, __en fazla 1000 mesaj__ silebilirsin.]

$onlyIf[$message[1]>=1;__En az 1__, en fazla 1000 mesaj silebilirsin.]


$onlyIf[$message[1]!=;Hatalı kullanım. **$getGuildVar[prefix;$guildID;bot]sil silenecek miktar**


$elseif[$isNumber[$message[1]]!=true]

$sendMessage[$username[$mentioned[1]] adlı kullanıcının $clear[$channelID;$message[2];user;$mentioned[1];true] tane mesajını kanaldan sildim. {extraOptions:{delete:5s}}]

$wait[1s]

$deletecommand

$onlyIf[$message[1]<=1000;En az 1, __en fazla 1000 mesaj__ silebilirsin.]

$onlyIf[$message[1]>=1;__En az 1__, en fazla 1000 mesaj silebilirsin.]

$onlyIf[$message[1]!=;Hatalı kullanım. **$getGuildVar[prefix;$guildID;bot]sil @kullanıcı silenecek miktar**]

$endelseif
$endif

$onlyClientPerms[administrator;Bunun için **Yönetici** iznine ihtiyacım var.]

$onlyIf[$hasPerms[$guildID;$authorID;managemessages]!=false;Bu komutu kullanabilmek için **Mesajları Yönet** yetkisine sahip olmalısın.]`
}
```

### Version of aoi.js

v6.5.0

### Version of Node.js

v20.5.1 (Current)

### Excepted Output

Normally, when messages are deleted, it should indicate how many messages were deleted, but it did not show a number at all. 
![Screenshot_20231204-121009](https://github.com/AkaruiDevelopment/aoi.js/assets/152855173/a386b7e1-0464-4756-8105-c7f2ee735702)
![Screenshot_20231204-121033](https://github.com/AkaruiDevelopment/aoi.js/assets/152855173/1f9f0423-0a3d-4784-912d-24055d8fec5f)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Faf4a** [comment]
Thank you for using our [Issues](https://github.com/AkaruiDevelopment/aoi.js/issues/), I can confirm that this is a bug, and it'll be fixed in the next version!

**Comment by baka-aho** [comment]
solved 
#next version
