### ISSUE TITLE
Bug: Database file issue

### ISSUE THREAD

**Issue by Snowxxxxxxxxx** [aoijs/aoi.js#511]
### Bug Type

Function

### Bugged Function

```js
module.exports = ({
name: "cooldown",
aliases: ["cd","time","timer","t"],
code:`
$color[1;#000000]
$author[1;$username[$authorID]'s Cooldown;(gif_link)]
$description[1;
:zap: **Daily** : $replaceText[$replaceText[$checkCondition[$getCooldownTime[20h;globalUser;daily;$authorID]<0];true;:yes:];false;:no: **$parseDate[$getCooldownTime[20h;globalUser;daily;$authorID];time]**]
$addTimestamp[1]
`})
```

### Version of aoi.js

v6.5.0

### Version of Node.js

v20.5.1 (Current)

### Excepted Output

The command is supposed to let the user know if they can use other comands again or how long they still have to wait, though it's not working anymore since i updated to the latest version of aoi.js
though when i run the daily command it works and it has cooldown, but on the cooldown command's embed it shows that the user can do it again (but they can't).
It's searching in the main file, so it wont work anymore.
![image](https://github.com/AkaruiDevelopment/aoi.js/assets/152856604/e37b6eb4-987e-41aa-9dfd-85a7b1b8208b)
![image-1](https://github.com/AkaruiDevelopment/aoi.js/assets/152856604/3a121401-7eee-44ba-814f-71fe5bfc20fb)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Faf4a** [comment]
Thank you for using our [Issues](https://github.com/AkaruiDevelopment/aoi.js/issues/), I can confirm that this is a bug, and it'll be fixed in the next version!

The issue lies in the function trying to search in the main table instead of the __aoijs_vars__ table!

cc: @USERSATOSHI

**Comment by USERSATOSHI** [comment]
> Thank you for using our [Issues](https://github.com/AkaruiDevelopment/aoi.js/issues/), I can confirm that this is a bug, and it'll be fixed in the next version!
> 
> The issue lies indeed in the function trying to search in the primary table instead of the __aoijs_vars__ table.
> 
> cc: @USERSATOSHI 

Ah got it

@Faf4a can you do a quick pr on this as I am traveling rn so I will be able to use my laptop a day after tmr

**Comment by Faf4a** [comment]
> Ah got it
> 
> @Faf4a can you do a quick pr on this as I am traveling rn so I will be able to use my laptop a day after tmr

Will do after I finish other stuff.

**Comment by Faf4a** [comment]
Fixed, will PR later.
