### ISSUE TITLE
banAdd event

### ISSUE THREAD

**Issue by GBlade0607** [aoijs/aoi.js#514]
### Featuring Type

Handler

### So, what is it about?

I want to get the ID of the banning user in the banAdd event but it is not possible now. If you add me, I want to ban protection system.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by baka-aho** [comment]
i have no idea if you mean the user who banned or the user who got banned but u can use the following for the result on banAdd event code.

### To get id of user who banned someone
`$getAuditLogs[$guildID;;1;22;{executor.id}]`

### To get id of user who got banned
`$getAuditLogs[$guildID;;1;22;{target.id}]`

**Comment by USERSATOSHI** [comment]
note: $authorId in banAdd gives id of user who was banned
