### ISSUE TITLE
$VoiceKick function 

### ISSUE THREAD

**Issue by scriptyyy13** [aoijs/aoi.js#516]
### Featuring Type

Function

### So, what is it about?

kick (disconnect) someone from voice channel.
$VoiceKick[guildID;voiceID;userID]

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by baka-aho** [comment]
Hello! To do what you told us, You can use 
`$moveUser[guildId;userid;;reason]`
leaving third param empty will disconnect the user from any vc but yeah having a separate function is convenient, will hold your request for now!

**Comment by scriptyyy13** [comment]
okay, thanks

**Comment by Leref** [comment]
Solved.
