### ISSUE TITLE
$softBan

### ISSUE THREAD

**Issue by anchor-team** [aoijs/aoi.js#517]
### Featuring Type

Function

### So, what is it about?

 "$softban" refers to a temporary restriction or limitation placed on the user. Unlike a permanent ban, a softban usually imposes a time-limited restriction or additional scrutiny on the user's activities, often as a warning or as part of a moderation strategy. This approach aims to curb undesirable behavior without completely barring the user from the community.

### Usage
$softBan[userId;reason]

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Faf4a** [comment]
Softban is **not** a Discord feature. Softban consists of a ban and instant unban to remove their messages, this can be implemented with `$ban` and `$unban`.

**Comment by anchor-team** [comment]
> Softban is **not** a Discord feature. Softban consists of a ban and instant unban to remove their messages, this can be implemented with `$ban` and `$unban`.




Discord has much feature but aoi doesnt right?

**Comment by Faf4a** [comment]
> > Softban is **not** a Discord feature. Softban consists of a ban and instant unban to remove their messages, this can be implemented with `$ban` and `$unban`.
> 
> Discord has much feature but aoi doesnt right?

Discord doesn't offer tempbans or softban as feature, therefore aoi.js doesn't either.

You can create tempbans using $setTimeout and $ban as well as softban with $ban and $unban.

**Comment by Faf4a** [comment]
@Leref this can be closed.
