### ISSUE TITLE
Bug: getObjectProperty Issue

### ISSUE THREAD

**Issue by atlasfyber** [aoijs/aoi.js#521]
### Bug Type

Function

### Bugged Function

```js
module.exports = [{
  name: "earth",
  prototype: "slash",
  type: "interaction",
  code: `
$getObjectProperty[api;[0].image] 
$createObject[api;$httpRequest[https://api.nasa.gov/EPIC/api/natural?api_key=DEMO_KEY;GET;;;Error]] `}]
```

### Version of aoi.js

v6.5.0

### Version of Node.js

v20.5.1 (Current)

### Excepted Output

epic_1b_20231209023357

### Relevant log output

```shell
undefined
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Faf4a** [comment]
@astrofyber Thanks for using our Github issues, I can confirm that is a bug and proceeded to fix it! Will be fixed within this week along the update.

#515
