### ISSUE TITLE
Broad variables

### ISSUE THREAD

**Issue by qhelios** [aoijs/aoi.js#522]
### So, what is it about?

Make it so that we can use the variables established inside of client.variables in JavaScript itself.

## Example
```js
client.variables({
  variable = "this is a variable"
})
console.log("variable")
```
## Output
```
"this is a variable".
```
## Why?
This can be quite handy in many ways as we can use it to interact with websites via a discord bot using an API wrapper.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by USERSATOSHI** [comment]
@qhelios 

```js
client.variables({
  variable = "this is a variable"
})
console.log("variable")
``` 
this syntax is not possible in javascript but you can access variables data like its name , type and default value

use 
```js
client.variableManager.cache.get("variable_tableName")
```

this will return a class object 
```js
Variable {
    name: "variable",
    type: "TEXT",
    default: "this is a variable"
}
```

a sample example would be:
```js
const variable = client.variableManager.cache.get("variable_main");
console.log(variable.default) // this is a variable
```
