### ISSUE TITLE
Readding the {execute:...} to the $onlyIf

### ISSUE THREAD

**Issue by abilalex** [aoijs/aoi.js#523]
### Featuring Type

Extensions

### So, what is it about?

So i want to use {execute in the $onlyIf function in the v6.6.1 and it doesnt work, but when i try in the v5, its work perfectly. please readd {execute feature to $onlyIf again please...

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Faf4a** [comment]
@Leref thoughts?

Would be adding it to the global parser then though, not just $onlyIf?

**Comment by USERSATOSHI** [comment]
> @Leref thoughts?
> 
> Would be adding it to the global parser then though, not just $onlyIf?

global parser so as it will be only used there

**Comment by Faf4a** [comment]
Done in #533

**Comment by Faf4a** [comment]
Implemented in 5d2da42 / #533
