### ISSUE TITLE
Bug: $reactionCount returns an error when the reaction count is 0

### ISSUE THREAD

**Issue by papaaj** [aoijs/aoi.js#527]
### Bug Type

Function

### Bugged Function

```js
$reactionCount[$channelID;$messageID;📌]

I use this, it works in any command (event, default or eval)
```

### Version of aoi.js

v6.6.1

### Version of Node.js

v20.10.0 (LTS)

### Excepted Output

if the reaction count is 0, it should return 0 instead of an "Invalid Emoji ID" error

### Relevant log output

```shell
AoiError: Invalid Emoji ID [908099773049999370;1186048408218243183;📌] 
 { 
   Function : `$reactionCount`,
   Command : `eval`,
   Version : 6.6.1 
 }
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by Faf4a** [comment]
@papaaj thanks for using our Github Issues! I actually fixed it, it's available in the Github Version of aoi.js, please note that this version may be unstable or have unfinished features.

`npm install github:AkaruiDevelopment/aoi.js#v6` would apply the fix.

_It was fixed in: #515_
