### ISSUE TITLE
Bug: leaderboard functions dont work properly

### ISSUE THREAD

**Issue by papaaj** [aoijs/aoi.js#528]
### Bug Type

Function

### Bugged Function

```js
$userLeaderboard
$getLeaderboardInfo and maybe more
```

### Version of aoi.js

v6.6.1

### Version of Node.js

v20.10.0 (LTS)

### Excepted Output

$userLeaderboard and $getLeaderboardInfo dont return info about a user before using $getUserVar on them (you have to use $getUserVar on everyone to get everyone on the leaderboard)

### Relevant log output

```shell
Bot doesnt return any error
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by baka-aho** [comment]
well yeah ofc u cant expect everyone to be in leaderboard without a certain value to rank on,
leaderboard functions get the data from .sql file

![issue](https://media.discordapp.net/attachments/1058843428831629443/1186081920593965076/image0.jpg)

**Comment by Faf4a** [comment]
cc: @USERSATOSHI

**Comment by USERSATOSHI** [comment]
it seems like some weird compability issue i am checking this rn confirming whether this is aoi.db issue or aoi.js issue

**Comment by USERSATOSHI** [comment]
@papaaj ok so issue is with aoi.db's fetchFile's path finder 
fixing it rn

**Comment by USERSATOSHI** [comment]
this is fixed
