### ISSUE TITLE
Bug: Cannot use no intents, error shown

### ISSUE THREAD

**Issue by Yuma246** [aoijs/aoi.js#529]
### Bug Type

Callback

### Bugged Function

```js
/home/container/node_modules/aoi.js/src/class es/AoiBase.js:37 options.intents =options.intents.map((x) => IntentOptions[x] || x); TypeError: Cannot read properties of undefine d (reading 'map') at new BaseClient (/home/container/node_m odules/aoi.js/src/classes/AoiBase.js:37:39 at new Client (/home/container/node_modul es/aoi.js/src/classes/AoiClient.js:13:9) at Object.<anonymous> (/home/container/in dex.js:7:13 at Module._compile (node:internal/modules /cjs/loader:1376:14) at Module. extensions..js (node:internal/ modules/cjs/loader:1435:10) at Module.load (node:internal/modules/cjs /loader:1207:32) at Module._load (node:internal/modules/cj s/loader:1023:12) at Function.executeUserEntryPoint [as run
```

### Version of aoi.js

v6.6.1

### Version of Node.js

v20.10.0 (LTS)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by USERSATOSHI** [comment]
@Yuma246 what did u provide intents as?

**Comment by Leref** [comment]
Seem to be using `all` intents, which doesn't exist.

**Comment by USERSATOSHI** [comment]
> Seem to be using `all` intents, which doesn't exist.

Actually it seems that he isnt using any intents and aoijs needs at least one in array 
this has been discussed and resolved at discord support so we can close this issue

**Comment by Leref** [comment]
Yeah, just noticed I fixed this.
