### ISSUE TITLE
Set $if to always act like the old if and create a new function called $ternary

### ISSUE THREAD

**Issue by nevertrollsh** [aoijs/aoi.js#532]
### Featuring Type

Function

### So, what is it about?

So yeah ever since the old $if is gone, you have to put `$if: old` but the new if should be called $ternary and leref should bring back the old $if

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Faf4a** [comment]
cc @Leref @USERSATOSHI

**Comment by USERSATOSHI** [comment]
this can be done sure

**Comment by Leref** [comment]
Coming in future update, will be closed when it's released.

**Comment by tifaxx** [comment]
the old $if is much better than the new

**Comment by Leref** [comment]
Will be happening in 6.8.10.

**Comment by Faf4a** [comment]
> Will be happening in 6.8.10.

wont happen until 6.10
