### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by NoOnE8151** [aoijs/aoi.js#534]
### Featuring Type

Function

### So, what is it about?

We need a comment function where we can use human language to instruct other developers and future self aswell, it will very helpful since when we have long codes we forget which line id for what use please consider it, thanks.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Faf4a** [comment]
@USERSATOSHI opinion?

**Comment by USERSATOSHI** [comment]
dont we have it already in [Aoi.js-Library](https://github.com/akaruidevelopment/aoi.js-library) as an official plugin tho

@Leref what are you thoughts on this

**Comment by Leref** [comment]
We do however no one really uses that package and it's not really told much.
We can make it official function.

**Comment by Faf4a** [comment]
#546

**Comment by Faf4a** [comment]
Will be added either after interpreter rewrite or in the next update.

**Comment by Leref** [comment]
The merge of the aoi.js-library is available next update.
