### ISSUE TITLE
Bug: $mentionedRoles 1 is last in message for some reason

### ISSUE THREAD

**Issue by scriptyyy13** [aoijs/aoi.js#536]
### Bug Type

Function

### Bugged Function

```js
$mentionedRoles[1] returns lats, not fisrt
```

### Version of aoi.js

v6.6.1

### Version of Node.js

v21.4.0 (Current)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by scriptyyy13** [comment]
![image](https://github.com/AkaruiDevelopment/aoi.js/assets/81494246/e7856c27-be6b-4cac-a1b0-080ac209de35)

**Comment by baka-aho** [comment]
@scriptyyy13 
![image](https://media.discordapp.net/attachments/1022533781040672839/1190254480877432902/image0.jpg) I dont see any problem here recheck the role ids again

**Comment by scriptyyy13** [comment]
i checked it again and it happened again, like in my prev. sh

**Comment by Faf4a** [comment]
Can confirm that this is a bug.

**Comment by Faf4a** [comment]
Can't be fixed.
![image](https://github.com/AkaruiDevelopment/aoi.js/assets/87046111/525dca1b-85ca-4b2f-b599-ae7b7758e61b)
