### ISSUE TITLE
embed creator (something like in d.js)

### ISSUE THREAD

**Issue by papaaj** [aoijs/aoi.js#537]
### Featuring Type

Function

### So, what is it about?

Add a embed creator (leave the normal embed functions too).

It would look like:
**$createEmbed[name;{title:title}{description:description}...]**

Then there would be 2 functions to use the embed, **$embed and {embed}**, for normal usage and for errors.

It would be a lot more readable sometimes than everything in a single line (I think you can just split it into new lines, but still an embed creator would be a lot more readable)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Faf4a** [comment]
You could just do..
```
$sendMessage[$nonEscape[$get[embed]]]
$let[embed;{newEmbed:{title:...}}]
```

Would be basically the same. Also you don't need everything in the same line.

```php
$sendMessage[{newEmbed:
  {title: Some text }
  {description: Some text }
}]
```

is the same as 

```php
$sendMessage[{newEmbed:{title:Some text}{description:Some text}}]
```

> leave the normal embed functions too

This is planned for v7.
```php
$sendMessage[$title[Some text]]
```

**Comment by Faf4a** [comment]
cc @Leref

**Comment by papaaj** [comment]
$let and $get dont work like embed creator, it just returns the text

**Comment by Faf4a** [comment]
Closing, won't be added unless otherwise specified by @Leref

**Comment by USERSATOSHI** [comment]
U can use $nonEscape to convert text back to parser.
