### ISSUE TITLE
Bug: $userCustomStatus always return "none"

### ISSUE THREAD

**Issue by wadeteam** [aoijs/aoi.js#538]
### Bug Type

Function

### Bugged Function

```js
$userCustomStatus[$guildID;$authorID;state]
```

### Version of aoi.js

v6.6.1

### Version of Node.js

v16.11.0 (Lowest)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by baka-aho** [comment]
@wadeteam This is not a bug, you probably don’t have any intent required by this function to work which is 
`GuildPresences`
![image](https://media.discordapp.net/attachments/1022533781040672839/1190253141501956106/image0.jpg)

**Comment by Leref** [comment]
Resolved, I can confirm this.
