### ISSUE TITLE
$channelAction, $roleAction, $emojiAction, $stickerAction

### ISSUE THREAD

**Issue by LuisitoDevhtt** [aoijs/aoi.js#539]
### Featuring Type

Function

### So, what is it about?

All these functions would work for the 'channelUpdate,' 'roleUpdate,' 'emojiUpdate,' and 'stickerUpdate' events, allowing us to obtain the specific action taken with that channel/role/emoji/sticker

In all these options, add the 'separator' parameter, which will separate the actions if more than one was performed on that channel/role/emoji/sticker

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Faf4a** [comment]
Isn't that what $new(eventname) / $old(eventname) does?

**Comment by LuisitoDevhtt** [comment]
Yes, that's true, but what if someone wanted to make a different message for each change?

**Comment by Faf4a** [comment]
> Yes, that's true, but what if someone wanted to make a different message for each change?

You can do that, just use the function/event multiple times.

**Comment by Faf4a** [comment]
Already exists as said functions.
