### ISSUE TITLE
Function showing the number of users in the voice channel

### ISSUE THREAD

**Issue by falsisdev** [aoijs/aoi.js#54]
## Type
- [x] Functions: \<$voice[channelID/all;membersCount]>
- [ ] Callbacks: \<Callback Name>
- [ ] Handlers: \<Handler Type>
- [ ] Others: \______

## Description
If $voice[$voiceID;membersCount] is typed, sends the number of users on the entered voice channel. But if $voice[all;membersCount] is typed, it will send the number of users on all audio channels. Even if the function is not exactly like this, something similar can be done.

**Comment by USERSATOSHI** [comment]
> ## Type
> * [x]  Functions: <$voice[channelID/all;membersCount]>
> * [ ]  Callbacks: <Callback Name>
> * [ ]  Handlers: <Handler Type>
> * [ ]  Others: ______
> 
> ## Description
> If $voice[$voiceID;membersCount] is typed, sends the number of users on the entered voice channel. But if $voice[all;membersCount] is typed, it will send the number of users on all audio channels. Even if the function is not exactly like this, something similar can be done.

first part can be done using $usersInChannel

second part hmm k I will check something and will inform

**Comment by falsisdev** [comment]
> > ## Type
> > * [x]  Functions: <$voice[channelID/all;membersCount]>
> > * [ ]  Callbacks: <Callback Name>
> > * [ ]  Handlers: <Handler Type>
> > * [ ]  Others: ______
> > 
> > ## Description
> > If $voice[$voiceID;membersCount] is typed, sends the number of users on the entered voice channel. But if $voice[all;membersCount] is typed, it will send the number of users on all audio channels. Even if the function is not exactly like this, something similar can be done.
> 
> first part can be done using $usersInChannel
> 
> second part hmm k I will check something and will inform

Oky thx

**Comment by USERSATOSHI** [comment]
@falsisdev for second part I made vcSize which supports that with more options which I will list in my pr

**Comment by falsisdev** [comment]
> @falsisdev for second part I made vcSize which supports that with more options which I will list in my pr

Thx I hope you will be rewarded for your efforts as soon as possible.

**Comment by USERSATOSHI** [comment]
> > @falsisdev for second part I made vcSize which supports that with more options which I will list in my pr
> 
> Thx I hope you will be rewarded for your efforts as soon as possible. 

already got it but thanks
