### ISSUE TITLE
Create Event (This is not Custom Event)

### ISSUE THREAD

**Issue by fhyrox** [aoijs/aoi.js#540]
### Featuring Type

Function

### So, what is it about?

events/event.js
```js
module.exports = [{
name: "test",
params: ["channel"],
execute: "$alwaysExecute",
code: "$executeEvent $onlyIf[$message==testevent;]"
}]
```

commands/testCommand.js
```js
module.exports= [{
type: "test", //event name
channel: "channelid", // params
code: ""
}]
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Faf4a** [comment]
What exactly is the issue?

**Comment by fhyrox** [comment]
suggestion

**Comment by Faf4a** [comment]
That already exists as custom events, it's exactly the same.

Also with simple DJS you can add more command types.

**Comment by Faf4a** [comment]
cc @Leref

**Comment by Leref** [comment]
Already exist, closing.
