### ISSUE TITLE
Bug: Leaderboard is problematic

### ISSUE THREAD

**Issue by ardawn9** [aoijs/aoi.js#542]
### Bug Type

Function

### Bugged Function

```js
module.exports = {
name:"lb",
code:`
$globalUserVarLeaderboard[Seth;asc;{top}. {tag} {value};10;1]
`
}
```

### Version of aoi.js

v6.6.1

### Version of Node.js

v20.10.0 (LTS)

### Excepted Output

When I run this code, it works as if I wrote dsc instead of asc and each name is written twice
![image](https://github.com/AkaruiDevelopment/aoi.js/assets/128643759/e5379d4e-dbf2-49f3-b94e-a2fa9adabd57)
![image](https://github.com/AkaruiDevelopment/aoi.js/assets/128643759/8db25023-caf9-473f-be70-793b6b6d03a9)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Faf4a** [comment]
Tried "desc"?

**Comment by ardawn9** [comment]
i dont use github version for db, but i'm using aoi.js github version

**Comment by Faf4a** [comment]
The usage is
$globalUserVarLeaderboard[Seth;asc;{top}. {tag} {value};10;1]

and

$globalUserVarLeaderboard[Seth;desc;{top}. {tag} {value};10;1]

not a bug
