### ISSUE TITLE
Bug: $getCooldownTime returning random things

### ISSUE THREAD

**Issue by papaaj** [aoijs/aoi.js#543]
### Bug Type

Function

### Bugged Function

```js
$getCooldownTime[24h;user;post-send;$authorID]

When the time = 0:
- on 6.6.1: returns random negative numbers
- on github version: returns NaN (not always)
```

### Version of aoi.js

v6.6.1

### Version of Node.js

v20.10.0 (LTS)

### Excepted Output

0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Faf4a** [comment]
Needs testing.

**Comment by Faf4a** [comment]
It works as expected for me, returns NaN when cooldown doesn't exists/expired and returns MS when not expired.

**Comment by Faf4a** [comment]
Not a bug.
