### ISSUE TITLE
Database | aoi.db

### ISSUE THREAD

**Issue by notadminnn** [aoijs/aoi.js#545]
### Bug Type

Database

### Message:

"I just want to say and request like that the developer try to take like 1-3 days of free time and then that all developers like team up and fix aoi.db completly. just like once to get the database fixed..."

### Version of aoi.js

v6.6.1

### Version of Node.js

v16.11.0 (Lowest)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by Faf4a** [comment]
Nobody within the team really has experience with the functionality of aoi.db except @USERSATOSHI.

As I know it's a custom made, JSON based database.

**Comment by notadminnn** [comment]
> Nobody within the team really has experience with the functionality of aoi.db except @USERSATOSHI.
> 
> As I know it's a custom made, JSON based database.

erm... well that sucks.....

**Comment by Faf4a** [comment]
The duplication error doesn't seem to occur anymore in my case, tested with 4000+ values within the same variable.

Used:
aoi.db github version
aoi.js github version

**Comment by Faf4a** [comment]
Works as expected in both development versions, any bugs will be fixed by Ayaka.

Refer to #542
