### ISSUE TITLE
$alwaysExecute as an event type

### ISSUE THREAD

**Issue by papaaj** [aoijs/aoi.js#548]
### Featuring Type

Callback

### So, what is it about?

I think $alwaysExecute should be as an event type, for example:

module.exports = [{
    type: "always-execute",
    name: "command",
    code: `

`}

idk if this was suggested, but I didn't see any similiar post

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Faf4a** [comment]
Technically it's just the "messageCreate" event without the check for prefix.

**Comment by Leref** [comment]
It can be as an event type but it's fine how it is for now.
