### ISSUE TITLE
"channelID" field in $awaitMessages, $reactionsCollector, $awaitReactions

### ISSUE THREAD

**Issue by Eduard1221** [aoijs/aoi.js#55]
## Type
- [ ] Function: \$awaitMessages, $awaitReactions, $reactionCollector
- [ ] Suggestion: add a field called "channelID" in $awaitMessages, $awaitReactions, $reactionCollector

## Description
This will make the bot to await replies/reactions in a different channel.

**Comment by DiscordBond** [comment]
@Eduard1221 added in next update
