### ISSUE TITLE
Longer max duration for $setTimeout 

### ISSUE THREAD

**Issue by Modyes** [aoijs/aoi.js#554]
### Featuring Type

Function

### So, what is it about?

$setTimeout ends instantly if you set a duration above 21d which is kinda short so I was hoping if we can extend the maximum possible duration for $setTimeout to maybe a year or more?
or maybe if it's not possible for $setTimeout to have that, is there any other alternative way? like a code or an addition function, maybe loops.. idk you guys are the experts in this

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Faf4a** [comment]
I was able to reproduce this in 6.1 and below but not in 6.6 and above.

**Comment by Modyes** [comment]
Well I'm on 6.7.5 (github)

**Comment by Modyes** [comment]
bump?

**Comment by Faf4a** [comment]
this can be fixed with some tricky stuff but

the limitation is basically the 32 bit int limit meaning 2147483647ms or about 25 days

**Comment by Modyes** [comment]
what does this mean? so we can't have longer than 25 days even after the fix?

**Comment by Faf4a** [comment]
after the fix you could yes

**Comment by Modyes** [comment]
can't it be longer than that?

**Comment by Faf4a** [comment]
> can't it be longer than that?

Pushed a fix to the github version, should work now.

I'll reopen if any bugs occur.
