### ISSUE TITLE
v6.10 Tracker

### ISSUE THREAD

**Issue by Faf4a** [aoijs/aoi.js#558]
This will be the Tracker for 6.10

All changes are listed below.

Current Linked PRs:

- None

**Comment by USERSATOSHI** [comment]
cant this be converted into a milestone ??

**Comment by Faf4a** [comment]
> cant this be converted into a milestone ??

it's a milestone, no clue how to pin the milestone though

**Comment by Faf4a** [comment]
using milestone instead
