### ISSUE TITLE
New V6 Interpreter

### ISSUE THREAD

**Issue by USERSATOSHI** [aoijs/aoi.js#559]
### Featuring Type

Others

## About
A new interpreter for aoi.js that can handle top to down + bottom to up code parsing

### Features
* faster execution with less memory overhead
* $if getting proper support
* interpreter based functions 
* top down + bottom up code execution

**Comment by Cyberghxst** [comment]
What's the current status of this? 🤔

**Comment by Faf4a** [comment]
not even started because we dont know what leref wants

**Comment by Leref** [comment]
Incorrect, I am not in charge of that interpreter possible rewrite anymore.
@USERSATOSHI was working on it and supposedly has finished, up to him if he wishes to use it or not.
Regardless v7 has been prioritized now.

**Comment by Faf4a** [comment]
not planned until v7 anymore
