### ISSUE TITLE
$timeoutList

### ISSUE THREAD

**Issue by Modyes** [aoijs/aoi.js#562]
### Featuring Type

Function

### So, what is it about?

We all know that timeouts now have a specific code that can be used to $stopTimeout but well that code sometimes gets lost if it's never been stored in a var. 
$timeoutList will help us get rid of that problem and let us get a list of all the active timeouts and their codes. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Faf4a** [comment]
Thank you for this suggestion! We will consider adding this.

**Comment by Faf4a** [comment]
This was added in [6452125](https://github.com/AkaruiDevelopment/aoi.js/commit/64521258c2897a1aa9be2a7f4c44f505ddac04f7)!

**Comment by Modyes** [comment]
Are you sure this function only gets active timeouts? cause I think it gets all the timeouts that were ever created on the bot.
Also it kinda doesn't show the timeout name along with the code which is the most important part of the function, how am I gonna know which is which?

Pretty long list for only active timeouts, don't you think?
![image](https://github.com/AkaruiDevelopment/aoi.js/assets/84382848/d2da4e0e-bf26-45f7-b807-45f6fdeed591)
![image](https://github.com/AkaruiDevelopment/aoi.js/assets/84382848/4783b312-9ff0-49a2-b0e1-413b64e9412a)

**Comment by Faf4a** [comment]
Oh, yeah we didn't actually delete old timeouts before. so..

**Comment by Faf4a** [comment]
And we don't save the executed command in the property, pretty sure.

```json
"setTimeout_768120":{"value":{"__duration__":1760843227172,"__timeoutName__":"timeout","__id__":768120,"__timeoutIds__":[]}
```

**Comment by Modyes** [comment]
So.. what we gonna do?
