### ISSUE TITLE
voicestateupdate error

### ISSUE THREAD

**Issue by NeonGamerBot-QK** [aoijs/aoi.js#57]
## Type
- [ ] ~~Functions: \<Function Name>~~
- [x] Callbacks: \voice state updates
- [ ] ~~Handlers: \<Handler Type>~~
- [ ] Others: \______ 

Code used:
```
a voice state update
```

More:
- Aoi.js version: 1.0.1
- Node.js version: 12
- Operating system: linxus

Screenshots (If any): Image or Link
![image](https://user-images.githubusercontent.com/58448036/116815295-d2e2ff00-ab2a-11eb-8875-5ffb854ef1ce.png)
**This stops the whole program on error **

**Comment by USERSATOSHI** [comment]
> ## Type
> * [ ]  ~Functions: <Function Name>~
> * [x]  Callbacks: \voice state updates
> * [ ]  ~Handlers: <Handler Type>~
> * [ ]  Others: ______
> 
> Code used:
> 
> ```
> a voice state update
> ```
> 
> More:
> 
> * Aoi.js version: 1.0.1
> * Node.js version: 12
> * Operating system: linxus
> 
> Screenshots (If any): Image or Link
> ![image](https://user-images.githubusercontent.com/58448036/116815295-d2e2ff00-ab2a-11eb-8875-5ffb854ef1ce.png)
> **This stops the whole program on error **

@NeonGamerBot-QK ok I will take a look on this
