### ISSUE TITLE
Bug: $globalUserLeaderboard broken in v6.8

### ISSUE THREAD

**Issue by VishvaasKr** [aoijs/aoi.js#587]
### Bug Type

Function

### Bugged Function

```js
module.exports = [{
name: "leaderboard",
type: "interaction",
prototype: "slash",
code: `
$InteractionFollowUp[{newEmbed:{title:Global Leaderboard}{description:$globalUserLeaderBoard[time;desc;{top}) {username};10;1;capsule]}{color:#0a9afa}}{actionRow:{button:Next:1:lb1:false:1227352256471502919}}]
$InteractionDefer[false]
`}]
```

### Version of aoi.js

v6.8

### Version of Node.js

v16.11.0 (Lowest)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Faf4a** [comment]
Can you define broken? @Vishvaas06

**Comment by VishvaasKr** [comment]
It's fixed in github version though but here broken means that it arranges the leaderboard randomly

**Comment by Faf4a** [comment]
That's the fault on aoi.db's side as it uses the sort() function from there

cc @USERSATOSHI

**Comment by USERSATOSHI** [comment]
has been fixed on db side on github
