### ISSUE TITLE
Silent Messages

### ISSUE THREAD

**Issue by dogukancim** [aoijs/aoi.js#589]
### Featuring Type

Function

### So, what is it about?

Silent messages, which are a feature of Discord, can be added in as a function, such as **$silentMessages**.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by USERSATOSHI** [comment]
this can be added via {flag} tag  in parser under {options}
and $setMessageFlag function for default functions @Faf4a

**Comment by dogukancim** [comment]
> this can be added via {flag} tag in parser under {options} and $setMessageFlag function for default functions @Faf4a

This is an awesome idea.

**Comment by Faf4a** [comment]
#604
