### ISSUE TITLE
Bug: Timeouts break on restart

### ISSUE THREAD

**Issue by Modyes** [aoijs/aoi.js#590]
### Bug Type

Function

### Bugged Function

```js
$setTimeout or the timeout callback idk
```

### Version of aoi.js

v6.8.0

### Version of Node.js

v20.10.0 (LTS)

### Excepted Output

Timeouts should still work even when you restart the bot

### Relevant log output

```shell
Timeouts you've set never end after the restart.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Modyes** [comment]
Note: I'm on aoi.js v6.8.0 (github)

**Comment by atlasfyber** [comment]
**I can confirm this issue from my experience with 6.8.0;** timeouts never end, although they are still registered in the database.

**Comment by Modyes** [comment]
@USERSATOSHI @Faf4a

**Comment by Faf4a** [comment]
will check
