### ISSUE TITLE
Bug: $isInteger

### ISSUE THREAD

**Issue by lawerth** [aoijs/aoi.js#599]
### Bug Type

Function

### Bugged Function

```js
$isInteger
```

### Version of aoi.js

v6.7.1

### Version of Node.js

v21.4.0 (Current)

### Excepted Output

Even if we enter an integer into the function, it returns "false". 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Leref** [comment]
Fixed in 0da8957344f9d1f5bb3d15c8a75795c1e7e8b319.
