### ISSUE TITLE
Bug: $setTimeout bug

### ISSUE THREAD

**Issue by MistiDev** [aoijs/aoi.js#605]
### Bug Type

Function

### Bugged Function

```js
v6.8.0
function/callback ?


module.exports = [{
    name: "test",
    code: `$setTimeout[test;10s;{"chi":"$channelID"}]`
},{
    name: "test",
    type: "timeout",
    code: `$channelSendMessage[$timeoutData[chi];test]`
}]
```

### Version of aoi.js

v6.7.1

### Version of Node.js

v20.10.0 (LTS)

### Excepted Output

$setTimeout never ends, if you restart the bot, the timeout is always repeated, that is, it will send a "test" message

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by OmkumarMangukiya** [comment]
## use clearTimeout() it will clear the timeout and the bot wont send the test message

**Comment by MistiDev** [comment]
> ## use clearTimeout() it will clear the timeout and the bot wont send the test message

this is a bug and i reported it, i can use clearTimeout() but the bug needs to be fixed

**Comment by Faf4a** [comment]
Update to latest, this was fixed
