### ISSUE TITLE
Bug: Event

### ISSUE THREAD

**Issue by GBlade0607** [aoijs/aoi.js#607]
### Bug Type

Handler

### Bugged Function

```js
module.exports = {
name: "İsim Log",
type: "memberUpdate",
channel: "1242748212209647716",
code:
`
$title[Kullanıcı İsmi Değiştirildi]
$color[Orange]
$footer[$formatDate[$datestamp;DD/MM/YYYY - $hour:$minute]]
$timezone[Turkey]

$addField[Değiştirilme Zamanı;<t:$truncate[$divide[$datestamp;1000]]:R>]
$addField[Eski Nick;$oldMember[nick]]
$addField[Yeni Nick;$newMember[nick]]
$addField[Kullanıcı;$username[$get[id]] | <@$get[id]>]

$let[id;$newMember[id]]
`
}
```

### Version of aoi.js

v6.8.0

### Version of Node.js

v21.4.0 (Current)

### Excepted Output

Old Name - New Name log

![image](https://github.com/aoijs/aoi.js/assets/152855173/2f9c3ef0-d6a9-47ad-9f55-f1ca3e1653b0)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by USERSATOSHI** [comment]
i still don't know what the issue actually is @GBlade0607  can you elaborate ?

**Comment by USERSATOSHI** [comment]
also there is $onlyif to restrict the cmd trigger to only happen when there is a nickname change , also try adding that

**Comment by Faf4a** [comment]
stale, closing
