### ISSUE TITLE
Bug: Button, SelectMenu Parser (v6.8.0)

### ISSUE THREAD

**Issue by lawerth** [aoijs/aoi.js#609]
### Bug Type

Function

### Bugged Function

```js
$sendMessage[Hello!
 {actionRow:
 
  {button:Hello!:secondary:customID:false:$get[emoji]}
 }
]

$let[emoji;<:bitcoin:1064159459460517958>]
```

### Version of aoi.js

v6.7.1

### Version of Node.js

v21.4.0 (Current)

### Excepted Output

The button in the code was supposed to work normally. But in the new version (v6.8.0) this code no longer works. It gives an "Invalid emoji" error. Please, correct it.

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by atlasfyber** [comment]
As temporary solution, you can just add the emoji ID.

`{button:Hello!:secondary:customID:false:1064159459460517958}`

Or you can also use your $get function for this, if needed.

**Comment by Faf4a** [comment]
looking into this, does this still occur in 6.8?

**Comment by atlasfyber** [comment]
> looking into this, does this still occur in 6.8?

Yup!
