### ISSUE TITLE
$ignoreChannels

### ISSUE THREAD

**Issue by falsisdev** [aoijs/aoi.js#61]
## Type
- [x] Functions: \ $ignoreChannels[channelID;channelID;channelID;...;error message]
~~- Callbacks: \<Callback Name>~~
~~- Handlers: \<Handler Type>~~
~~- Others: \______~~

## Description
The use of the command is prohibited on channels whose ID is entered. If used, the entered error message is sent. 
```
bot.command({
name:"hello",
code:`helloooo!
$ignoreChannels[798055313907253279;I was banned from saying hello to you on this channel :(]`
})
```
There is an example in bdfd.

**Comment by Huguitis** [comment]
I like It

**Comment by avixityyt** [comment]
```
bot.command({
name:"hello",
code:`helloooo!
$ignoreChannels[CHANNEL ID;Yk i'm bored when i start to come here lol;GUILD ID]`
})
```

idk made sense in my head so yeah.

**Comment by DiscordBond** [comment]
Channels are global objects so there is no guildID field needed.

**Comment by USERSATOSHI** [comment]
> ## Type
> - [x] Functions: \ $ignoreChannels[channelID;channelID;channelID;...;error message]
> ~~- Callbacks: \<Callback Name>~~
> ~~- Handlers: \<Handler Type>~~
> ~~- Others: \______~~
> 
> ## Description
> The use of the command is prohibited on channels whose ID is entered. If used, the entered error message is sent. 
> ```
> bot.command({
> name:"hello",
> code:`helloooo!
> $ignoreChannels[798055313907253279;I was banned from saying hello to you on this channel :(]`
> })
> ```
> There is an example in bdfd.

ngl I like your idea but it's already possible

you can just add
`
$onlyIf[$checkContains[$channelID;channelid1;channelid2;....]==false; This Channel Is Blacklisted]`

This Works Like $ignoreChannels so Ig There is no need

**Comment by falsisdev** [comment]
> > ## Type
> > - [x] Functions: \ $ignoreChannels[channelID;channelID;channelID;...;error message]
> > ~~- Callbacks: \<Callback Name>~~
> > ~~- Handlers: \<Handler Type>~~
> > ~~- Others: \______~~
> > 
> > ## Description
> > The use of the command is prohibited on channels whose ID is entered. If used, the entered error message is sent. 
> > ```
> > bot.command({
> > name:"hello",
> > code:`helloooo!
> > $ignoreChannels[798055313907253279;I was banned from saying hello to you on this channel :(]`
> > })
> > ```
> > There is an example in bdfd.
> 
> ngl I like your idea but it's already possible
> 
> you can just add
> `
> $onlyIf[$checkContains[$channelID;channelid1;channelid2;....]==false; This Channel Is Blacklisted]`
> 
> This Works Like $ignoreChannels so Ig There is no need

Oky I will try, thank you.

**Comment by USERSATOSHI** [comment]
@falsisdev so is it working ?

**Comment by Kino7916** [comment]
> > ## Type
> > 
> > * [x]  Functions: \ $ignoreChannels[channelID;channelID;channelID;...;error message]
> >   ~- Callbacks: <Callback Name>~
> >   ~- Handlers: <Handler Type>~
> >   ~- Others: ______~
> > 
> > ## Description
> > The use of the command is prohibited on channels whose ID is entered. If used, the entered error message is sent.
> > ```
> > bot.command({
> > name:"hello",
> > code:`helloooo!
> > $ignoreChannels[798055313907253279;I was banned from saying hello to you on this channel :(]`
> > })
> > ```
> > 
> > 
> > There is an example in bdfd.
> 
> ngl I like your idea but it's already possible
> 
> you can just add
> ` $onlyIf[$checkContains[$channelID;channelid1;channelid2;....]==false; This Channel Is Blacklisted]`
> 
> This Works Like $ignoreChannels so Ig There is no need
> @falsisdev

This method can be used, no need for addition.

**Comment by falsisdev** [comment]
> @falsisdev so is it working ?

Yeah

**Comment by falsisdev** [comment]
> > > ## Type
> > > 
> > > * [x]  Functions: \ $ignoreChannels[channelID;channelID;channelID;...;error message]
> > >   ~- Callbacks: <Callback Name>~
> > >   ~- Handlers: <Handler Type>~
> > >   ~- Others: ______~
> > > 
> > > ## Description
> > > The use of the command is prohibited on channels whose ID is entered. If used, the entered error message is sent.
> > > ```
> > > bot.command({
> > > name:"hello",
> > > code:`helloooo!
> > > $ignoreChannels[798055313907253279;I was banned from saying hello to you on this channel :(]`
> > > })
> > > ```
> > > 
> > > 
> > > There is an example in bdfd.
> > 
> > ngl I like your idea but it's already possible
> > 
> > you can just add
> > ` $onlyIf[$checkContains[$channelID;channelid1;channelid2;....]==false; This Channel Is Blacklisted]`
> > 
> > This Works Like $ignoreChannels so Ig There is no need
> > @falsisdev
> 
> This method can be used, no need for addition.

Oky
