### ISSUE TITLE
Bug: $setUserVar Does Not Save New Data Quickly

### ISSUE THREAD

**Issue by dogukancim** [aoijs/aoi.js#611]
### Bug Type

Function

### Bugged Function

```js
$setUserVar[action-verification;$toUpperCase[$randomString[6]]]
```

### Version of aoi.js

v6.8.0

### Version of Node.js

v20.13.1

### Excepted Output

New data should be saved as soon as possible. However, this does not work like that right now; new data is recorded after an indefinite period of time.

### Relevant log output
*There is no error in the console.*

### Image about the problem

![image](https://github.com/aoijs/aoi.js/assets/78941156/7ff20d84-2496-44d4-976d-798a9ba743e8)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dogukancim** [comment]
This problem may be caused by aoi.db or aoi.js. So I'm not sure if I opened it to the wrong repository. ($setUserVar is aoi.js function, but its action is in aoi.db)

**Comment by baka-aho** [comment]
still full of errors i see;
![shikimori-shikimoris-not-just-cute](https://github.com/user-attachments/assets/f226fdb6-32e6-4814-8060-c5ff8535fcfa)

**Comment by Leref** [comment]
This is related towards aoi.db.
Open an issue over there.
