### ISSUE TITLE
Bug: $createArray creates an index when the input is empty (the version is 6.8.0)

### ISSUE THREAD

**Issue by yungheheh** [aoijs/aoi.js#612]
### Bug Type

Function

### Bugged Function

```js
$getArray[test]      returns [""]
$createArray[test;]
```

### Version of aoi.js

v6.7.1

### Version of Node.js

v21.4.0 (Current)

### Excepted Output

[]

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Faf4a** [comment]
can reproduce

**Comment by USERSATOSHI** [comment]
@yungheheh that is expected cause you are telling the function to create an array with 1 element which is an empty string 

if u want to create an empty array $createArray[test] would do this

**Comment by yungheheh** [comment]
> @yungheheh that is expected cause you are telling the function to create an array with 1 element which is an empty string 
> 
> if u want to create an empty array $createArray[test] would do this
> 
> 

Then I suggest to make docs Say that the elements field isnt required
