### ISSUE TITLE
Bug: $roundTenth

### ISSUE THREAD

**Issue by lawerth** [aoijs/aoi.js#617]
### Bug Type

Function

### Bugged Function

```js
$roundTenth[503.6972]
```

### Version of aoi.js

v6.7.1

### Version of Node.js

v21.4.0 (Current)

### Excepted Output

Expected output: "503.70"
Error: AoiError: Invalid Decimal Position Provided In [503.6972]
Version: 6.8.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by USERSATOSHI** [comment]
@lawerth hi , you need to provide the round off decimal in roundTenth function so a proper usage might be 

$roundTenth[503.6972;2] // 503.70

**Comment by lawerth** [comment]
@USERSATOSHI I understand I looked at aoi.js docs. It was used incorrectly in the example there. It would be nice if you fix it.

**Comment by AstrooKai** [comment]
> @USERSATOSHI I understand I looked at aoi.js docs. It was used incorrectly in the example there. It would be nice if you fix it.

Thanks for letting us know, @lawerth! We've updated the documentation to reflect the correct usage. We apologize for any inconvenience.

_Fixed with [#180](https://github.com/aoijs/website/pull/180)_
