### ISSUE TITLE
Bug: conditions checks break with vars which are not changed from the default value (6.8.0)

### ISSUE THREAD

**Issue by papaaj** [aoijs/aoi.js#618]
### Bug Type

Function

### Bugged Function

```js
$checkCondition[$let[test]!=$getGuildVar[prefix]] //Returns true
$let[test;!]


prefix: "!" //Default var value is !
```

### Version of aoi.js

v6.7.1

### Version of Node.js

v16.11.0 (Lowest)

### Excepted Output

false

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Modyes** [comment]
That's not a bug, you have "!" as your default var value so naturally when you're trying to get your guild var it will return the default value unless changed.
that's just how it works
