### ISSUE TITLE
Bug: Custom Function Type: "aoijs" Doesnt Work

### ISSUE THREAD

**Issue by dhruvakalur** [aoijs/aoi.js#636]
### Bug Type

Callback

### Bugged Function

```js
bot.functionManager.createFunction({
    name: "$function", // custom function name, can be anything.
    params: [ "parameter", ... ], // function parameters, $function[parameter;parameter]
    type: "aoi.js", // custom function type
    code: "..." // the code that will be executed
});
```

### Version of aoi.js

v6.7.1

### Version of Node.js

v21.4.0 (Current)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dhruvakalur** [comment]
![Screenshot 2024-08-03 231247](https://github.com/user-attachments/assets/f62b586b-bf41-4eca-9fba-42e421440d67)

**Comment by atlasfyber** [comment]
It works fine for me, probably the documentation is outdated.

**Comment by Faf4a** [comment]
This should be fixed as well in one of the latest commits.
