### ISSUE TITLE
HTTP Functions Refactor

### ISSUE THREAD

**Issue by Asayukiii** [aoijs/aoi.js#640]
### Featuring Type

Function

### So, what is it about?

I believe that currently the attention that has been given to HTTP functions has been **null**.
There are some features that could be implemented for this area, and not just have `$httpRequest` and `$jsonRequest`.
> what if I want to know which type of content type the API return? (currently implemented on $httpRequest but I started feeling that is not the best idea) / what if I want to know the status code of the API response / etc, etc...

The idea is: **"give you more control over the requests you can make with your client"**.

I would like to do this work myself, but I would like to know if it will be accepted.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Leref** [comment]
Seeing this I absolutely agree it can be improved.
If any suggestions, please feel free to make a Pull Request and show your ideas and it can be further discussed.
