### ISSUE TITLE
Bug: $isCommandInteraction

### ISSUE THREAD

**Issue by atlasfyber** [aoijs/aoi.js#642]
### Bug Type

Function

### Bugged Behavior

```js
module.exports = [{
    name: "test",
    code: ` 
    Hello!
    $addButton[1;Click Me!;primary;ButtonID;false]

    `
    },{
    name: "ButtonID",
    type: "interaction",
    prototype: "button",
    code:`
	$isCommandInteraction
    $interactionReply[Hello World!;everyone;false]
  `
}]

Second usage:

module.exports = [{
    name: "test-slash",
    prototype: "slash",
    type: "interaction",
    code: ` 
$isCommandInteraction
$interactionReply[Hi]`
}]
```

### Version of aoi.js

v6.8.x

### Version of Node.js

v20.16.0 (LTS)

### Excepted Output

true (or false)

### Relevant log output

isCommand() {
    return this.type === InteractionType.ApplicationCommand;
  }

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Faf4a** [comment]
not a but, use $iscomponentinteraction

**Comment by Faf4a** [comment]
turns out i didnt read this correctly

**Comment by atlasfyber** [comment]
Also it seems `$addSelectMenu` with `channel` type value is also broken.

```
$addSelectMenu[1;channel;yourCustomID;This is a placeholder!;1;5;false;A Option:Description of option A:anotherCustomID:false;B Option:Description of option B:andAnotherCustomID:true]
```

Can we include this in this issue thread or should I open a new one for this?

**Comment by Faf4a** [comment]
You can't provide options with the channel type, it's just

`$addSelectMenu[1;channel;yourCustomID;This is a placeholder!;1;5;false]`

in this case
