### ISSUE TITLE
Bug: Timestamp

### ISSUE THREAD

**Issue by GBlade0607** [aoijs/aoi.js#650]
### Bug Type

Function

### Bugged Behavior

```js
<t:$truncate[$divide[$creationDate[$authorID;ms];1000]]:R> => 2 years ago == correct
$formatDate[$truncate[$divide[$creationDate[$authorID;ms];1000]];DD/MM/YYYY] => 1/20/1970 == no correct

why!?

Node: 21
```

### Version of aoi.js

v6.8.x

### Version of Node.js

v20.16.0 (LTS)

### Excepted Output

![image](https://github.com/user-attachments/assets/9fd380d7-5175-41f3-9b74-7abd42790b5e)

### Relevant log output

![image](https://github.com/user-attachments/assets/497ee42f-6578-4d92-a6a0-7b6ee0e50e2f)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Faf4a** [comment]
$formatDate takes MS and not epoch.

Using just $creationDate within formatDate should be sufficient.
