### ISSUE TITLE
$if statement runs both sides

### ISSUE THREAD

**Issue by LightslicerGP** [aoijs/aoi.js#664]
### Bug Type

Function

### Bugged Behavior

```js
module.exports = [
  {
    name: "whois",
    code: `
        $clientTyping    
        $reply[$messageID;true]

        $if[$isNumber[$noMentionMessage]==true;
            true $userTag[$message];
            false $userID[$message]
        ]
    `,
  },
];
```

### Version of aoi.js

v6.8.x

### Version of Node.js

v20.16.0 (LTS)

### Excepted Output

![image](https://github.com/user-attachments/assets/7313e7c0-0623-44cb-95e5-ca69270d48fe)

So the issue is the $if functions (and many others like it iirc) work like this:
1. Check the comparison
2. Run both sides of the function
3. Disregard any data that is NOT on the correct side

The problem is, if ONE side (doesn't matter which since they both run anyway) runs into an error, the ENTIRE thing breaks and doesn't run.

What it _should_ do is NOT run the side that doesn't match the condition, so it never gets that error in the first place.

It should only run one side, the side that matches weather it is True or false, but BOTH sides run and it causes problems.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by LightslicerGP** [comment]
Update: this might be relevant to the issue: https://github.com/aoijs/aoi.js/issues/559

**Comment by Faf4a** [comment]
this is a known issue, related to #559
