### ISSUE TITLE
Bug: $awaitMessages error parameter breaks when using embed

### ISSUE THREAD

**Issue by LightslicerGP** [aoijs/aoi.js#666]
### Bug Type

Function

### Bugged Behavior

```js
bot.command({
  name: "test",
  code: `
    $awaitMessages[$channelID;$authorID;10s;yes,y,no,n;yes,yes,no,no;
      {newEmbed:
        {title:No reply, canceled}
        {color:#80ff80}
      }
      {reply:$messageID:true}
    ]
    `,
});
```

### Version of aoi.js

v6.8.x

### Version of Node.js

v22.5.1 (Current)

### Excepted Output

after waiting 10+ seconds it should make an embed, but it breaks (not having the embed but just regular text works fine)

### Relevant log output

c:\Users\LightslicerGP\node_modules\aoi.js\src\classes\AoiError.js:120
                    msg = await (await d.util.getMessage(channel, extraOptions.reply?.message)).reply(options).catch((e) => {
                                         ^

TypeError: Cannot read properties of undefined (reading 'util')
    at AoiError.makeMessageError (c:\Users\LightslicerGP\node_modules\aoi.js\src\classes\AoiError.js:120:42)
    at c:\Users\LightslicerGP\node_modules\aoi.js\src\functions\awaitMessages.js:75:28

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Faf4a** [comment]
Found the error, function is missing the context of `d`

https://github.com/aoijs/aoi.js/blob/v6/src/functions/awaitMessages.js#L78-L80
