### ISSUE TITLE
messageCollector

### ISSUE THREAD

**Issue by masterguy35** [aoijs/aoi.js#68]
## New Function
- Function Name: `$messageCollector`

## Description
`$messageCollector` is as same as `$reactionCollector` but it collects every messages in a given channel within a given time. It collects almost Every data in the channel after the collection is started and will store the collection. It collects like usernames, messages, etc.,
It already exists in Discord.JS but idk how to make it, This is the [Collector](https://discord.js.org/#/docs/main/stable/class/Collector) docs.

**Comment by LightnerDev** [comment]
Don't you think `$awaitMessages` would do the trick?

**Comment by masterguy35** [comment]
> Don't you think `$awaitMessages` would do the trick?

`$messageCollector` is totally different from `$awaitMessages`

**Comment by DiscordBond** [comment]
> Don't you think `$awaitMessages` would do the trick?

$awaitMessages is a one time event, $messagesCollector would be permanent within the given time
