### ISSUE TITLE
$playSpotify playing the playlist only for 30s. Please fix this as i asked in support many said the same.

### ISSUE THREAD

**Issue by BeastBoyADI** [aoijs/aoi.js#74]
## Type
- [ x ] Functions: \$queue
- [ ] Callbacks: \<Callback Name>
- [ ] Handlers: \<Handler Type>
- [ ] Others: \______

Code used:
```
Your Code Here
```

More:
- Aoi.js version:1.0.6
- Node.js version:14.16.0
- Operating system:linux

Screenshots (If any): Image or Link

**Comment by BeastBoyADI** [comment]
Please fix this. As its giving much problems. As i think the problem is with the $queue as when my friend changed some queue codes in my testing bot's code it started to work but it was only playing 20 songs from a 90 songs playlist. so if the queue code is fixed then maybe it will be fixed. Please fix it.

**Comment by XzFirzal** [comment]
$playSpotify works by getting the metadata in spotify then it got the audio format in youtube. It get only 20 songs maybe because it failed on getting it on youtube

**Comment by BeastBoyADI** [comment]
I understood what you are saying but when my friend modified the queue code then only it was playing 20 songs out of 97 songs playlist. So maybe if the $queue function code is changed to some extent it will play all the songs. As other Music bots were able to play all those playlist. Please fix this if u can. As i really wanted to add the song to be played by spotify.

**Comment by BeastBoyADI** [comment]
Before the modification the bot was playing the playlist only for 30 seconds

**Comment by Leref** [comment]
There will be a necessary revamp of $playSpotify in the following updates.
