### ISSUE TITLE
 bot.botJoinCommand is broken/bugged

### ISSUE THREAD

**Issue by aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa77** [aoijs/aoi.js#75]
## Type
- [ ] Functions: \<Function Name>
- [x] Callbacks: \<Callback Name>
- [ ] Handlers: \<Handler Type>
- [ ] Others: \______

Code used:
```
 bot.botJoinCommand({
  channel: "838023671280435245", 
  code: `
  $title[i have been added in $serverName]
  $description[
    Server User Count | $membersCount
    Owner | $userTag[$ownerID]]
    $footer[i am in $serverCount Guilds!]
    $color[BLUE]`
 });
 bot.onGuildJoin()
 bot.botLeaveCommand({
  channel: "838023671280435245",
  code: `
  $title[i have been kicked in $serverName]
  $description[
    Server User Count | $membersCount
    Owner | $userTag[$ownerID]]
    $footer[i am in $serverCount Guilds!]
    $color[RED]`
 });
```

More:
- Aoi.js version: 1.0.6
- Node.js version: discord.js 12
- Operating system: Windows 10
ISSUE: bot.botJoinCommand is broken as it returns: invalid channel ID but bot.botLeaveCommand works with the same channel ID.
Screenshots (If any): Image or Link

**Comment by USERSATOSHI** [comment]
@aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa77 specify the error

what part is bugged and what error it gave in console

**Comment by USERSATOSHI** [comment]
@aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa77 ^

**Comment by epic2305** [comment]
ae

**Comment by Kino7916** [comment]
The source code for botJoinCommand and botLeaveCommand are the same, no such difference related to `channel` was found based on what had Difference Text Detector said.
![Screenshot_917](https://user-images.githubusercontent.com/73807155/117236863-d4c30000-ae53-11eb-9986-4d3f663ddf59.png)
