### ISSUE TITLE
reactionRemoveCommand not working

### ISSUE THREAD

**Issue by Miduwu** [aoijs/aoi.js#76]
## Type
- [x] Bug fix: yes
- [ ] Functions: \<Function Name>
- [ ] Callbacks: \<Callback Name>
- [ ] Handlers: \<Handler Type>
- [ ] Others: \______

Code used:
```
module.exports = ({
    channel: "$channelID",
    code: `$channelSendMessage[$channelID;popo;no]
$onlyif[$emojiToString==❤️;]`,
    type: 'reactionRemoveCommand'
})
```

More:
- Aoi.js `1.0.6`
- Node.js idk
The message is not sent, and this is spamming the console. Many of my reactionRemove commands are not working now. But that code in the reactionAdd commands works.

![popo](https://media.discordapp.net/attachments/827711429233868800/839018985843327056/unknown.png)

**Comment by Miduwu** [comment]
$channelUsed does not work either :(

**Comment by USERSATOSHI** [comment]
> $channelUsed does not work either :(
