### ISSUE TITLE
$getServerTemplate

### ISSUE THREAD

**Issue by RedentSama** [aoijs/aoi.js#78]
## Type
- [ ] Functions: \
- [ ] Callbacks: \
- [ ] Handlers: \
- [ ] Others: \______

## Code Used
```module.exports = {
  name: "getServerTemplate",
  code: `Here is Server Template;
$getServerTemplate`
}```

## Description
Server gives template link

**Comment by falsisdev** [comment]
> 
> 
> ## Type
> - [ ] Functions: \
> - [ ] Callbacks: \
> - [ ] Handlers: \
> - [ ] Others: \______
> 
> ## Code Used
> ```module.exports = {
>   name: "getServerTemplate",
>   code: `Here is Server Template;
> $getServerTemplate`
> }```
> 
> ## Description
> Server gives template link

I think it's ridiculous

**Comment by RedentChan** [comment]
> I think it's ridiculous

by to you.

**Comment by DiscordBond** [comment]
I'm already coding a lot of functions like that to get data of a template or  creating/updating/editing/deleting templates etc. xD
Give me one or two days

**Comment by DiscordBond** [comment]
> I think it's ridiculous

Why do you think it's ridiculous? @falsisdev

**Comment by falsisdev** [comment]
> 
> > I think it's ridiculous
> 
> Why do you think it's ridiculous? @falsisdev 

Why should the bot take a server template so that one person can do it very easily?

**Comment by DiscordBond** [comment]
> > > I think it's ridiculous
> > 
> > 
> > Why do you think it's ridiculous? @falsisdev
> 
> Why should the bot take a server template so that one person can do it very easily?

To let the bot work with that information? So it grabs the url and can use it? Like in discord.js?

**Comment by andrewthemeow** [comment]
> > > I think it's ridiculous
> > 
> > 
> > Why do you think it's ridiculous? @falsisdev
> 
> Why should the bot take a server template so that one person can do it very easily?

Mobile users.

**Comment by USERSATOSHI** [comment]
closed due to inactivity
