### ISSUE TITLE
$handlerror

### ISSUE THREAD

**Issue by NeonGamerBot-QK** [aoijs/aoi.js#79]
## Type
- [x] Functions: $handlererror[awaited command name]
- [ ] Callbacks: \<Callback Name>
- [ ] Handlers: \<Handler Type>
- [ ] Others: \______

## Description
this will let `{error}` be handled in an awaited command for error handling

**Comment by USERSATOSHI** [comment]
@NeonGamerBot-QK I mean you can use

 `$suppressErrors[{error}] `

or 

error: `$channelSendMessage[channelid;$error]`

to handle the error 
so why need another function for that ?

**Comment by NeonGamerBot-QK** [comment]
> @NeonGamerBot-QK I mean you can use
> 
> `$suppressErrors[{error}] `
> 
> or
> 
> error: `$channelSendMessage[channelid;$error]`
> 
> to handle the error
> so why need another function for that ?

for sending errors to you, the dev! and `$error` is djs only

**Comment by USERSATOSHI** [comment]
> > @NeonGamerBot-QK I mean you can use
> > 
> > `$suppressErrors[{error}] `
> > 
> > or
> > 
> > error: `$channelSendMessage[channelid;$error]`
> > 
> > to handle the error
> > so why need another function for that ?
> 
> for sending errors to you, the dev! and `$error` is djs only
> 

u can use error: property for sending Interpreter errors
```
bot.command({
name:"name",
error:"$channelSendMessage[channelid you want;$error]",
code:`
your code
`
})```

so when interpreter sends error in console

error property will get triggered and it will send message to the channel you provided

@NeonGamerBot-QK

**Comment by DiscordBond** [comment]
I think they mean something to log Aoi.JS errors in a log channel like if something like ❌ failed to give roles! comes the dev can set in the log what user has issues or what functions aren’t working well… to log bot errors in a dev's server

**Comment by USERSATOSHI** [comment]
> I think they mean something to log Aoi.JS errors in a log channel like if something like ❌ failed to give roles! comes the dev can see in the log what user has issues or what functions aren’t working well… to log bot errors in a dev's server

hmm if that's the case ,... ig

**Comment by NeonGamerBot-QK** [comment]
so will it be added?

**Comment by USERSATOSHI** [comment]
> so will it be added?

@NeonGamerBot-QK I will try making it in form of callbacks so yeah if I made it then I will pr it

**Comment by NeonGamerBot-QK** [comment]
ok,
