### ISSUE TITLE
$serverLeaderboard

### ISSUE THREAD

**Issue by RedentSama** [aoijs/aoi.js#80]
**Description**
```
Creates an server leaderboard```

**Usage**
```
$serverLeaderboard[variable;asc/desc (optio al);{top} - {servername} - {value};list (optional);page (optional)]```

**Comment by DiscordBond** [comment]
I’ll try it

**Comment by USERSATOSHI** [comment]
> I’ll try it

uh...

i am already done with it just need couple of bug fixes
