### ISSUE TITLE
Remove $clientID

### ISSUE THREAD

**Issue by KASKUSTTV** [aoijs/aoi.js#81]
## Description
Whats the difference between `$clientID` and `$client[id]`?

**Comment by soudblox** [comment]
They're both the same, $clientID was made before $client[] was a thing, and still used in some commands

If they just remove it, it will break commands that is currently using it

**Comment by Mr-Catty** [comment]
$client is **compact function** and has many properties. But $clientID doesn't have multiple properties.

**Comment by KASKUSTTV** [comment]
ohh ok
