### ISSUE TITLE
$if statement bug

### ISSUE THREAD

**Issue by KASKUSTTV** [aoijs/aoi.js#82]
## Type
- [x] Functions: \<Function Name>
- [ ] Callbacks: \<Callback Name>
- [ ] Handlers: \<Handler Type>
- [ ] Others: \______

Code used:
```js
$if[$memberExists[$get[user]]==true;]
$title[$userTag[$get[user]]]
$description[Here is some information about $username[$get[user]]]
$addField[:calendar: Account Creation;$creationDate[$get[user];date];yes]
$addField[:calendar: Joined $serverName;$memberJoinedDate[$get[user];date];yes]
$color[RANDOM]
$thumbnail[$replaceText[$userAvatar[$get[user]];.webp;.png]]
$elseIf[$memberExists[$get[user]]==false;]
$title[$userTag[$get[user]]]
$description[Here is some information about $username[$get[user]]]
$addField[:calendar: Account Creation;$creationDate[$get[user];date];yes]
$addField[:id: User ID;$get[user];yes]
$addField[:pencil2: Display Name;$username[$get[user]];yes]
$color[RANDOM]
$thumbnail[$replaceText[$userAvatar[$get[user]];.webp;.png]]
$endelseIf
$endIf
$onlyIf[$userExists[$get[user]]==true;Cannot find user]
$let[user;$findUser[$message[1]]]
```

**Comment by KASKUSTTV** [comment]
This return ```js
$title[$userTag[$get[user]]]
$description[Here is some information about $username[$get[user]]]
$addField[:calendar: Account Creation;$creationDate[$get[user];date];yes]
$addField[:id: User ID;$get[user];yes]
$addField[:pencil2: Display Name;$username[$get[user]];yes]
$color[RANDOM]
$thumbnail[$replaceText[$userAvatar[$get[user]];.webp;.png]]
```
even the user is in the server ^^

**Comment by USERSATOSHI** [comment]
@KASKUSTTV there is no second field in $if

so why did u add ; at last

**Comment by KASKUSTTV** [comment]
i

> @KASKUSTTV there is no second field in $if
> 
> so why did u add ; at last

i thought it will and the `$if`
and all my code with `$if` are with `;` in the last but its all working fine before

**Comment by KASKUSTTV** [comment]
> This return ```js
> $title[$userTag[$get[user]]]
> $description[Here is some information about $username[$get[user]]]
> $addField[ Account Creation;$creationDate[$get[user];date];yes]
> $addField[ User ID;$get[user];yes]
> $addField[ Display Name;$username[$get[user]];yes]
> $color[RANDOM]
> $thumbnail[$replaceText[$userAvatar[$get[user]];.webp;.png]]
> 
> ```
> even the user is in the server ^^
> ```

i try to remove `;` but still it returning this embed

**Comment by USERSATOSHI** [comment]
> This return ```js
> $title[$userTag[$get[user]]]
> $description[Here is some information about $username[$get[user]]]
> $addField[📆 Account Creation;$creationDate[$get[user];date];yes]
> $addField[🆔 User ID;$get[user];yes]
> $addField[✏️ Display Name;$username[$get[user]];yes]
> $color[RANDOM]
> $thumbnail[$replaceText[$userAvatar[$get[user]];.webp;.png]]
> 
> ```
> even the user is in the server ^^
> ```

because If user exist one is true then it won't go to Member one


switch the position make member one in if and user one in else if

**Comment by KASKUSTTV** [comment]
ok

**Comment by KASKUSTTV** [comment]
@USERSATOSHI can you give an example i cant really understand it, i change the `$if` to `$memberExists[$get[user]]` and `$elseIf` with `$userExists[$get[user]]` but now its not responding

**Comment by USERSATOSHI** [comment]
> @USERSATOSHI can you give an example i cant really understand it, i change the `$if` to `$memberExists[$get[user]]` and `$elseIf` with `$userExists[$get[user]]` but now its not responding

@KASKUSTTV send ur Current code

**Comment by KASKUSTTV** [comment]
> > @USERSATOSHI can you give an example i cant really understand it, i change the `$if` to `$memberExists[$get[user]]` and `$elseIf` with `$userExists[$get[user]]` but now its not responding
> 
> @KASKUSTTV send ur Current code

here 
```js
$if[$memberExists[$get[user]]==true]
$title[$userTag[$get[user]]]
$description[Here is some information about $username[$get[user]]]
$addField[:calendar: Account Creation;$creationDate[$get[user];date];yes]
$addField[:calendar: Joined $serverName;$memberJoinedDate[$get[user];date];yes]
$addField[:id: User ID;$get[user];yes]
$addField[:pencil2: Display Name;$nickname[$get[user]];yes]
$color[RANDOM]
$thumbnail[$replaceText[$userAvatar[$get[user]];.webp;.png]]
$elseIf[$userExists[$get[user]]==true]
$title[$userTag[$get[user]]]
$description[Here is some information about $username[$get[user]]]
$addField[:calendar: Account Creation;$creationDate[$get[user];date];yes]
$addField[:id: User ID;$get[user];yes]
$addField[:pencil2: Display Name;$username[$get[user]];yes]
$color[RANDOM]
$thumbnail[$replaceText[$userAvatar[$get[user]];.webp;.png]]
$endelseIf
$endIf
$onlyIf[$userExists[$get[user]]==true;**Sorry,** I couldn't find anyone named **$message** in this server, maybe try using the user's ID instead?]
$let[user;$findUser[$message[1]]]
```

**Comment by KASKUSTTV** [comment]
@USERSATOSHI

**Comment by USERSATOSHI** [comment]
> @USERSATOSHI

-m![Screenshot_2021-05-06-11-51-46-61.png](https://user-images.githubusercontent.com/73595362/117250855-769d1980-ae61-11eb-89e9-2298b85da70c.png)


use $sendMessage instead

**Comment by XzFirzal** [comment]
`condition` in is individual part of code, can't get any object or var from the outside. It's default behaviour
