### ISSUE TITLE
A perticular var's $getGlobalUserVar is getting stuck to a weird value in all the cmds which contain the $getGlobalUserVar of the var.

### ISSUE THREAD

**Issue by Coder9495** [aoijs/aoi.js#83]
## Type
- [x] Functions: \<not a perticular one, but happening in a $getGlobalUserVar>
- [ ] Callbacks: \<Callback Name>
- [ ] Handlers: \<Handler Type>
- [ ] Others: \______
Happening in most of my commands, like, first it will happen in Commands which contain "$getGlobalUserVar" of a perticular var. Read below.

Hey, there's a bug which makes a perticular part of code gets stuck to a perticular thing, and that's what's happening with me from 2 days. First my epouch var got bugged and I fixed it after hours, as I fixed it, a different var got bugged, and so on 4 more time... this is VERY annoying and I hate this. :(. If you're wondering, I fixed it by changing the var name in bot.variables and the var name in all the cmds. This bug started to happen as I updated to aoi.js 1.0.6 from dbd.js 3.0.6. I do not know what's the actual cause for this, but I am struggling very annoyingly. Kindly do try check why is this happening, and tell me a temporary fix till it's sorted. Ty.

More:
- Aoi.js version: 1.0.6
- Node.js version: Wut?
- Operating system: Android

**Comment by Coder9495** [comment]
If it's Still confusing, I'll tell you how the bug actually happened with me in details. First, my var named "epouch" got bugged, everywhere (everywhere includes ALL Commands) where I used "$getGlobalUserVar[epouch;$mentioned[1;yes]]", the interpreter interpreted it as "GlobalUserVat[epouch]". Hence, where it should give the var value for the user, it responded with "GlobalUserVat[epouch]".

**Comment by Coder9495** [comment]
And to fix that, I changed the var name, and changed it in all the commands which contained the $getGlobalUserVar for the var. But then, it started to happen with a different VAR 👺💢💢💢 and I am pissed. If this gets fixed, there's nothing better.

**Comment by USERSATOSHI** [comment]
you know @Coder9495 you can see the error from interpreter response

it send GlobalUserVa`t`[epouch] so you did a spelling mistake

**Comment by USERSATOSHI** [comment]
and because $getGlobalUserVat is not a Function 
$get gets triggered instead hence sending `GlobalUserVat[epouch]` as response
