### ISSUE TITLE
remove shitcode from your library

### ISSUE THREAD

**Issue by TheFerryn** [aoijs/aoi.js#89]
## Type
- [ ] Functions: \<Function Name>
- [ ] Callbacks: \<Callback Name>
- [ ] Handlers: \<Handler Type>
- [x] Other

## Description
please remove shitcode from your library as soon as possible, and do not force normal coders to cry

**Comment by USERSATOSHI** [comment]
> 
> 
> ## Type
> - [ ] Functions: \<Function Name>
> - [ ] Callbacks: \<Callback Name>
> - [ ] Handlers: \<Handler Type>
> - [x] Other
> 
> ## Description
> please remove shitcode from your library as soon as possible, and do not force normal coders to cry

specify which codes are "shitcode"

**Comment by TheFerryn** [comment]
every single file in this repo contains shitcode lol

**Comment by USERSATOSHI** [comment]
> every single file in this repo contains shitcode lol

well then don't use it

**Comment by Enslavedd** [comment]
> every single file in this repo contains shitcode lol

😡

**Comment by LightnerDev** [comment]
wait what does "shitcode" mean?

**Comment by TheFerryn** [comment]
code which is actually shit 💩

**Comment by falsisdev** [comment]
> code which is actually shit 💩 

You look like a fool like your mother 💩

**Comment by TheFerryn** [comment]
That's everything what a 10 year old javascript kid can say? 🤣
