### ISSUE TITLE
$cpu features & $disk

### ISSUE THREAD

**Issue by falsisdev** [aoijs/aoi.js#90]
- [x] Functions: $cpu[property], $disk

## Description
Features should be added to the $cpu command, for example $cpu[model] or $cpu[platform] $cpu must be $cpu[usage]

## Codes

Model:
```
require ('os').cpus()[0].model
```
Platform :

```
require ('os').platform()
```
And the disk function:
```
module.exports = async (d) => {
    return {
      code: d.command.code.replaceLast(`$disk`, process.memoryUsage().rss / 1024 / 1024),
    };
  };
 ```

### Uh :/
I don't know how the files are modified 😦

**Comment by USERSATOSHI** [comment]
well memory is not equal to disk @falsisdev

**Comment by USERSATOSHI** [comment]
for disk if u are using pterodactyl server use their api

**Comment by falsisdev** [comment]
> well memory is not equal to disk @falsisdev 

Uh sorry
