### ISSUE TITLE
$botPing bug

### ISSUE THREAD

**Issue by TheGioXD** [aoijs/aoi.js#91]
![!ping](https://user-images.githubusercontent.com/83745961/117245138-2f764080-adef-11eb-93f3-6adcda327e2f.png)

```
module.exports = ({
name: "ping", 
code: `$description[Mensajes__($ping)__ - Api__($botPing)__ - DB__($dbPing)__]
$color[2475E3]`
});
```

Check out the AstroBot bot, -33 ping :u
and I use a host with 2GB ram 5GB disk and 100% cpu, it is not so much

**Comment by USERSATOSHI** [comment]
thats not a bug

its because ur local clock was behind systems clock

**Comment by Kino7916** [comment]
> thats not a bug
> 
> its because ur local clock was behind systems clock

^

We will change $ping and $botPing timezone to UTC timezone for better and accurate ping.
