### ISSUE TITLE
$setservervar | $getservervar saving globally.

### ISSUE THREAD

**Issue by Discord-Developer-Tech** [aoijs/aoi.js#93]
Functions: $setservervar | $hetservervar

Code used:

```
module.exports = ({
name: "setup-logs",
aliases: ['setlogs','setuplogs','set-logs'],
code: `
$channelsendmessage[$channelid;Everything is setup!]
$wait[5s]
$channelsendmessage[$getservervar[modlogs;$guildID];{title:TEST LOG!}{description:Test Successful!
Logs are all set up!}]
$wait[5s]
$channelsendmessage[$channelid;Testing logs...]
$setServerVar[modlogs;$channelID[spectrum-logs];$guildID]
$wait[5s]
$channelsendmessage[$channelid;Finalizing...]
$createChannel[spectrum-logs;text;no]
$wait[5s]
$channelsendmessage[$channelid;Setting up...]
`
})
```

Info: 
For my mod-logs command I use $set/$get servervar to save the channelID for the logs. However. When I used the command in 2 different servers the second server sent the logs to the first server. Meaning it's saving the vars globally to 1 server.

Aoi.js version: 1.0.6
Node.js version: 12.x
Operating system: Chrome
Screenshots (If any): N/A

**Comment by USERSATOSHI** [comment]
use findServerChannel instead
