### ISSUE TITLE
Add "Name" in TimeOut

### ISSUE THREAD

**Issue by KamexGaming** [aoijs/aoi.js#96]
ADD "Name"

$setTimeout[duration;timeout data;timeout heartbeat (optional);name]

bot.timeoutCommand({
name: "test",
//    channel: "ID", (This is optional)
    code: `$sendDM[$timeoutData[userID];$timeoutData[message]]`
});

**Comment by USERSATOSHI** [comment]
You can add name property in timeout data and use

$onlyIf[$timeoutData[name]==namehere;]

**Comment by KamexGaming** [comment]
> You can add name property in timeout data and use
> 
> $onlyIf[$timeoutData[name]==namehere;]
> @KamexGaming

thx <3

**Comment by Kino7916** [comment]
Closed Issue for Resolved.
