### ISSUE TITLE
create guild function

### ISSUE THREAD

**Issue by aa-aa44** [aoijs/aoi.js#97]
- [ ✓] Functions: $createGuild, $setGuildOwner
- [ ] Callbacks: 
- [ ] Handlers: 
- [ ] Others: 

## Description
Create a guild like 'client.guild.create' in djs
$createGuild[name;returns invite (yes/no)]
also
$setGuildOwner[user id] transfer the ownership of the server to a user if the guild owner was the bot

**Comment by USERSATOSHI** [comment]
> - [ ✓] Functions: $createGuild, $setGuildOwner
> - [ ] Callbacks: 
> - [ ] Handlers: 
> - [ ] Others: 
> 
> ## Description
> Create a guild like 'client.guild.create' in djs
> $createGuild[name;returns invite (yes/no)]
> also
> $setGuildOwner[user id] transfer the ownership of the server to a user if the guild owner was the bot

pretty useless because bot news to be below 10 guilds to actually able to create a guild

**Comment by USERSATOSHI** [comment]
![stated by Discord api](https://user-images.githubusercontent.com/73595362/117418801-753f2000-af39-11eb-8192-4a54d4e20041.png)

**Comment by aa-aa44** [comment]
oh, okay

**Comment by Kino7916** [comment]
Closed Issue for Inactivity.
